### ISSUE TITLE
CMS Agnostic?

### ISSUE THREAD

**Issue by kcristiano** [veda-consulting/uk.co.vedaconsulting.mosaico#1]
Just tested this and works in Drupal, but not WordPress. On a quick look it seems the URLs are being built based on a drupal file structure. Is the intent to support all 3 CMS?

**Comment by deepak-srivastava** [comment]
Thanks. Don't see any hurdles or code which is specific to CMS. Just that we haven't really tested on other CMS yet. We 'll roll out the fix in next alpha releases.

**Comment by deepak-srivastava** [comment]
@kcristiano latest release (alpha2) fixes the url issues. Might want to give it a try.

**Comment by kcristiano** [comment]
Thanks.  URL issues, fixed, however on save I get an error when completing the template and clicking done.   

I get an unable to contact server message and editing the tempate via http://exampl.org/wp-admin/admin.php?page=CiviCRM&q=snippet_2&snippet=2#kcd1teh#kcd1teh shows no content at all.
