### ISSUE TITLE
Tag 1.0-beta2?

### ISSUE THREAD

**Issue by totten** [veda-consulting/uk.co.vedaconsulting.mosaico#105]
Installing Mosaico currently requires a couple longish commands. I'd like to get us down to this:

```
cv dl --dev shoreditch flexmailer mosaico
```

That requires posting an updated pre-release on the extension directory. Suggestion: after merging #102, #103, #104, make a tag for `1.0-beta2`. Within a day, this will show up on the extension directory.

**Comment by deepak-srivastava** [comment]
Hi @totten,
 
We have had a look at the features and requirements.

Most of our clients are on v4.6 (LTS). And unofficial backport may be a turn off / hurdle.

And therefore think two release lines would be better for now. Master branch could become v2.0 and be tagged v2.0-beta2 ? And old beta1 could branch out & remain v1.0 series. Only fixes will go in v1.0, and would also be pushed to v2.0 if applicable.

It would still however be upto the user to decide which version to use. We 'll just need to document the difference clearly between the two versions.

Some points that needs to be documented for v2.0-x upgrades (unless supported) is 
- Old Mosaico Templates will need to be re-built. As they won't be available to be used with new civimail workflow. (We might have to build an 'import' function that solves this).
- New CiviMail Workflow - would only work with mosaico templates. There won't be any support for message templates.

Thoughts?

**Comment by totten** [comment]
@deepak-srivastava That policy sounds pretty balanced. I say let's go for it.

Other thoughts:

1. Don't think it'll be too hard to import/migrate content between the 1.0 message-templates and 2.0 mosaico-templates. (The 2.0 schema is basically a subset of the 1.0 schema.)
2. Agree that fixes can cross over as applicable. We probably shouldn't try to do any general `git merge` between 1.0/2.0 -- they'd just be separate pull-requests.
3. The [Jenkins build job](https://test.civicrm.org/view/Tools/job/Tool-Publish-mosaico/) tracks `master`. Should it also track `1.0`? (If you want this, I can set it up, but I'll need to backport much of `setup.sh`.)
4. I have a soft inclination for naming the branches `1.0`/`2.0` or `1.x`/`2.x` instead of `1.0`/`master`. Can't articulate a good reason, though. (Maybe because it's nice to have a symmetry among git-branches, version-numbers, and issue-labels? For non-developers browsing the issue-queue, labeling an issue as `master` might look weird?) It's not a blocker, but if you have a similar feeling, it's easier to change this now than later. Otherwise, it's not a big deal.

**Comment by deepak-srivastava** [comment]
@totten 
1. Yep, had a look. We can help with it.
2. Agree.
3. Think we can release it old way through git. Versions from 2.x can continue to use Jenkins.
Unless you think its going to cause any confusion or is inconsistent?
4. Lets go with 1.x and 2.x.
