### ISSUE TITLE
Installation problems (help wanted)

### ISSUE THREAD

**Issue by Upperholme** [veda-consulting/uk.co.vedaconsulting.mosaico#113]
Working through the [install instructions using Git](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico#installation-git).

When I run the setup script it generates a number of warnings and errors:

> npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@0.12.1: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN prefer global nave@0.5.3 should be installed with -g
npm WARN prefer global jshint@2.9.4 should be installed with -g

Then it gets to the point of trying to install phantomjs and throws an error:

> Error: Cannot find module '/path/to/extensions/directory/uk.co.vedaconsulting.mosaico/packages/mosaico/node_modules/phantomjs/install.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3

followed by:

> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN mosaico@0.15.0 No repository field.
npm WARN mosaico@0.15.0 license should be a valid SPDX license expression
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.16 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

Is this expected behaviour? Any clues as to why the setup script fails most welcome.

**Comment by totten** [comment]
@Upperholme, when I've had this kind of problem before, it was an issue with the version of NodeJS and/or NPM. For reference, the `npm install` step is working on my machine with these versions:

```
$ npm --version
3.5.2
$ node --version
v4.2.6
```

**Comment by pbatroff** [comment]
In case somebody else runs into this Problem: A working version for me currently is  [nodeJS 6](https://nodejs.org/dist/latest-v6.x/) . Haven't tried v8, definitely not working with NodeJS 10/11. Throws weird Exceptions and is unable to resolve dependencies.
