### ISSUE TITLE
Display issues in WordPress

### ISSUE THREAD

**Issue by bhahumanists** [veda-consulting/uk.co.vedaconsulting.mosaico#114]
Once you click on a design to edit, the mosaico iframe appears beneath the WordPress admin bar. 
(The WordPress admin bar is 160px as standard, so hopefully this is an easy one)

![screenshot_030117_054730_pm](https://cloud.githubusercontent.com/assets/5374634/23473248/66eca4e2-fea7-11e6-9486-07bddce8f50f.jpg)

**Comment by totten** [comment]
@bhahumanists , are you in a position to fiddle with [`ang/crmMosaico/Iframe.js`](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/7c16a8e/ang/crmMosaico/Iframe.js#L38) -- in particular, determining whether another value of `zIndex` or `width` fixes it? (The `zIndex` fix is probably ideal.)

@guanhuan @jamienovick, I know you were pretty passionate about absolutely taking the full screen. Wonder how you'd feel if a `zIndex` solution isn't possible?

**Comment by jamienovick** [comment]
Can we have an adaptation for wordpress that frees a left hand margin for the WordPress menu? I.e. full screen except the left hand menu?

**Comment by totten** [comment]
OK, I was fixing some other positioning issues, and I found a way to get the z-index to work on WP (#119). ce97093 is a little uglier than I like, but it works for me.

**Comment by bhahumanists** [comment]
yep, that looks good - thanks!

**Comment by totten** [comment]
Can someone close this?
