### ISSUE TITLE
Shoreditch extension .zip won't extract

### ISSUE THREAD

**Issue by kngs** [veda-consulting/uk.co.vedaconsulting.mosaico#115]
When I try an install the Shoreditch extension to support Mosaico on a 4.6 Civi install I get  the following message when trying to extract from the .zip file:
"Finished with some errors. The file may be corrupted or you may have reached your quota limit.
caution: filename not matched: \*"
Other .zip files extract work.  Is anybody else experiencing problems extracting Shoreditch (I've tried it on a few installs and no luck!)

**Comment by Upperholme** [comment]
Have you tried getting Shoreditch via git instead?

**Comment by kngs** [comment]
Yes, that didn't help BUT did find that my server's archive extractor has a bug that is triggered when the archive has a lot of files. Removing  the "*" in file mask field gets around it.

But now having problems installing flexmailer (I know, sorry, different topic):
Fatal error: Class 'Civi' not found in /home/greenleaf/www/civi45wp/wp-content/plugins/files/civicrm/extensions/org.civicrm.flexmailer-master/flexmailer.php on line 51
(Going to stick my head down that rabbit hole!)

**Comment by veda-consulting** [comment]
@kngs would be good if you could share how you fixed it?
