### ISSUE TITLE
Lengthen the 'name' column

### ISSUE THREAD

**Issue by kenwest** [veda-consulting/uk.co.vedaconsulting.mosaico#130]
When I try to save a template with the default name I get a database error "Data too long for column 'name' at row 1".

The name column is varchar(32) and the default name is "Mosaico Template dd/mm/yyyy, hh:mm:ss". Perhaps my local settings give a longer name than others.

32 characters seems too short. The corresponding column in the civicrm_msg_template field is varchar(255)

**Comment by totten** [comment]
FWIW, in 2.x, the analogous column is `varchar(64)`. But I think it's a good point that we can make it longer. Submitted fix for 2.x as part of #131.

**Comment by totten** [comment]
Looks like it was closed in 2.x and 1.x.
