### ISSUE TITLE
workaround imagemagick ?

### ISSUE THREAD

**Issue by DirkVR** [veda-consulting/uk.co.vedaconsulting.mosaico#137]
My webserver host doesn't allow installing imagemagick .... seems there is a security issue with script PHP function exec()
is there a way to work around this?

**Comment by deepak-srivastava** [comment]
The extension uses [Mosaico library](https://github.com/voidlabs/mosaico) which requires imageMagick. You might want to raise it with them and check?

**Comment by mattwire** [comment]
Resolved via #281
