### ISSUE TITLE
Imagemagick not found

### ISSUE THREAD

**Issue by mfuggle** [veda-consulting/uk.co.vedaconsulting.mosaico#14]
I am running alpha3 in Drupal 7. I have imagemagick installed on the server and Drupal is able to display details of version etc in Image Tools. However Mosaico templates show the following at the top of the page 'ImageMagick not installed'.
@mark-rodgers - Thanks for your comment Mark but I have read the instructions and ImageMagick is installed on the server and Drupal seems to find it without problem. I may be asking dumb questions but I am not that dumb that I don't read the instructions.

**Comment by mark-rodgers** [comment]
@mfuggle wasn't trying to offend was just trying to confirm it is installed.

**Comment by mfuggle** [comment]
@mark-rodgers - text is never a perfect tool for conveying intent!

**Comment by mfuggle** [comment]
It seems to be correctly installed since Drupal finds it and reports the version installed. When installing it in the Ubuntu14.04 LTS server no errors were reported.

**Comment by deepak-srivastava** [comment]
@mfuggle if you ignore error and go ahead with building a template, does that all work fine without problems?

Note: the error checks only triggers for initial installs i.e as long as there are no templates made (or saved). As soon as you have one, it stops doing checks.

Might be easier for you to debug / detect - what's wrong with the check - https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/master/CRM/Mosaico/Page/Index.php#L14
A PR would be most welcome & appreciated.

**Comment by mfuggle** [comment]
I am no developer but I found a php script which checks for ImageMagick. I can upload the script if necessary but the output is shown in the attached file
![imagemagick test](https://cloud.githubusercontent.com/assets/1777429/13897459/c0358216-ee05-11e5-8816-eaec11d89e12.jpg)

**Comment by mfuggle** [comment]
Got it - my stupidity. I had installed php5-imagick after I installed ImageMagick and failed to restart Apache. So this can now be closed.
Sorry for wasting everyone's time and effort
