### ISSUE TITLE
Mosaico file upload size issue

### ISSUE THREAD

**Issue by madurak** [veda-consulting/uk.co.vedaconsulting.mosaico#142]
Tried to upload an 1.8MB image and Mosaico shows an error message "File is too large".
If I try to upload again, the message does not show up any more but the image was never uploaded.
<img width="1163" alt="screen shot 2017-04-26 at 17 22 29" src="https://cloud.githubusercontent.com/assets/10810117/25445006/f989f7a4-2aa4-11e7-8350-1a079c638a4f.png">

This is not a issue on mosaico.io or civimail.

**Comment by totten** [comment]
Haven't really researched, but a couple quick notes:
 * File upload sizes are also dictated by the environment/server settings. However, if you're able to upload the same file to the same server using CiviMail, then that's probably not the issue.
 * The file `packages/mosaico/src/js/bindings/fileupload.js` does include a statement `maxFileSize: 1024 * 1024,`, but `mosaico.io` is running with a different version/value for that constant(?).

**Comment by totten** [comment]
Patch submitted in #216.

**Comment by totten** [comment]
Thanks for reporting, @madurak! Merged #216.
