### ISSUE TITLE
URL mismatch and 403 error when clicking on Mosaico template

### ISSUE THREAD

**Issue by mfuggle** [veda-consulting/uk.co.vedaconsulting.mosaico#15]
When I try to add the Mosaico tutorial template,for example, I get the following error:
`Warning: file_get_contents(http://www.quins.com.au/sites/default/files/civicrm/extensions/uk.co.vedaconsulting.mosaico/packages/mosaico/templates/tutorial/edres/_full.png): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden in CRM_Mosaico_Utils::getResource() (line 19 of /var/www/html/sites/default/files/civicrm/extensions/uk.co.vedaconsulting.mosaico/CRM/Mosaico/Utils.php).`
A similar error occurs on line 26 of Utils.php.
The reason for this as far as I can see is that the URL being accessed is uk.co.vedaconsulting.mosaico/etc whereas the files are located in uk.co.vedaconsulting.mosaico.1.0-alpha3/etc
This maybe caused by me not installing correctly but if that's the case I'm not sure where I have gone wrong.

**Comment by deepak-srivastava** [comment]
@mfuggle try going to civi'c extensions dir listings page, and click on refresh button. That should correct the paths, and also make sure to have one copy of extension.

**Comment by mfuggle** [comment]
Frankly I don't think this issue should be tagged 'help wanted'. Maybe help is wanted but I think the issue is not a 'user error' but a problem with the extension. I have performed a clean install with the following results:
- Image 1 - shows details of installed extension
- Image 2 - shows the Message Template builder screen
- Image 3 - shows the Drupal watchdog error indicating a 403 error when the xx shown in one of the templates is clicked. Note that the URL/file location is uk.co.vedaconsulting.mosaico
- Image 4 - shows the 403 error when trying to access the URL of the template image using URL uk.co.vedaconsulting.mosaico
- Image 5 - shows the 403 error when trying to access the URL of the template image using URL uk.co.vedaconsulting.mosaico-1.0.alpha3

It appears that there are inconsistencies in the URLs of the template images and also issues to do with permissions. But I am not planning on playing around with permissions in the CiviCRM extensions directory since this should be sorted out by the extension itself.
Is there anyone out there who has been able to install this extension successfully?

Martin
![image 1- mosaico extension details](https://cloud.githubusercontent.com/assets/1777429/14063707/4471809c-f429-11e5-8079-ea68f0a29cd5.png)
![image 2 - mosaico template screen](https://cloud.githubusercontent.com/assets/1777429/14063708/45c901ea-f429-11e5-9d91-70f55cce7d01.png)
![image 3 - mosaico watchdog error](https://cloud.githubusercontent.com/assets/1777429/14063709/48f45db0-f429-11e5-90e9-6ae5449aa95e.png)
![image 4 - mosaico 403 error 1](https://cloud.githubusercontent.com/assets/1777429/14063710/4e7761c4-f429-11e5-900c-5f78ba36d1c7.png)
![image 5 - mosaico 403 error 2](https://cloud.githubusercontent.com/assets/1777429/14063711/5125d662-f429-11e5-8bfa-1cc0c544ef1e.png)

**Comment by deepak-srivastava** [comment]
Sounds like https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/12. Where it suggests:
- work around is to adjust apache / hatccess config issue where the url being considered as absolute path, to invoke php handler.
- it does require a fix in extension code so urls look like: http://example.org/civicrm/mosaico/templates?file=versafix-1/edres/_full.png, instead of  http://example.org/sites/default/civicrm/extensions/uk.co.vedaconsulting.mosaico/packages/mosaico/templates/versafix-1/edres/_full.png (Any PRs most welcome).

**Comment by petednz** [comment]
suggested solution now at https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/12#issuecomment-203647558

**Comment by deepak-srivastava** [comment]
UPDATE: released alpha4 which attempts to resolve icon/image loading issues without requiring a web-sever config fix. Can somebody give that a try. Thanks.

**Comment by mfuggle** [comment]
I have installed release 4 and the result shows in the attached image where there is a mismatch in directories reported. I uninstalled, changed the extension directory as specified in the message and reinstalled. The result is tha same as already reported. That is the icons do not display etc etc.

![release 4 error](https://cloud.githubusercontent.com/assets/1777429/14218497/3ec1da72-f8a0-11e5-9333-299632e6080e.jpg)

**Comment by deepak-srivastava** [comment]
@mfuggle could you send/email me login details? i'll take a look.

**Comment by mfuggle** [comment]
You can access the website using webmaster/Yingally

Cheers...
*Martin Fuggle*
kew: 03 9817 1401 <tel:0398171401>
mobile: 04 0826 5586 <tel:0408265586>
skype: mfuggle <callto:mfuggle>
website www.martinfuggle.com <http://www.martinfuggle.com>

If you forward this message please delete my email address before you 
forward it to another party. For bulk mail  please use BCC rather than 
TO or CC. This will help keep email addresses as private as possible and 
might reduce spam and identity theft.

**Comment by deepak-srivastava** [comment]
@mfuggle Thanks for access. I have had a look. Extension configurations look correct. Its web server config thats denying access to absolute path - http://www.quins.com.au/sites/default/files/civicrm/extensions/uk.co.vedaconsulting.mosaico/packages/mosaico/templates/tedc15/edres/_full.png

Anything with http://www.quins.com.au/sites/default/files/civicrm* pattern throws a 403 permission error. Looks like some htaccess or web-server config thats denying it. Might want to check with your server admin.

**Comment by deepak-srivastava** [comment]
Closing this ticket as enhancements been done with Apha4. Please re-open image/icon loading issues with with extension and alpha4. Thanks.

**Comment by deepak-srivastava** [comment]
Enhancements were taken care by Alpha4. If still see any issues with this topic, please re-open the ticket. Thanks all.

**Comment by mfuggle** [comment]
I have had this looked at by a competent sysadmin and they conclude that the extension needs to solve this issue and the permissions on the civicrm directory should not be altered.

**Comment by deepak-srivastava** [comment]
@mfuggle Based on my checks on your setup (through UI) its not related to extension. Its a webserver config. 
However if you (or anyone else) able to locate / identify what part of extension is causing it, we 'll be happy to fix it.

**Comment by mfuggle** [comment]
Unfortunately I don't have the skills to do that so it seems we are not going to get to enjoy testing the extension which is a pity.
