### ISSUE TITLE
Event links converted wrongly

### ISSUE THREAD

**Issue by aydun** [veda-consulting/uk.co.vedaconsulting.mosaico#156]
If you add a link in a text block (either by Insert/Edit Link widget or source editing) to a Civi event as http://<my_site>/civicrm/event/info?reset=1&id=1 then it is rewritten as ../event/info?reset=1&id=1 which results in page not found.

**Comment by bhahumanists** [comment]
See: https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/165

**Comment by totten** [comment]
Thanks for reporting. It sounds like this was also reported and fixed in ^^^^. To be on the safe side, I've updated the TESTING.md notes to include a link the above.
