### ISSUE TITLE
Cannot upload image or save template on stable release V1

### ISSUE THREAD

**Issue by stoporko** [veda-consulting/uk.co.vedaconsulting.mosaico#158]
Hi, many thanks for this extension. Great work!

Our setup:
Drupal 7.5
civiCRM: 4.7.9
mosaico: stable version 1

After installation and enabling imagemagick with our host, everything seems fine. The problem appears, when I create and edit a new mosaico template. After uploading a new image, there is an error message: Unexpected error: internal server error.

From console log:
`abort: function ()
acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i
add: function (e, data)
autoUpload: true
bind: "fileupload: { data: _src, onerror: $root.notifier.error, onfile: $root.loadImage, canvasPreview: true }"
bitrate: 9911461.538461538
bitrateInterval: 500
blob: null
cache: false
canvasPreview: true
contentType: false
create: null
data: FormData
dataType: "json"
disableImageResize: false
disabled: false
dropZone: m.fn.init(1)
errorThrown: "Internal Server Error"
fileInput: m.fn.init(1)
files: Array(1)
forceIframeTransport: false
form: m.fn.init
formAcceptCharset: undefined
formData: function (form)
getNumberOfFiles: function ()
headers: Object
i18n: function (message, context)
imageCrop: false
imageMaxHeight: 1080
imageMaxWidth: 1920
imageOrientation: false
jqXHR: Object
limitMultiFileUploadSizeOverhead: 512
loadImageFileTypes: /^image\/(gif|jpeg|png|svg\+xml)$/
loadImageMaxFileSize: 10000000
loaded: 128849
maxFileSize: 1048576
messages: Object
multipart: true
onerror: function t(e,t,n)
onfile: function (e)
originalFiles: Array(1)
paramName: Array(1)
pasteZone: m.fn.init
previewCanvas: true
previewCrop: false
previewMaxHeight: 200
previewMaxWidth: 200
previewOrientation: true
previewThumbnail: true
process: function (resolveFunc, rejectFunc)
processData: false
processQueue: Array(9)
processing: function ()
progress: function ()
progressInterval: 100
recalculateProgress: true
replaceFileInput: false
response: function ()
sequentialUploads: false
singleFileUploads: true
state: function ()
submit: function ()
textStatus: "error"
total: 128849
type: "POST"
uploadedBytes: 0
url: "http://zivica.sk/databaza/civicrm/mosaico/upload"
xhr: function ()
_bitrateTimer: Object
_processQueue: Object
_progress: Object
_response: Object
_time: 1495626601820
__proto__: Object`

After trying to save the template, it throws another error: Unexpected error talking to server: Contact us. 
From log:
`fail (3) [Object, "error", "Internal Server Error", callee: (...), Symbol(Symbol.iterator): function]`

What shall I do? Many thanks for your help.

**Comment by deepak-srivastava** [comment]
Do you see anything specific in apache or php log?

It could be related to IDS error, but that's just a guess - https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/52#issuecomment-253535006.

Exact error will help drill down and fix the problem.

**Comment by stoporko** [comment]
Nope, nothing in logs.

**Comment by mattwire** [comment]
Please update to 2.0  1.x is no longer supported
