### ISSUE TITLE
Imagemagick not found

### ISSUE THREAD

**Issue by mfitzhugh** [veda-consulting/uk.co.vedaconsulting.mosaico#16]
Hi - I'm running into a problem similar to that encounters by @mfuggle in #14 as I try to get Mosaico working on my Civihosting account.

Although it seems clear that imageMagick is installed on Civihosting and the Drupal module is in place, the Message Template Builder (alpha3) displays an "ImageMagick not installed" message.

I'm not certain how to best troubleshoot this issue, but hope that by raising it that I might help highlight a stumbling block that others could run into. Any suggestions for how to get the extension working or on how to best further investigate this?

![imagemagick-not-found](https://cloud.githubusercontent.com/assets/183787/14062803/efddd9e6-f369-11e5-9222-dcb97d5f5ec8.png)

<img width="751" alt="civihosting-cpanel-imagemagick-installed" src="https://cloud.githubusercontent.com/assets/183787/14062805/f5634d42-f369-11e5-83b6-915391b745e6.png">

<img width="905" alt="imagemagick-drupal-module" src="https://cloud.githubusercontent.com/assets/183787/14062806/fca7d8ca-f369-11e5-8371-be0da2b2370d.png">

Thanks!
- Michael

**Comment by mfuggle** [comment]
Actually I no longer get the ImageMagick Not Found error but still see the same screen as displayed by  @mfitzhugh above. I am going to uninstall everything to do with the extension and see if a fresh start gives a different outcome.
Cheers
Martin Fuggle

**Comment by deepak-srivastava** [comment]
@mfuggle you can force the check with http://example.org/civicrm/mosaico/index?reset=1&runcheck=1 (note runcheck=1 arg). It stops doing auto checks once you have a template "saved".

**Comment by deepak-srivastava** [comment]
@mfitzhugh your screenshot of "installed software" does say that ImageMagick is installed, but NOT - if its installed as a PHP module. 

The extension requires ImageMagick as PHP module. This might help verify - http://stackoverflow.com/questions/4208253/verify-imagemagick-installation

**Comment by mfitzhugh** [comment]
Thanks for pointing out the need for me to install the ImageMagick php module @deepak-srivastava. I remedied that and verified its success using one of the test scripts suggested on the StackOverflow page you shared. Now I'm in the same place as @mfuggle, in that I no longer get the ImageMagick Not Found error but still see the "broken" images of the templates. Furthermore, when I click on one (such as https://members.toool.us/snippet_2?snippet=2#templates/#templates/versafix-1/template-versafix-1.html), I'm sent to a page that auto-launches a "print" dialogue box.

**Comment by PalanteJon** [comment]
I also get the "print" dialogue box - I'd ignored it because it only
happened on one of my test machines (Firefox 45/Linux) so I wrote it off
as a fluke on my end.

**Comment by mfuggle** [comment]
I don't see a print dialogue box but I get this strange URL which has the title 'Printer-Friendly View | CiviCRM'. The URL is http://example.com.au/civicrm/mosaico/editor?snippet=2#02mckux. I am also using Firefox 45.0.1. I'll try another browser...

**Comment by mfuggle** [comment]
Same thing happens when using Chrome. If I click the Show button I can see an entry for the Template I have previously attempted to edit. There are two black buttons to the right of the template detail. The first should say Edit and the second Delete. If I click the edit button I get the Printer Friendly stuff. Clicking the Delete button does in fact delete the template. I have performed the ImageMagick checks and according to the StackOverflow check ImageMagick works just fine and displays the Hello World graphic successfully.
![mosaico extension](https://cloud.githubusercontent.com/assets/1777429/14097940/ad42d9b4-f5c2-11e5-984f-e28296d0bf22.jpg)

**Comment by deepak-srivastava** [comment]
@mfitzhugh @mfuggle Ok so thats now down to image loading issues. Given that there are already issues for them - https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/12 and https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/15, i would like to close this one.

**Comment by petednz** [comment]
solution suggested at https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/12#issuecomment-203647558

**Comment by deepak-srivastava** [comment]
@petednz thanks for sharing. Closing this ticket now.
