### ISSUE TITLE
CKeditor not disappearing and layout looses styling when choosing a mosaico template

### ISSUE THREAD

**Issue by blauraum** [veda-consulting/uk.co.vedaconsulting.mosaico#161]
Thank you for this great plugin, the builder works perfectly and makes creating mails so much better.
However, in our setup, when we try to select a created mosaico-template for send out, the CKeditor does not disappear and the the layout looses some of it's styling.
Powered by CiviCRM 4.7.19., same happens in Firefox 53.0.3 (64-bit) and Chrome 58.0.3029.110 (64-bit).
Screenshots attached
Do you have an idea what might be the problem?

Thanks and Regards

![in_firefox](https://cloud.githubusercontent.com/assets/3189727/26568025/64485dde-4543-11e7-93ca-6db3110a72f9.png)
![from chrome](https://cloud.githubusercontent.com/assets/3189727/26567982/0d9ce946-4543-11e7-8c9d-e44b01905019.png)
![desired_look_sent_from_builder](https://cloud.githubusercontent.com/assets/3189727/26567981/0d98d36a-4543-11e7-8eaf-abeb3ab8cf31.png)
![sent_from_civi](https://cloud.githubusercontent.com/assets/3189727/26567983/0da1eee6-4543-11e7-87a6-dba53f204a6a.png)

**Comment by MegaphoneJon** [comment]
@blauraum It appears that you're using the 1.x branch of the extension, not the 2.x branch.  Can you please confirm?

If so - the answer is to upgrade to the 2.x branch.  It's still in beta, but it should meet your needs.  Someone can correct me if I'm wrong - but I think at this time there's no direct upgrade path for your templates.

**Comment by veda-consulting** [comment]
Hi @Jon

I dont think thats the answer!

The v2 branch is different in a few respects, including needing the themes
etc. The v1 branch is a lighter install but doesn't come with the wizard.

@blauraum we'll come back to you with possible solutions a bit later today
or tomorrow morning.

Thanks

**Comment by blauraum** [comment]
Hi and thanks. Any news on this very appreciated. Am I right that a send out with the look created in builder should be possible? 
In addition following question: what's the best practice to add a footer section with address, unsubscribe link etc: as a section in the builder or adding a footer section through the civiCRM to the mosaico template?

**Comment by deepak-srivastava** [comment]
@blauraum Do you have any specific configurations / filters for CKEditor that allows some content but not others (e.g ACF, allowedcontent..)?

In v4.7, way to check is goto Administer >> Customize Data & Screens >> Display Preferences, click on Configure CKEditor.

CKeditor has gone under some changes in 4.7 - https://civicrm.org/blog/colemanw/big-changes-to-wysiwyg-editing-in-47, giving more control to users to control options from UI.
Possible that there is some config thats doing the filtering / stripping?

**Comment by blauraum** [comment]
Hi, thank you, updating to the latest version helped - above problem is now solved!
Now the mails stay integer, except when testing the forwarding option: pictures don't display in the forwarded mails and token links (view in browser) also don't seem to work. Do you have any suggestions regarding this issue?
Thanks and Regards.

**Comment by mattwire** [comment]
For the pictures issue see #160

**Comment by blauraum** [comment]
Thank you, we'll look into that.

**Comment by mattwire** [comment]
Please update to 2.0  1.x is no longer supported
