### ISSUE TITLE
CiviMail / Mosaico integration

### ISSUE THREAD

**Issue by mark-rodgers** [veda-consulting/uk.co.vedaconsulting.mosaico#17]
Is there any plans or discussion on if/when this extension will become more integrated into the CiviMail workflow? This way a template will not need to be created every time a new email wants to be sent out but instead you would create a draft but have some sort of Mosaico integration on that page so you can put together emails on the fly and send them out quickly? Potentially like a CKEditor replacement as far as CiviMail is concerned.

**Comment by deepak-srivastava** [comment]
Thats the ultimate goal that we do have on our list. IMO that also means - tighter integration with new angular js model of civimail with configured "email template builder" of choice, more efforts, some funding, acceptance by civicrm-core. 
Staying as an extension (outside civicrm) and integrating with civimail is even more effort in terms of maintenance.

@veda-consulting might have better ideas on discussions being planned and / or how this is going to be pushed.

**Comment by deepak-srivastava** [comment]
Have had a discussion with @veda-consulting. We might take the route of having a new civimail journey that becomes available in civi with this extension, and is more native to email template builders (mosaic in this case). This way we 'll cut down some effort on integration.

**Comment by BettyDolfing** [comment]
Thanks for the effort! I will certainly follow the developments. I will demonstrate Mosaic as an extension during CiviCon NW Europe and I expect clients will be enthousiastic. However, same comments here about the template.

**Comment by totten** [comment]
Just a bit of follow-up... integration between Mosaico the CiviMail pageflow is the primary change in 2.x. So generally that's been addressed.
