### ISSUE TITLE
Packages folder missing in download but referenced in code --> no images

### ISSUE THREAD

**Issue by kngs** [veda-consulting/uk.co.vedaconsulting.mosaico#170]
I'm test driving Mosaico 2.0 on a drupal install and found that the packages folder in the /sites/default/files/civicrm/ext/uk.co.vedaconsulting.mosaico/ directory does not exist in the download but is referenced in the code.  As a result no template images are showing up (similar to issue https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/12).  I found that if I copy the packages folder over from a 1.x mosaico version (WP install) it solved my problem.  Is the packages folder suppose to be there or is there a misconfiguration issue? Thanks!

**Comment by JKingsnorth** [comment]
@kngs please check the new installation instructions on the readme: https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/2.x/README.md

The packages folder is not part of this project any more, and the patched Mosacio library is held here: https://github.com/civicrm/mosaico

But if you download the mosaico extension from the CiviCRM extensions repository: https://civicrm.org/extensions/email-template-builder - then the 'packages' folder is already included :)

**Comment by kngs** [comment]
Thank you - that did the trick!
Once the 2.x extension is available through the GUI old versions' pacakges folders will update automatically, but in the mean time, do I need to replace the old package folder from 1.x I uploaded on previous 2.0 installs or will that version still work without creating potential problems?
Thanks again - Karen

**Comment by JKingsnorth** [comment]
I would guess it is better to put the new civicrm forked mosaico library on all of the ones you've upgraded to 2.x.
