### ISSUE TITLE
Mobile Preview View

### ISSUE THREAD

**Issue by stevekessler** [veda-consulting/uk.co.vedaconsulting.mosaico#173]
I see Mosaico can have a mobile preview 

<img width="713" alt="screen shot 2017-07-10 at 5 50 37 pm" src="https://user-images.githubusercontent.com/867985/28045108-6efcdb04-6598-11e7-9f1a-22cf518b850a.png">

What would be involved in enabling this for the CiviCRM version of Mosaico?

-Steve

**Comment by rocxa** [comment]
You just need a monitor with high enough resolution for that button to appear in CiviCRM.  The button gets hidden if your screen is too small.

**Comment by totten** [comment]
Thanks @rocxa. I was also confused by this too (how the button shows and disappears sometimes), but I've confirmed your comment, and now it makes more sense. The preview actually needs horizontal screen space -- so it wouldn't very usable on a narrow screen.

I guess one could maybe do a popup instead? IMHO, that would really be more of a feature request for upstream.
