### ISSUE TITLE
'mosaico' is not a valid option for field template_type

### ISSUE THREAD

**Issue by bryancn** [veda-consulting/uk.co.vedaconsulting.mosaico#174]
Using D7/4.7.22. In trying to troubleshoot what turned out to be [#165](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/165) I uninstalled the (working) beta version of mosaico and reinstalled v1.0. Now I get an empty civcrm screen when trying to create a new mailing or the message ''mosaico' is not a valid option for field template_type' when trying to duplicate an existing mailing. Also, no Mosaico items in the Mailings menu, even after a cache clear and menu rebuild. Is there a procedure for a clean uninstall so I can try again?

**Comment by totten** [comment]
When you go to the "New Mailing" screen, you see some kind of widget for composing the message. In CiviMail classic and in Mosaico v1.x, this is `ckeditor`. (These mailings are marked `template_type`=`traditional`.) In Mosaico v2.x, there's an "Edit"  button that opens Mosaico in a popup. (These mailings are marked `template_type`=`mosaico`.) It sounds like you have some leftover records from the Mosaico 2.x experiment.

You'd have to dig into the SQL level to work with them, and I've never had to deal with your situation, so... make a backup before doing anything. ;)

You can do a search:

```sql
select id, name, template_type  from civicrm_mailing where template_type ='mosaico';
```

In theory, it *might* work to downgrade those mailings to `traditional` format. (In the future, you wouldn't be able to re-edit/re-use as elegantly in 2.x, but it's probably better than the situation you've described above.)

```sql
update civicrm_mailing set template_type = 'traditional' where template_type ='mosaico';
```

Or if the goal is get to a clean baseline, then maybe just delete them:

```sql
delete from civicrm_mailing where template_type ='mosaico';
```

**Comment by totten** [comment]
Feel free to reopen if there's some other aspect that needs action.
