### ISSUE TITLE
Mosaico in CiviCRM on Joomla menu z-index

### ISSUE THREAD

**Issue by brucew2013** [veda-consulting/uk.co.vedaconsulting.mosaico#176]
I did see the post for Wordpress but since this is for Joomla decided to start a new thread. Installed and integrated flawlessly in CiviCRM. Please watch this screencast illustrating the issue.
[https://youtu.be/VxvYf0G9GIk](https://youtu.be/VxvYf0G9GIk)

PHP 7.0.x
CiviCRM 4.7.22
Joomla 4.7.4
Browsers: Waterfox/Firefox/Cliqz or Chrome latest versions

**Comment by eruraindil** [comment]
Your issue can probably be solved similar to mine in #190. You need to find the identifier of the Joomla menu and offset the mosaico iframe so they don't conflict.

**Comment by brucew2013** [comment]
Which PR please?

**Comment by eruraindil** [comment]
PR #190

**Comment by totten** [comment]
Joomla variant is #199.

**Comment by totten** [comment]
Thanks all! Merged #199.
