### ISSUE TITLE
Not able to load/access

### ISSUE THREAD

**Issue by mediasunrise** [veda-consulting/uk.co.vedaconsulting.mosaico#18]
Civicrm 4.7.7 with WordPress 4.5.2.  Just installed it and tried to create a new template and got a blank screen. See attached.  Here are the error messages from the console.

http://mydomain.org/home/domain/public_html/wp-content/plugins/files/…ulting.mosaico-1.0-alpha4/packages/mosaico/dist/vendor/knockout.js?r=hpNAV Failed to load resource: the server responded with a status of 404 (Not Found)
http://mydomain.org/home/domain/public_html/wp-content/plugins/files/….mosaico-1.0-alpha4/packages/mosaico/dist/mosaico-material.min.css?r=hpNAV Failed to load resource: the server responded with a status of 404 (Not Found)
http://mydomain.org/home/domain/public_html/wp-content/plugins/files/…rm/extensions/uk.co.vedaconsulting.mosaico-1.0-alpha4/js/index2.js?r=hpNAV Failed to load resource: the server responded with a status of 404 (Not Found)
http://mydomain.org/home/domain/public_html/wp-content/plugins/files/…1.0-alpha4/packages/mosaico/dist/vendor/notoregular/stylesheet.css?r=hpNAV Failed to load resource: the server responded with a status of 404 (Not Found)
http://mydomain.org/home/domain/public_html/wp-content/plugins/files/…m/extensions/uk.co.vedaconsulting.mosaico-1.0-alpha4/css/index.css?r=hpNAV Failed to load resource: the server responded with a status of 404 (Not Found)
http://mydomain.org/home/domain/public_html/wp-content/plugins/files/…crm/extensions/uk.co.vedaconsulting.mosaico-1.0-alpha4/js/index.js?r=hpNAV Failed to load resource: the server responded with a status of 404 (Not Found)
3(index):454 WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Error during WebSocket handshake: Unexpected response code: 403
http://mydomain.org/home/domain/public_html/wp-content/plugins/files/….mosaico-1.0-alpha4/packages/mosaico/dist/mosaico-material.min.css?r=hpNAV Failed to load resource: the server responded with a status of 404 (Not Found)
http://mydomain.org/home/domain/public_html/wp-content/plugins/files/…m/extensions/uk.co.vedaconsulting.mosaico-1.0-alpha4/css/index.css?r=hpNAV Failed to load resource: the server responded with a status of 404 (Not Found)
http://mydomain.org/home/domain/public_html/wp-content/plugins/files/…1.0-alpha4/packages/mosaico/dist/vendor/notoregular/stylesheet.css?r=hpNAV Failed to load resource: the server responded with a status of 404 (Not Found)
![screen capture](https://cloud.githubusercontent.com/assets/19416006/15336838/b663445e-1c35-11e6-975d-6a16434c8d1d.jpg)

**Comment by mediasunrise** [comment]
By the way, starting looking for the files and I confirmed that they seem to be on my server.

**Comment by deepak-srivastava** [comment]
@mediasunrise 
1. one the points in instructions is to keep the directory name as "uk.co.vedaconsulting.mosaico" (and NOT like e.g - uk.co.vedaconsulting.mosaico-1.0-alphaX) to avoid any icon / image loading issues.

2. To the "Message Template Builder" screen url, if you append "&runcheck=1", do you see any errors reported?

**Comment by mediasunrise** [comment]
Thanks, updated the directory and tried "&runcheck=1" but still a blank 
screen.  I see that the directory structure is incorrect.  It is going 
here for the files:

http://mydomain.org/home/username/public_html/wp-content/plugins/files/…co.vedaconsulting.mosaico/packages/mosaico/dist/vendor/knockout.js?r=jrYIt

But the files are located here:
http://mydomain.org/wp-content/plugins/files/…co.vedaconsulting.mosaico/packages/mosaico/dist/vendor/knockout.js?r=jrYIt

My CiviCRM Extensions Directory is set-up properly. Any idea why this 
would happen?

Nina

------ Original Message ------

**Comment by deepak-srivastava** [comment]
Is your extension resource url setup correctly?

**Comment by mediasunrise** [comment]
Yes, it is setup correctly.  I just downloaded your Alpha5, but the same 
problem:

http://mydomain.org/home/username/public_html/wp-content/plugins/files/…ng.mosaico/packages/mosaico/dist/vendor/notoregular/stylesheet.css?r=EuX59 
Failed to load resource: the server responded with a status of 404 (Not 
Found)
http://mydomain.org/home/username/public_html/wp-content/plugins/files/…co.vedaconsulting.mosaico/packages/mosaico/dist/vendor/knockout.js?r=EuX59 
Failed to load resource: the server responded with a status of 404 (Not 
Found)
http://mydomain.org/home/username/public_html/wp-content/plugins/files/civicrm/extensions/uk.co.vedaconsulting.mosaico/js/index.js?r=EuX59 
Failed to load resource: the server responded with a status of 404 (Not 
Found)
http://mydomain.org/home/username/public_html/wp-content/plugins/files/…aconsulting.mosaico/packages/mosaico/dist/mosaico-material.min.css?r=EuX59 
Failed to load resource: the server responded with a status of 404 (Not 
Found)
http://mydomain.org/home/username/public_html/wp-content/plugins/files/civicrm/extensions/com.imba.sendgrid-3.0-beta1/js/sendgrid.js?r=EuX59 
Failed to load resource: the server responded with a status of 404 (Not 
Found)
http://mydomain.org/home/username/public_html/wp-content/plugins/files/civicrm/extensions/uk.co.vedaconsulting.mosaico/js/index2.js?r=EuX59 
Failed to load resource: the server responded with a status of 404 (Not 
Found)
http://mydomain.org/home/username/public_html/wp-content/plugins/files/civicrm/extensions/uk.co.vedaconsulting.mosaico/css/index.css?r=EuX59 
Failed to load resource: the server responded with a status of 404 (Not 
Found)
(index):451 WebSocket connection to 
'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' 
failed: Error during WebSocket handshake: Unexpected response code: 403
http://mydomain.org/home/username/public_html/wp-content/plugins/files/civicrm/extensions/uk.co.vedaconsulting.mosaico/css/index.css?r=EuX59 
Failed to load resource: the server responded with a status of 404 (Not 
Found)
http://mydomain.org/home/username/public_html/wp-content/plugins/files/…ng.mosaico/packages/mosaico/dist/vendor/notoregular/stylesheet.css?r=EuX59 
Failed to load resource: the server responded with a status of 404 (Not 
Found)
http://mydomain.org/home/username/public_html/wp-content/plugins/files/…aconsulting.mosaico/packages/mosaico/dist/mosaico-material.min.css?r=EuX59 
Failed to load resource: the server responded with a status of 404 (Not 
Found)

------ Original Message ------

**Comment by deepak-srivastava** [comment]
@mediasunrise what is your extension resource url set to?

**Comment by mediasunrise** [comment]
/home/username/public_html/wp-content/plugins/files/civicrm/extensions

------ Original Message ------

**Comment by deepak-srivastava** [comment]
@mediasunrise thats incorrect. That looks like a directory path than url. Should be something like:
http://mydomain.org/wp-content/plugins/files/...path-to-extensions-dir/

**Comment by mediasunrise** [comment]
When I attempt to put in an absolute path I get an error message.  I 
used the info at this url to find my path, and it worked. My other 
extensions are working with this path. I asked a more senior developer 
if this was the correct path and he indicated that it was.

http://civicrm.stackexchange.com/questions/6254/enabling-extensions-directory-not-found

"You can tell by looking in your civicrm.settings.php file that's in 
wp-content/plugins/civicrm and scrolling down to the file paths. One of 
them will be to the templates_c folder, which should normally be in 
wp-content/plugins/files/civicrm. That path will be all the way to the 
root of your server, so you can just copy that and replace templates_c 
with custom_ext."



------ Original Message ------

**Comment by deepak-srivastava** [comment]
@mediasunrise Think you are confused between "extension directory" and "extension resource url".

1. Extensions directory - Can be navigated as "Administer » System Settings » Directories"
Needs to be configured with absolute directory path.
And you are correct if you talking about extensions directory.

E.g: /home/username/public_html/wp-content/plugins/files/civicrm/extensions

2. Extensions resource url - Can be navigated as "Administer » System Settings » Resouce URLs".
This is the base url through which resources (css, js) of your extensions are accessible to the web.

E.g: http://mydomain.org/wp-content/plugins/files/civicrm/extensions

Hope that clarifies.

**Comment by mediasunrise** [comment]
Ok, that did provide progress, but still not loading.  New error 
message:

index.js:26 Uncaught ReferenceError: ko is not defined

------ Original Message ------

**Comment by deepak-srivastava** [comment]
Does it now show any messages for runcheck=1 in the url?

**Comment by mediasunrise** [comment]
No it does not.  Now I see a red screen for a second before it goes 
blank.

------ Original Message ------

**Comment by deepak-srivastava** [comment]
Which browser you trying on?

**Comment by mediasunrise** [comment]
Chrome but I just tried Firefox too and same results. Thanks again for 
your help.

------ Original Message ------

**Comment by deepak-srivastava** [comment]
Sorry out of ideas. Can i have a look at your install?

**Comment by mediasunrise** [comment]
Yes, give me your email address and I will give you access.  Thanks for 
your help.

------ Original Message ------

**Comment by mediasunrise** [comment]
We just moved the site to a new server where we have better control and better access to error messages.  Here is what I get when I try to load this extension.

Uncaught Reference Error: ko is not defined(anonymous function) 
@ index.js?r=m3dj8:26(anonymous function) 
@ index.js?r=m3dj8:106

**Comment by deepak-srivastava** [comment]
Sounds like a JS error. Does runcheck=1 report anything?

**Comment by mediasunrise** [comment]
No it does not.

Not sure if this will help:

https://github.com/Knockout-Contrib/Knockout-Validation/issues/259


------ Original Message ------

**Comment by deepak-srivastava** [comment]
How many browsers you tried. Same result for all?

**Comment by deepak-srivastava** [comment]
No reply for some time. Closing this ticket. Please reopen if still an issue with latest release. Thanks.
