### ISSUE TITLE
"Table 'log_civicrm_mosaico_template' doesn't exist" errors when creating new Mosaico template

### ISSUE THREAD

**Issue by universalhandle** [veda-consulting/uk.co.vedaconsulting.mosaico#180]
CiviCRM version 4.7.17. Extension version 2.0-beta3.1499897730.

The error can be triggered either through the UI or via the API explorer (api.MosaicoTemplate.create) when CiviCRM detailed logging is enabled. It appears that the extension/CiviCRM fail to create the log table.

Error details from CiviCRM log:

```
Aug 16 11:43:26  [info] $Fatal Error Details = Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => exceptionHandler
        )

    [code] => -18
    [message] => DB Error: no such table
    [mode] => 16
    [debug_info] => INSERT INTO civicrm_mosaico_template (title ) VALUES ('hi' )  [nativecode=1146 ** Table 'civicrm_dev.log_civicrm_mosaico_template' doesn't exist]
    [type] => DB_Error
    [user_info] => INSERT INTO civicrm_mosaico_template (title ) VALUES ('hi' )  [nativecode=1146 ** Table 'civicrm_dev.log_civicrm_mosaico_template' doesn't exist]
    [to_string] => [db_error: message="DB Error: no such table" code=-18 mode=callback callback=CRM_Core_Error::exceptionHandler prefix="" info="INSERT INTO civicrm_mosaico_template (title ) VALUES ('hi' )  [nativecode=1146 ** Table 'civicrm_dev.log_civicrm_mosaico_template' doesn't exist]"]
)
```

**Comment by bhahumanists** [comment]
Does disabling logging and re-enabling fix it? That sometimes creates the necessary triggers for me. I haven't had this particular issue, though.

**Comment by mattwire** [comment]
@GinkgoFJG Is this still an issue, can it be closed?  I don't think it's directly related to the extension as log tables can be missing for various reasons.

**Comment by mattwire** [comment]
@GinkgoFJG Can you close this issue as it's not an issue with the mosaico extension but a local database issue that should be fixable by disabling/re-enabling logging.  Mosaico doesn't do anything with the logging tables.
