### ISSUE TITLE
Unexpected Upload Error - Internal Server Error

### ISSUE THREAD

**Issue by sohalkhatwani** [veda-consulting/uk.co.vedaconsulting.mosaico#181]
Been trying to solve this one for a while. We have most of the extension working (V 1.0) on our test site. The site is on Windows PHP 5.6.20, IIS 8.5, Drupal 7.56, CiviCRM 4.6.30. Whenever we upload an image it uploads for a second and then we get an error of Unexpected Upload Error - Internal Server Error. We have tried changing the upload directory permission, using the VC Runtime uploads, re-added imagemagik etc. Nothing seems to work. We noticed that the image actually uploads correctly and can be seen on the server. When using standard CiviMail we can upload and image and select it without any issues so I don't think it is a permission problem. Is this a bug? 
![screen shot 2017-08-18 at 1 11 31 pm](https://user-images.githubusercontent.com/11778532/29442860-9c34f3e8-8417-11e7-83a4-e7b4b22911a3.png)

**Comment by ivanask** [comment]
I am getting "Unexpected upload error" when trying to upload image in Email Template Builder.

Use case:
1) Environment: Hosted (Linux) website on SiteGround + Joomla + CiviCRM
Versions
PHP 7.0.29
Joomla! 3.8.6
CiviCRM 4.7.31

2) Installation/administration: I have read the post [Mosaico CiviCRM integration](https://civicrm.org/extensions/email-template-builder)
then manually downloaded and installed the following extensions:  CiviCRM Bootstrap theme and FlexMailer and installed (it's one of the listed extensions) the extension: Mosaico.

Applied the following being already stated in [this post](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/36):
> php.ini needs to be edited in the webroot to include
> extension=imagick.so
> ** ALSO ** .htaccess needs to be edited to include the line
> SetEnv PHPRC /path/to/php.ini

Tried several PHP code snippets and running ImageMagick from a cron job:
`/usr/bin/convert public_html/image.jpg -resize 64x64 public_html/resize_image.jpg`
It is all working.

The error ImageMagick not installed is cleared from the Message Template Builder but within CiviCRM System Status I have the error "the ImageMagick library is not installed. The Email Template Builder extension will not work without it."
And I am getting "Unexpected upload error" when trying to upload image in Email Template Builder.
As a result I am not able to upload the image.

**Comment by mattwire** [comment]
Please update to 2.0  1.x is no longer supported
