### ISSUE TITLE
Control image size

### ISSUE THREAD

**Issue by kngs** [veda-consulting/uk.co.vedaconsulting.mosaico#187]
Hi,
Thank you for Mosaico!
Is there a way to control the image size (other than small, medium and big widths)?
Is there a way to get to the html of the image blocks?
I was able to put an image tag directly in a text block (where I have access to html) ! (edited bad URLs)
Is any way to control image size?
Thanks, Karen

**Comment by bmango** [comment]
I think this enhancement would be very helpful as well. It would be great to be able to insert custom sized images.
