### ISSUE TITLE
Mosaico extension can overwrite content of previously sent mailing and send again

### ISSUE THREAD

**Issue by andrewperry** [veda-consulting/uk.co.vedaconsulting.mosaico#189]
If you continue a mailing in Mosaico in two different windows and send it from one, you can continue editing it in the other and then send it again, which should not occur.

You should not be able to continue editing a mailing that has been Scheduled, Sent or Cancelled without duplicating it.

Issue detected on Drupal 7 with latest CiviCRM 4.7.24

**Comment by MegaphoneJon** [comment]
I believe this is the same as [CRM-20892](https://issues.civicrm.org/jira/browse/CRM-20892), and is a problem with core CiviCRM.  If so, there's a patch in review to fix this - you may want to test it and report your results to speed its inclusion.

**Comment by totten** [comment]
Thanks @andrewperry and @MegaphoneJon . Agree this sounds like the same as CRM-20892, which has been closed upstream.
