### ISSUE TITLE
Allow CKEditor on rendered Templates

### ISSUE THREAD

**Issue by shawnholt** [veda-consulting/uk.co.vedaconsulting.mosaico#19]
This is a fantastic tool and brilliant integration. I understand the risk that users can "Break" the email using CKeditor and therefore it is disabled but for many use-cases this gets us 90% of the way and the 10% is critical to workflow, etc.  This is especially true for email to contact that use templates or integrating tokens.  

Can we set CKEditor as an option to enable/disable and tweak the generated HTML?

**Comment by deepak-srivastava** [comment]
@shawnholt Thanks. Its not an option yet. But think it 'll be good to have. 

Incase anybody else is interested in doing it, code that disables / hides the editor is here - https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/master/js/crmMailingCustom.js#L44

**Comment by shawnholt** [comment]
Great.  Other than disabling that code to hide the editor are there any other considerations that occur to you?

**Comment by dptarrant** [comment]
Hi,

I am testing this extension as well.

I have not been successful in loading images.  I get the same response as
reported - image flashes in template but then disappears.  When I load the
template into CiviMail, the images are missing.   I can add them with
CKEditor but there are inconsistencies.

Also, when I select a template, it opens my print dialog (Windows).  When I
close that I go back to the Mosaico template.

I will continue to test but I wanted to add my observations.

I also am very excited about this extension and would like to help.

Thanks

Dave

On Thu, May 26, 2016 at 8:41 AM, shawnholt <notifications@github.com> wrote:

> Great. Other than disabling that code to hide the editor are there any
> other considerations that occur to you?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/19#issuecomment-221859679>
>



-- 
David Tarrant
617-901-2513 (m)
dptarrant@gmail.com

**Comment by shawnholt** [comment]
Also, as noted in #19 to track with enhancement request:
while I understand the rational to hide the CKeditor I would suggest editor is hidden that we at least notifying the user that it is hidden on purpose. 

Civicrm already has a notion of message templates (actually a few ....) and this approach is inconsistent and therefore there is an expectation that the user can edit.

**Comment by deepak-srivastava** [comment]
@shawnholt Agree. We 'll add the fix in our next releases. An option, and a message if its hidden by default.

As usual, any PRs most welcome.

**Comment by psampont** [comment]
I try this alpha-5 version and this version works already very well.

But I don't understand why CKEditor is blocked when I define a mailing. If I use CKEditor, I change the mail but not the template, no ?

Would not it be better to simply prevent to save the template ? By hiding the disk icon? Or by changing the mode of the "Save the template" window : from"update" mode to "add" mode ?

**Comment by shawnholt** [comment]
@psampont please see #19 #21 . If you are to send PR to accelerate.  Think we all agree that good enhancement.

**Comment by psampont** [comment]
My PR is available. Thank you for review.

**Comment by deepak-srivastava** [comment]
@psampont your PR has been merged. Will be part of next release. Thanks.

**Comment by shawnholt** [comment]
Fantastic!  Last release was a month ago.  any thoughts on next release?

**Comment by shawnholt** [comment]
Tested and this works great!
Would be nice if we could put tokens in the template but now that we have ckeditor, we can add manually and "Save as new template".

Strongly suggest you do a release.

**Comment by deepak-srivastava** [comment]
Thanks. Have pushed a new release.
