### ISSUE TITLE
Fatal error: could not find valid value for id

### ISSUE THREAD

**Issue by waddyvic** [veda-consulting/uk.co.vedaconsulting.mosaico#191]
Environment: Drupal 7.56 + CiviCRM 4.7.24 + Mosaico 2.0-beta3.1499897730.

When CiviCRM's scheduled task tried to send a mailing created using traditional mailing system, the job log returned the fatal error "could not find valid value for id". The backtrace pointed to uk.co.vedaconsulting.mosaico/mosaico.php(294): CRM_Utils_Request::retrieve('id', 'String', NULL, true). It looks like the old mailing doesn't provide "id" in the $_REQUEST array and triggered this error. Should mosaico.php check the existence of "id" before proceeding?

Here's the complete backtrace:

{
    "trace": "0 sites/all/modules/civicrm/CRM/Utils/Request.php(120): CRM_Core_Error::fatal('Could not find ...')
1 sites/default/files/civicrm/custom_ext/uk.co.vedaconsulting.mosaico/mosaico.php(294): CRM_Utils_Request::retrieve('id', 'String', NULL, true)
2 sites/default/files/civicrm/custom_ext/uk.co.vedaconsulting.mosaico/mosaico.php(365): _mosaico_civicrm_replaceTokens('<p><img src=\"ht...', true)
3 sites/all/modules/civicrm/CRM/Utils/Hook.php(274): mosaico_civicrm_alterMailParams(Array, 'civimail')
4 sites/all/modules/civicrm/CRM/Utils/Hook/DrupalBase.php(85): CRM_Utils_Hook->runHooks(Array, 'civicrm_alterMa...', 2, Array, 'civimail', NULL, NULL, NULL, NULL)
5 sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(90): CRM_Utils_Hook_DrupalBase->invokeViaUF(2, Array, 'civimail', NULL, NULL, NULL, NULL, 'civicrm_alterMa...')
6 [internal function]: Civi\\Core\\CiviEventDispatcher::delegateToUF(Object(Civi\\Core\\Event\\GenericHookEvent), 'hook_civicrm_al...', Object(Civi\\Core\\CiviEventDispatcher))
7 sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Civi\\Core\\Event\\GenericHookEvent), 'hook_civicrm_al...', Object(Civi\\Core\\CiviEventDispatcher))
8 sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'hook_civicrm_al...', Object(Civi\\Core\\Event\\GenericHookEvent))
9 sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php(170): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('hook_civicrm_al...', Object(Civi\\Core\\Event\\GenericHookEvent))
10 sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(47): Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->dispatch('hook_civicrm_al...', Object(Civi\\Core\\Event\\GenericHookEvent))
11 sites/all/modules/civicrm/CRM/Utils/Hook.php(164): Civi\\Core\\CiviEventDispatcher->dispatch('hook_civicrm_al...', Object(Civi\\Core\\Event\\GenericHookEvent))
12 sites/all/modules/civicrm/CRM/Utils/Hook.php(1080): CRM_Utils_Hook->invoke(Array, Array, 'civimail', NULL, NULL, NULL, NULL, 'civicrm_alterMa...')
13 sites/all/modules/civicrm/CRM/Mailing/BAO/Mailing.php(1355): CRM_Utils_Hook::alterMailParams(Array, 'civimail')
14 sites/all/modules/civicrm/CRM/Mailing/BAO/MailingJob.php(648): CRM_Mailing_BAO_Mailing->compose('1967', '325941', '91094f4528da4b0...', '94276', 'victor.huang@sk...', NULL, false, Array, Array, false, NULL, '\"The Lung Assoc...')
15 sites/all/modules/civicrm/CRM/Mailing/BAO/MailingJob.php(580): CRM_Mailing_BAO_MailingJob->deliverGroup(Array, Object(CRM_Mailing_BAO_Mailing), Object(Mail_mail), '20171002100709', Array)
16 sites/default/files/civicrm/custom_ext/org.civicrm.flexmailer/src/Listener/Abdicator.php(75): CRM_Mailing_BAO_MailingJob->deliver(Object(Mail_mail), NULL)
17 [internal function]: Civi\\FlexMailer\\Listener\\Abdicator->onRun(Object(Civi\\FlexMailer\\Event\\RunEvent), 'civi.flexmailer...', Object(Civi\\Core\\CiviEventDispatcher))
18 sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Civi\\FlexMailer\\Event\\RunEvent), 'civi.flexmailer...', Object(Civi\\Core\\CiviEventDispatcher))
19 sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\\Component\\EventDispatcher\\EventDispatcher->doDispatch(Array, 'civi.flexmailer...', Object(Civi\\FlexMailer\\Event\\RunEvent))
20 sites/all/modules/civicrm/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php(170): Symfony\\Component\\EventDispatcher\\EventDispatcher->dispatch('civi.flexmailer...', Object(Civi\\FlexMailer\\Event\\RunEvent))
21 sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(47): Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->dispatch('civi.flexmailer...', Object(Civi\\FlexMailer\\Event\\RunEvent))
22 sites/default/files/civicrm/custom_ext/org.civicrm.flexmailer/src/FlexMailer.php(211): Civi\\Core\\CiviEventDispatcher->dispatch('civi.flexmailer...', Object(Civi\\FlexMailer\\Event\\RunEvent))
23 sites/default/files/civicrm/custom_ext/org.civicrm.flexmailer/src/FlexMailer.php(177): Civi\\FlexMailer\\FlexMailer->fireRun()
24 sites/default/files/civicrm/custom_ext/org.civicrm.flexmailer/src/FlexMailer.php(148): Civi\\FlexMailer\\FlexMailer->run()
25 [internal function]: Civi\\FlexMailer\\FlexMailer::createAndRun(Object(CRM_Mailing_BAO_MailingJob), Object(Mail_mail), NULL)
26 sites/all/modules/civicrm/Civi/Core/Resolver.php(119): call_user_func_array(Array, Array)
27 sites/all/modules/civicrm/CRM/Mailing/BAO/MailingJob.php(198): Civi\\Core\\Resolver->call('\\\\Civi\\\\FlexMaile...', Array)
28 sites/all/modules/civicrm/CRM/Mailing/BAO/Mailing.php(2951): CRM_Mailing_BAO_MailingJob::runJobs(NULL, NULL)
29 sites/all/modules/civicrm/api/v3/Job.php(317): CRM_Mailing_BAO_Mailing::processQueue()
30 sites/all/modules/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_job_process_mailing(Array)
31 sites/all/modules/civicrm/Civi/API/Kernel.php(169): Civi\\API\\Provider\\MagicFunctionProvider->invoke(Array)
32 sites/all/modules/civicrm/Civi/API/Kernel.php(100): Civi\\API\\Kernel->runRequest(Array)
33 sites/all/modules/civicrm/api/api.php(23): Civi\\API\\Kernel->runSafe('Job', 'process_mailing', Array, NULL)
34 sites/all/modules/civicrm/CRM/Utils/REST.php(404): civicrm_api('Job', 'process_mailing', Array)
35 sites/all/modules/civicrm/CRM/Utils/REST.php(641): CRM_Utils_REST::process(Array, Array)
36 [internal function]: CRM_Utils_REST::ajax()
37 sites/all/modules/civicrm/CRM/Core/Invoke.php(276): call_user_func(Array)
38 sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem(Array)
39 sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke(Array)
40 sites/all/modules/civicrm/drupal/civicrm.module(448): CRM_Core_Invoke::invoke(Array)
41 [internal function]: civicrm_invoke('ajax', 'rest')
42 includes/menu.inc(527): call_user_func_array('civicrm_invoke', Array)
43 index.php(20): menu_execute_active_handler()
44 {main}",
    "is_error": 1,
    "error_message": "A fatal error was triggered: Could not find valid value for id"
}

**Comment by totten** [comment]
Thank you for the backtrace!

@waddyvic, it looks like you're running the proposed patch from https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/pull/182 ?

The backtrace shows a couple curious things:
 * There are calls to `mosaico_civicrm_alterMailParams` and `CRM_Utils_Request::retrieve()` -- but those don't currently appear in `2.x`. (They do, however, appear in proposal #182.)
 * There's a call  from`Abdicator.php(75)` to `CRM_Mailing_BAO_MailingJob->deliver()`. This suggests that FlexMailer isn't supposed to handle the delivery -- e.g. this particular mailing is a "traditional", non-Mosaico CiviMail blast.

Assuming that you are using #182... I'd like to close #191, because I think we're going to make some changes and wind up with a different PR. You might want to follow the discussion on #182 to see where it winds up.

Feel free to re-open if I've misinterpreted.
