### ISSUE TITLE
Advanced Settings popup stays open when switching pages

### ISSUE THREAD

**Issue by mukeshcompucorp** [veda-consulting/uk.co.vedaconsulting.mosaico#195]
**Steps to Reproduce:**
1. Open any Mailing or New Mailing
2. Go Upto step 3 (Options)
3. Click on _Advanced Mailing Options_
4. Now, without closing popup Go to Menu > Mailings >  Mosaico Templates
5. Templates page will be shown with popup of _Advanced Mailing Options_

**Bug Screenshot:**
![0403158778_template_manager_0_body_0_desktop](https://user-images.githubusercontent.com/26058635/31171510-96cc1262-a91d-11e7-89c7-caf74c73e5f1.png)

**Browser:**
All

**Desired Output:**
Templates page should open without popup

**Comment by mukeshcompucorp** [comment]
@totten Please see above one

**Comment by totten** [comment]
Merged #214.
