### ISSUE TITLE
Is it possible to keep a link to a traditional email in the mailings menu?

### ISSUE THREAD

**Issue by themak1985** [veda-consulting/uk.co.vedaconsulting.mosaico#197]
This is more a feature enhancement than an issue.  Historically, our organization would use the traditional civicrm email system to send announcements and emails to certain individuals and groups - such as event participants or selected members. We would then use Mailchimp for our newsletters and general mailings.  Now with mosaico, we are making the switch and while there are some hiccups as expected in a beta, we are generally happy. 

Would it be possible to include a menu item in the mailings menu that links to 
DOMAIN/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fa%2F#/mailing/new/traditional
(wordpress)

We manually added it in the mean time, but it would be great if it was included in the plugin.

**Comment by totten** [comment]
Resolved by f082c52084e51d9c60f43f649df07218a777a333
