### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by laurynnlowe** [veda-consulting/uk.co.vedaconsulting.mosaico#198]
Source code button does not seem to work well initially, and then not at all on repeat edits.

I've added minor pieces of code --a few images, alignment, links-- and what does not work is not consistent: the image will come through, but not the alignment. When I go back to edit the alignment, and hit OK, the images no longer display. Same problem with changing the size of an image: the image stops displaying completely on OK. The image tag is still there in the source code, but not showing in the WYSIWYG text field.

**Comment by mattwire** [comment]
Please update to 2.0  1.x is no longer supported
