### ISSUE TITLE
Images upload but dont display

### ISSUE THREAD

**Issue by R-Frost** [veda-consulting/uk.co.vedaconsulting.mosaico#20]
firstly thank you very much for this extension - this is really exciting.

Extension is working just fine.. all except for the images .. Uploaded images show for a second or so and then up comes the JSON error and images disappear. Firefox/Chrome the same 

Wordpress 4.5.2 Civi 4.6.16 extension Alpha 5 resource URLs set

edit: I just did a bit of digging.. the images actually are being uploaded.. going to plugins/files/civicrm/persist/contribute

my image upload URL: is set to wp-content/plugins/files/civicrm/images
Extension Resource URL : wp-content/plugins/files/civicrm/extensions/

**Comment by deepak-srivastava** [comment]
@R-Frost Shouldn't extension resource url start with http(s) ?

1. If you using alpha5 (latest), adding "&runcheck=1" to the "Message Template Builder" url, should tell you if something is wrong with extension resource url.

1. If you hover over the section where you uploaded the image, and inspect, console should give you the url its using to display the image. Most likely its the wrong url.

**Comment by R-Frost** [comment]
ok.. Ill try and muddle through this.. please bear with me...

1 resource URLS : I only put the last bit in.. the full Extension Resource URL is:
http://mysite.com/wp-content/plugins/files/civicrm/extensions/

2 Message builder URL is: 
wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fmosaico%2Findex&reset=1

nothing happened  when I ran: 
wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fmosaico%2Findex&reset=1&runcheck=1 

3 hovering over the upload shows nothing that I could see.  On the (Chrome) console there is this error message: 

fileupload.js:304 fileuploadfail m.Event {type: "fileuploadfail", timeStamp: 1464315247625, jQuery1113048052895248850946: true, target: input.fileupload.nofile, isTrigger: 3…} Object {disabled: false, create: null, dropZone: m.fn.init[1], replaceFileInput: false, singleFileUploads: true…}

thanks for going through this - I sure hope Im not doing something basic wrong :)

**Comment by R-Frost** [comment]
Ok after a lot of mucking around and experimenting.. the issue seems to be missing directories: (&runcheck=1 showed no errors)

my image path is: wp-content/plugins/files/civicrm/persist/contribute/images

the extension expects to find: 
wp-content/plugins/files/civicrm/persist/contribute/images/uploads/thumbnails

once I created the extra directories, all works really well - and the images appear in the gallery

thanks again.. this is going to be great

**Comment by deepak-srivastava** [comment]
@R-Frost glad it sorted out for you. 

As far as i understand it doesn't need thumbnail directory. It creates an image of size thumbnail on the fly using ImageMagick. 

Similar problem happened for me when i was testing it on wordpress with incorrect image upload url for which i 've made runcheck to detect it - https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/commit/2a0384cd1f0c5d44aca97ef8c23de349a4fe9e00

Not sure what else could cause it. May be its some other directories along with it, that solved for you? If you come to know, do let us know. Thanks.
