### ISSUE TITLE
Allow writable directory to be placed elsewhere

### ISSUE THREAD

**Issue by herbdool** [veda-consulting/uk.co.vedaconsulting.mosaico#200]
_[Update: Someone had told me that this extension required the extensions directory to be writable for installing, etc. But I can't replicate it yet using v2 so maybe this isn't an issue.]_

We are forced to attempt to make a symlink from this extension's writable directory to sites/default/files/civicrm. On our host, the code is locked down on live so we cannot have any extension attempt to write to it. And we put extensions in our code repository so the extensions are locked down. Everything that does try to write is put into sites/default/files/*

Please make it possible to set the path for any directories that need to be writable.

**Comment by mattwire** [comment]
There is now a setting for a custom template for so I don't think this is an issue anymore @herbdool can it be closed?

**Comment by herbdool** [comment]
@mattwire I think we can close this. Just checked https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/2.x/settings/Mosaico.setting.php -- it seems that it defaults to [civicrm.files] and can be changed.

(I did a quick test in Pantheon and the admin page wasn't showing the fields, but I think that is a different issue.)
