### ISSUE TITLE
Image upload button vanishes before it can be used on Chrome

### ISSUE THREAD

**Issue by tim1mw** [veda-consulting/uk.co.vedaconsulting.mosaico#201]
When using Mosaico v1 (with Wordpress 4.8.3 and CiviCRM 4.7.23) on Chrome the upload image button sometimes displays too far away from the active area of the page associated with the image for it to be clickable, the button always vanishes before the you can get the mouse pointer over the button to click it.

![vanish1](https://user-images.githubusercontent.com/11174402/32320515-e718c658-bfb5-11e7-9d15-d9d6ec431697.jpg)
![vanish2](https://user-images.githubusercontent.com/11174402/32320517-eaaccc2e-bfb5-11e7-8089-906931475781.jpg)

**Comment by totten** [comment]
That box looks odd -- it should like this:

<img width="734" alt="screen shot 2017-12-07 at 4 45 49 pm" src="https://user-images.githubusercontent.com/1336047/33745851-282b0498-db6e-11e7-80fd-0849ff365873.png">

The background image (with the dimensions and diagonal bars) should be produced by `civicrm/mosaico/img`, and this visual suggests something's going wrong in calling that. There's more discussion about trying to diagnose this in #186.

**Comment by nganivet** [comment]
@tim1mw I had the same issue and this was due to the ImageMagik library not present. After installing it on the server everything works.
@totten Maybe we could add a error message when installing and/or bootstrapping Mosaico if any hard requirement is unmet.

**Comment by mrandraspal** [comment]
I have to same problem and only on Chrome even in incognito mode. I have ImageMagick running too.
