### ISSUE TITLE
Mosaico only shows 25 templates

### ISSUE THREAD

**Issue by pbatroff** [veda-consulting/uk.co.vedaconsulting.mosaico#202]
In the template overview (civicrm/a/#/mosaico-template) a maximum of 25 templates are shown. If more templates are created, they temporarily show up (and correctly), but once the browser cache is cleared they just disappear. There are no error logs or interaction in the UI.

This happens when the templates are pulled from the Database, the default limit of elements is 25. Other templates are not shown.

A good long term solution would be to implement a a pager for a bigger amount of templates, but for now it would be best to just pull all available templates. The limit (correctly) needs to be set to zero.

**Comment by pbatroff** [comment]
I added a PR with a proposed solution with option limit set to 0 (PR #203)

**Comment by totten** [comment]
Resolved by #203.
