### ISSUE TITLE
Unable to place images 

### ISSUE THREAD

**Issue by rkensey** [veda-consulting/uk.co.vedaconsulting.mosaico#205]
When I try and place image I get a quick flash of the image and then it disappears.  I am using CIVICRM
on WordPress. Mosaico 1.0 and Shoreditch civicrm bootstrap theme and flexmailer installed.  The image box on all of the blocks look odd .  

<img width="893" alt="screen shot 2017-11-14 at 4 06 24 pm" src="https://user-images.githubusercontent.com/33670629/32805807-8b10de70-c958-11e7-90b9-f9ee54af7280.png">

**Comment by totten** [comment]
Agree that box looks odd -- it should like this:

<img width="734" alt="screen shot 2017-12-07 at 4 45 49 pm" src="https://user-images.githubusercontent.com/1336047/33745851-282b0498-db6e-11e7-80fd-0849ff365873.png">

The background image (with the dimensions and diagonal bars) should be produced by `civicrm/mosaico/img`, and this visual suggests something's going wrong in calling that. There's more discussion about trying to diagnose this in #186.
