### ISSUE TITLE
Using mosaico template causes Civi email to not show

### ISSUE THREAD

**Issue by R-Frost** [veda-consulting/uk.co.vedaconsulting.mosaico#21]
1 I create a template - all fine

2  start new email in Civi using the template I just created - template shows momentarily then whole email text area closes

3 remove the template from the mailing and the text area reappears with the template in it

4 work on email and send - all fine

Wordpress 4.5.2 /Civi 4.6.16 / extension Alpha 5 / resource URLs set

**Comment by deepak-srivastava** [comment]
@R-Frost Thats on purpose. Idea is to not allow updating mosaico templates using ckeditor. Ideally it would be the template editer (mosaico builder) somewhere in between.

Here is one discussion about making this an option - https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/19

**Comment by shawnholt** [comment]
BTW - While I understand the rational - I would suggest at least notifying the user as it does not seem intuitive (it is a totally different metaphor for email templates than usual.)  Will cross - post on #19 .

**Comment by R-Frost** [comment]
Yes I did see that comment and I understand a bit more now thanks

You can actually edit the "template" in the normal Civi editor if you simply remove "using template" option.. the mosaico "template" stays there and is editable.. and yes you can sure muck it up no matter how careful

on the other hand you can also use spell check, tokens etc and all the other goodies that are usually available

and I do agree with shawnholt  about terminology.. in this case the "template" IS the email  NOT the template on which the email is based..

but the end result- whatever its called - is a great step forward.. Im really impressed and grateful:  happy to help if I can

**Comment by deepak-srivastava** [comment]
Closing it now. Has been resolved with @R-Frost 's PR - https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/pull/22
