### ISSUE TITLE
Errors when CIVICRM_MAIL_SMARTY enabled

### ISSUE THREAD

**Issue by bhahumanists** [veda-consulting/uk.co.vedaconsulting.mosaico#23]
If CIVICRM_MAIL_SMARTY is set to 1 in civicrm.settings.php, the smarty engine dies when processing the mosaico html. Presumably the {} brackets in the CSS declarations, but I'm not certain of that.

Had a poke around but couldn't see a way to dynamically overridde that setting for the duration of sending the email. Hopefully there's a way! We use smarty logic in templates a lot, so can't disable it entirely :-(

(also: this extension is awesome! Can't wait to show it to our communications team, who regularly despair of their templates breaking in ckeditor)

**Comment by shawnholt** [comment]
Ah nice catch! That is definitely important for many sites.

**Comment by deepak-srivastava** [comment]
Update: Latest beta release has this fixed. Please re-open the ticket if you still see any issues. Thanks.

**Comment by mcollopy** [comment]
Deepak, Smarty still not working on Version 2.0-beta4.
Smarty code just shows up literally.
Running CivicrM 5.4.0
CKEditor entities are 'false'

This is really important for my client - please help.

**Comment by mattwire** [comment]
@mcollopy is your client able to offer any funding to resolve it?

**Comment by mcollopy** [comment]
Matt I wasn't aware it was a new development requirement - see https://civicrm.org/blog/deepaksrivastava/email-template-builder-civimosaico-is-now-beta
See"CIVICRM_MAIL_SMARTY flag is now supported with templates i.e you could now use smarty codes in templates, just like with any message templates."
At some point the developers (Deepak I presume) were satisfied it was working.
Could we please understand the status first before going to clients and asking for funding, as we have recommended Mosaico on the assumption of Smarty support.

Are you from Veda Consulting MAtt?  I couldn't see that on your profile.
If not then I understand you may be offering your services if paid.
If Veda are not able to address this then its a consideration.
Thanks

**Comment by mattwire** [comment]
@mcollopy I'm not from veda, I run my own consultancy. However, just investigating this kind of issue is normally a couple of hours work for someone, eg. 
* Does it happen on all installations?
* Which version of CiviCRM / XYZ did it previously work on if it is not doing now?
* Is it a simple fix, or something that requires more thought?
* Has a more recent change to mosaico broken this again?

Some of those questions you might be able to help answer by investigating a little further yourself?  But otherwise, Veda, or someone else will need to commit resources to answer those questions and that costs money :-)

**Comment by bhahumanists** [comment]
@mcollopy this was specifically disabled in v2 - I think [this comment](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/pull/252#issuecomment-392979047) partially explains why. As far as I understand, Mosaico and Smarty both use {...} for syntax, and it's nigh-on impossible to parse both.

(But fwiw we would also be willing to put some money towards this feature, if anyone found a way.)

**Comment by mcollopy** [comment]
@bhahumanists Wow, thanks for the update, but that's come as a shock, as I realise now that issue search is filtered on 'open' by default, so I wasn't aware.
As a workaround, I found that I could extract the HTML out of a Mosaico built template from a test email, and paste into a traditional email body where smarty will work.
I believe we can live with this - use traditional email where smarty is required, Mosaico for marketing emails, and in exceptional cases use the method above.
However it seems a shame not to go 'all Mosaico' so perhaps I could convince clients to contribute financially if there is a known solution.
