### ISSUE TITLE
WordFence blocks from saving templates

### ISSUE THREAD

**Issue by KilakwaBT** [veda-consulting/uk.co.vedaconsulting.mosaico#230]
I have come across a conflict with the WordFence security plugin and saving Mosaico templates. After content edit it gives a cannot save notice. Once I leave the page I find the following in the WordFence firewall info:

<<visitor info>> left https://<<site url>>/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fa%2F and was blocked by firewall for XSS: Cross Site Scripting in POST body: json=%7B%22id%22%3A%222%22%2C%22domain_id%22%3A%221%22%2C%22reply_id%22%3A%228%22%2C%22unsubscribe_id%22%… at https://<<site url>>/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fajax%2Frest

If I 'Whitelist param from firewall' all works as designed. The other option is to disable WordFence (not preferred). THis site is using CiviCRM 4.7.27, WordpRess 4.9.1 and Mosaico 2.0 beta4. 

I have noticed this on a few sites that we are demoing Mosaico on. This could just be a WordFence issue that has to be dealt with on a site by site basis but i thought I would put it here so that folks are aware.

This is such a great extension and the most recent version is running very smoothly aside from this firewall issue.

Thanks

**Comment by totten** [comment]
I've never used WordFence, but the Mosaico connection seems circumstancial/happenstance --  the end-point `civicrm/ajax/rest` handles a lot of data for many different Civi use-cases (in core and in extensions), and any extension that submits large documents to `civicrm/ajax/rest` could have problems with it. It sounds like we basically need a way to distribute that whitelist rule to any CiviCRM installations.

Can you get the WordFence folks to add a general whitelist rule for `civicrm/ajax/rest`?

Or, if they can't do that, perhaps they provide an API which `civicrm-wordpress` can use to generally whitelist `civicrm/ajax/rest`?

Barring that... best bet is to patch`civicrm-core` or `civicrm-wordpress` to display a nag screen to anyone running WordFence.

**Comment by kcristiano** [comment]
@KilakwaBT Can you export you WF settings file and send to me?  I'd like to test this.   I've been able to have success as long as I either move the extension directory to `wp-content/civicrm/ext/` or disable `Disable Code Execution for Uploads directory` in the security plugin.

More and more the security plugins are disabling direct calls to php in the uploads AND plugins directory.  While this works well for WP alone, CiviCRM has many places where the code is called directly and this presents an issue of do we get rid of a security plugin (not a good option) find a way to allow the code to work (but possibly not hardening as much as we want), or moving to a true WAF (too expensive for most clients).

**Comment by themak1985** [comment]
@KilakwaBT  - Not sure if you resolved this issue already - but we had the same issue - we resolved the issue within Wordfence.

1.  First - in Wordfence - go to global options - then View Customization and make sure live traffic and blocking are enabled.

2.  Attempt to save a template in Mosaico - then immediately go to Live Traffic and find the param that was blocked - then whitelist it. 

3. If its still an issue - go to blocking and remove the block if its there.

**Comment by jusfreeman** [comment]
This is a problem specific to WordFence, recommend this issue be closed.

Included the steps to fix the issue in the documentation would help other CiviCRM / WordPress sites.
