### ISSUE TITLE
Smarty Errors when logged in and viewing message in browser 

### ISSUE THREAD

**Issue by pbatroff** [veda-consulting/uk.co.vedaconsulting.mosaico#233]
When I send a mailing, and I want to view the message in the browser with the provided link, and I am logged in, the drupal log is spammed with smarty errors.
If the template is really large, a PDO Exception is thrown with the smarty error because the error is too big (> max_allowed_packet_size). It doesn't seem to happen when I am **not** logged into Civi (e.g. incognito browser).

The Question is: How can these errors be prevented? 

System Information: 
Civi 4.7.22
Drupal 7.54
Mosaico: 2.0-beta3
FlexMailer: 0.2alpha2
shoreditch: 0.1-alpha8

Happens in versafix-1 template (unmodifed)

**Comment by MegaphoneJon** [comment]
If someone with permissions to close tickets sees this, this was fixed a while back in https://github.com/civicrm/org.civicrm.flexmailer/pull/21.
