### ISSUE TITLE
suggestion for workflow enhancement - duplicate a template

### ISSUE THREAD

**Issue by R-Frost** [veda-consulting/uk.co.vedaconsulting.mosaico#24]
reuse a template - 2 options

 1 ability to duplicate a template.. At present when you save with a new name it overwrites the old one

2 Upload a saved template - You can download one but not upload it

**Comment by deepak-srivastava** [comment]
The metadata is stored in civicrm_mosaico_msg_template table, which makes it easier to provide the option in civi, like "re-use" option for civi-mailings.

**Comment by axon-obriend** [comment]
+1 for this request. We've shown this extension to a couple of clients and the lack of being able to copy an existing Mosaico template, make changes and save as a different template is key for one of them.

**Comment by deepak-srivastava** [comment]
Update: Beta release now has a "copy" feature that allows duplicating a template. Any issues please re-open the ticket. Thanks.
