### ISSUE TITLE
Feature Request: Hide Base Templates

### ISSUE THREAD

**Issue by themak1985** [veda-consulting/uk.co.vedaconsulting.mosaico#241]
We have set up one template for our users - that one template meets our needs.  However - there are the three base templates + the template we created on display for users.  Is it possible to either choose what templates are displayed (ideally) or alternatively to hide base templates from non-admins.  

As you can see from this [Stack Exchange](https://civicrm.stackexchange.com/questions/22832/hide-base-templates-in-mosaico/22858#22858), other users have found their own ways with dealing with the templates.

**Comment by totten** [comment]
To improvise a downstream fix:
 * I agree that deleting an unused base-template is pretty quick/simple.
 * One could probably implement `hook_civicrm_mosaicoBaseTemplates` and remove any unused base-templates.
 * One could probably inject some CSS. (Or, with a small patch to the Angular HTML, make the CSS possible.)

However, those are improvised downstream fixes. I can see how this might be a more common problem. 

Just to verbalize some designs, maybe....

* Allow some kind of extra permissioning -- such that users with more advanced permissions can see more templates? (Trick: *How to make this work without breaking existing installs?*)
* In the management screen for Mosaico templates, change the "Settings' to a bigger dialog. Provide some options for activating/deactivating each one.

**Comment by lcdservices** [comment]
FYI, I was looking to do this as well and tried option 2 -- unsetting some of the templates using `hook_civicrm_mosaicoBaseTemplates` -- and that throws console errors: "TypeError: Cannot read property 'title' of undefined". I suspect the list of templates is loaded in another way as well, so even though you remove it here, the js is cycling through the expected list and throwing errors when it can't find it.

**Comment by francescbassas** [comment]
I am a supporter of directly removing the default base templates from the extension. In any case put them in another extension.

In case of keeping them, leave them hidden by default or at most make visible the versafix that I guess is the only one that is really being used.

**Comment by howardshand** [comment]
Was just setting this extension up and was looking for an option similar to the second design @totten suggests. Any chance of a revisit of this feature request.

For others the workaround we implemented was:
- in the Mosaico Custom Templates Directory defined at '/civicrm/admin/mosaico?reset=1' (we had to create the folder mosaico_tpl) copy the template(s) you like from '/uk.co.vedaconsulting.mosaico/packages/mosaico/templates' and edit the names of the folder and the template-*.html and any other element within that file that you want to customize. Then delete the folders in '/uk.co.vedaconsulting.mosaico/packages/mosaico/templates', this will need to be done again after every update.

**Comment by elcapo** [comment]
Just in case it's useful for someone, implementing this in a custom extension worked to me:

``` php
/**
 * Implements hook_civicrm_mosaicoBaseTemplates().
 *
 * @link https://docs.civicrm.org/mosaico/en/latest/api/
 */
function myext_civicrm_mosaicoBaseTemplates(&$templates) {
  unset($templates['tutorial']);
  unset($templates['tedc15']);
  unset($templates['versafix-1']);
}
```

**Comment by kurund** [comment]
There are few issues when we directly unset using base templates.
* Template listing crashes if all base templates are hidden
* Configured templates directly derived from base template are not displayed.

Base template array is used to determine few things for configured templates hence we can't directly unset it. I am getting the error mentioned by Brain here: https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/issues/241#issuecomment-384384190

Here is the PR attempting to address the above mentioned issues: https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/pull/442
