### ISSUE TITLE
Hardcoded path to templates in civicrm_mosaico_template table, metadata column

### ISSUE THREAD

**Issue by jackrabbithanna** [veda-consulting/uk.co.vedaconsulting.mosaico#243]
We started using this extension for a client, and the client made several templates.  When we refreshed our dev instance of the client site, we noticed that we could not edit existing templates.

Turns out that the "template" property in the metadata column of the civicrm_mosaico_template table hard codes a path to the html template file in the extension directory. 

It seems like these should automatically adjust when CiviCRM is moved to a new domain, or that the domain should pull from a setting or something so to make moving sites to a new domain, or maintaining dev/staging instances easier.

**Comment by totten** [comment]
Yup, it's a good point. There is an existing issue #87, so I'll close as duplicate.
