### ISSUE TITLE
Preheader: View In Browser 

### ISSUE THREAD

**Issue by sandrajvillagenetwork** [veda-consulting/uk.co.vedaconsulting.mosaico#244]
The preheader - 'View in browser' link for mass emails doesn't work correctly if not logged into the site. The current token for 'view in browser' {mailing.viewUrl} only displays as a full URL link and there is no option to update the display text for 'view in browser'. Only an option to update the URL and display text for 'unsubscribe'

**Comment by Upperholme** [comment]
Running Civi 5.10.4 with Flexmailer 1.0-beta1, Mosaico 2.0-beta4.1528762072 and I'm seeing the same issue: even when the mailing is set to 'public page' the 'view in your browser' link does not work and generates a syntax error if not logged in.

`Mar 13 09:57:59  [info] $Fatal Error Details = Array
(   
    [callback] => Array
        (   
            [0] => CRM_Core_Error
            [1] => exceptionHandler
        )
    
    [code] => -2 
    [message] => DB Error: syntax error
    [mode] => 16 
    [debug_info] => SELECT id, display_name FROM civicrm_contact WHERE id in () [nativecode=1064 ** You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1]
    [type] => DB_Error
    [user_info] => SELECT id, display_name FROM civicrm_contact WHERE id in () [nativecode=1064 ** You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1]
    [to_string] => [db_error: message="DB Error: syntax error" code=-2 mode=callback callback=CRM_Core_Error::exceptionHandler prefix="" info="SELECT id, display_name FROM civicrm_contact WHERE id in () [nativecode=1064 ** You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1]"]
)


Mar 13 09:57:59  [info] $backTrace = #0 /home/foo/sites/default/sites/all/modules/civicrm/CRM/Core/Error.php(948): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 [internal function](): CRM_Core_Error::exceptionHandler(Object(DB_Error))
#2 /home/foo/sites/default/sites/all/modules/civicrm/packages/PEAR.php(921): call_user_func((Array:2), Object(DB_Error))
#3 /home/foo/sites/default/sites/all/modules/civicrm/packages/DB.php(985): PEAR_Error->__construct("DB Error: syntax error", -2, 16, (Array:2), "SELECT id, display_name FROM civicrm_contact WHERE id in () [nativecode=1064 ...")
#4 /home/foo/sites/default/sites/all/modules/civicrm/packages/PEAR.php(575): DB_Error->__construct(-2, 16, (Array:2), "SELECT id, display_name FROM civicrm_contact WHERE id in () [nativecode=1064 ...")
#5 [internal function](): PEAR->_raiseError(Object(DB_mysqli), NULL, -2, NULL, NULL, "SELECT id, display_name FROM civicrm_contact WHERE id in () [nativecode=1064 ...", "DB_Error", TRUE)
#6 /home/foo/sites/default/sites/all/modules/civicrm/packages/PEAR.php(224): call_user_func_array((Array:2), (Array:8))
#7 /home/foo/sites/default/sites/all/modules/civicrm/packages/DB/common.php(1907): PEAR->__call("raiseError", (Array:7))
#8 /home/foo/sites/default/sites/all/modules/civicrm/packages/DB/common.php(1907): PEAR->raiseError(NULL, -2, NULL, NULL, "SELECT id, display_name FROM civicrm_contact WHERE id in () [nativecode=1064 ...", "DB_Error", TRUE)
#9 /home/foo/sites/default/sites/all/modules/civicrm/packages/DB/mysqli.php(933): DB_common->raiseError(-2, NULL, NULL, NULL, "1064 ** You have an error in your SQL syntax; check the manual that correspon...")
#10 /home/foo/sites/default/sites/all/modules/civicrm/packages/DB/mysqli.php(403): DB_mysqli->mysqliRaiseError()
#11 /home/foo/sites/default/sites/all/modules/civicrm/packages/DB/common.php(1216): DB_mysqli->simpleQuery("SELECT id, display_name FROM civicrm_contact WHERE id in ()")
#12 /home/foo/sites/default/sites/all/modules/civicrm/packages/DB/DataObject.php(2415): DB_common->query("SELECT id, display_name FROM civicrm_contact WHERE id in ()")
#13 /home/foo/sites/default/sites/all/modules/civicrm/packages/DB/DataObject.php(1607): DB_DataObject->_query("SELECT id, display_name FROM civicrm_contact WHERE id in ()")
#14 /home/foo/sites/default/sites/all/modules/civicrm/CRM/Core/DAO.php(438): DB_DataObject->query("SELECT id, display_name FROM civicrm_contact WHERE id in ()")
#15 /home/foo/sites/default/sites/all/modules/civicrm/CRM/Core/DAO.php(1413): CRM_Core_DAO->query("SELECT id, display_name FROM civicrm_contact WHERE id in ()", TRUE)
#16 /home/foo/sites/default/sites/all/extensions/org.civicrm.flexmailer-1.0-beta1/src/Listener/ToHeader.php(80): CRM_Core_DAO::executeQuery("SELECT id, display_name FROM civicrm_contact WHERE id in ()")
#17 /home/foo/sites/default/sites/all/extensions/org.civicrm.flexmailer-1.0-beta1/src/Listener/ToHeader.php(44): Civi\FlexMailer\Listener\ToHeader->getContactNames((Array:1))
#18 [internal function](): Civi\FlexMailer\Listener\ToHeader->onCompose(Object(Civi\FlexMailer\Event\ComposeBatchEvent), "civi.flexmailer.compose", Object(Civi\Core\CiviEventDispatcher))
#19 /home/foo/sites/default/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func((Array:2), Object(Civi\FlexMailer\Event\ComposeBatchEvent), "civi.flexmailer.compose", Object(Civi\Core\CiviEventDispatcher))
#20 /home/foo/sites/default/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch((Array:10), "civi.flexmailer.compose", Object(Civi\FlexMailer\Event\ComposeBatchEvent))
#21 /home/foo/sites/default/sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(47): Symfony\Component\EventDispatcher\EventDispatcher->dispatch("civi.flexmailer.compose", Object(Civi\FlexMailer\Event\ComposeBatchEvent))
#22 /home/foo/sites/default/sites/all/extensions/org.civicrm.flexmailer-1.0-beta1/src/FlexMailer.php(238): Civi\Core\CiviEventDispatcher->dispatch("civi.flexmailer.compose", Object(Civi\FlexMailer\Event\ComposeBatchEvent))
#23 /home/foo/sites/default/sites/all/extensions/org.civicrm.flexmailer-1.0-beta1/src/API/MailingPreview.php(57): Civi\FlexMailer\FlexMailer->fireComposeBatch((Array:1))
#24 [internal function](): Civi\FlexMailer\API\MailingPreview::preview((Array:7))
#25 /home/foo/sites/default/sites/all/modules/civicrm/Civi/API/Provider/AdhocProvider.php(131): call_user_func("\Civi\FlexMailer\API\MailingPreview::preview", (Array:7))
#26 /home/foo/sites/default/sites/all/modules/civicrm/Civi/API/Kernel.php(169): Civi\API\Provider\AdhocProvider->invoke((Array:7))
#27 /home/foo/sites/default/sites/all/modules/civicrm/Civi/API/Kernel.php(100): Civi\API\Kernel->runRequest((Array:7))
#28 /home/foo/sites/default/sites/all/modules/civicrm/api/api.php(43): Civi\API\Kernel->runSafe("Mailing", "preview", (Array:2))
#29 /home/foo/sites/default/sites/all/extensions/org.civicrm.flexmailer-1.0-beta1/src/Page/ViewMailing.php(44): civicrm_api3("Mailing", "preview", (Array:1))
#30 /home/foo/sites/default/sites/all/modules/civicrm/CRM/Core/Invoke.php(309): Civi\FlexMailer\Page\ViewMailing->run((Array:3), NULL)
#31 /home/foo/sites/default/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:15))
#32 /home/foo/sites/default/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#33 /home/foo/sites/default/sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:3))
#34 [internal function](): civicrm_invoke("mailing", "view")
#35 /home/foo/sites/default/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#36 /home/foo/sites/default/index.php(21): menu_execute_active_handler()
#37 {main}


Mar 13 09:57:59  [info]
$Fatal Error Details = array(3) {
  ["message"]=>
  string(22) "DB Error: syntax error"
  ["code"]=>
  NULL
  ["exception"]=>
  object(CiviCRM_API3_Exception)#198 (8) {
    ["extraParams":"CiviCRM_API3_Exception":private]=>
    array(4) {
      ["error_code"]=>
      string(12) "syntax error"
      ["tip"]=>
      string(62) "add debug=1 to your API call to have more info about the error"
      ["is_error"]=>
      int(1)
      ["error_message"]=>
      string(22) "DB Error: syntax error"
    }
    ["message":protected]=>
    string(22) "DB Error: syntax error"
    ["string":"Exception":private]=>
    string(0) ""
    ["code":protected]=>
    int(0)
    ["file":protected]=>
  string(62) "/home/foo/sites/default/sites/all/modules/civicrm/api/api.php"
    ["line":protected]=>
    int(45)
    ["trace":"Exception":private]=>
    array(8) {
      [0]=>
      array(4) {
        ["file"]=>
        string(103) "/home/foo/sites/default/sites/all/extensions/org.civicrm.flexmailer-1.0-beta1/src/Page/ViewMailing.php"
        ["line"]=>
        int(44)
        ["function"]=>
        string(12) "civicrm_api3"
        ["args"]=>
        array(3) {
          [0]=>
          &string(7) "Mailing"
          [1]=>
          &string(7) "preview"
          [2]=>
          &array(1) {
            ["id"]=>
            string(3) "784"
          }
        }
      }
      [1]=>
      array(6) {
        ["file"]=>
        string(70) "/home/foo/sites/default/sites/all/modules/civicrm/CRM/Core/Invoke.php"
        ["line"]=>
        int(309)
        ["function"]=>
        string(3) "run"
        ["class"]=>
        string(32) "Civi\FlexMailer\Page\ViewMailing"
        ["type"]=>
        string(2) "->"
        ["args"]=>
        array(2) {
          [0]=>
          &array(3) {
            [0]=>
            string(7) "civicrm"
            [1]=>
            string(7) "mailing"
            [2]=>
            string(4) "view"
          }
          [1]=>
          &NULL
        }
      }
      [2]=>
      array(6) {
        ["file"]=>
        string(70) "/home/foo/sites/default/sites/all/modules/civicrm/CRM/Core/Invoke.php"
        ["line"]=>
        int(84)
        ["function"]=>
        string(7) "runItem"
        ["class"]=>
        string(15) "CRM_Core_Invoke"
        ["type"]=>
        string(2) "::"
        ["args"]=>
        array(1) {
          [0]=>
          &array(15) {
            ["id"]=>
            string(3) "376"
            ["domain_id"]=>
            string(1) "1"
            ["path"]=>
            string(20) "civicrm/mailing/view"
            ["title"]=>
            string(12) "View Mailing"
            ["access_callback"]=>
            array(2) {
             [0]=>
              string(19) "CRM_Core_Permission"
              [1]=>
              string(9) "checkMenu"
            }
            ["access_arguments"]=>
            array(2) {
              [0]=>
              array(3) {
                [0]=>
                string(28) "view public CiviMail content"
                [1]=>
                string(15) "access CiviMail"
                [2]=>
                string(16) "approve mailings"
              }
              [1]=>
              string(2) "or"
            }
            ["page_callback"]=>
            string(33) "\Civi\FlexMailer\Page\ViewMailing"
            ["breadcrumb"]=>
            array(2) {
              [0]=>
              array(2) {
                ["title"]=>
                string(7) "CiviCRM"
                ["url"]=>
                string(16) "/civicrm?reset=1"
              }
              [1]=>
              array(2) {
                ["title"]=>
                string(8) "CiviMail"
                ["url"]=>
                string(24) "/civicrm/mailing?reset=1"
              }
            }
            ["component_id"]=>
            string(1) "4"
            ["is_public"]=>
            string(1) "1"
            ["is_ssl"]=>
            string(1) "0"
            ["weight"]=>
            string(3) "800"
            ["type"]=>
            string(1) "1"
            ["page_type"]=>
            string(1) "0"
            ["page_arguments"]=>
            bool(false)
          }
        }
      }
      [3]=>
      array(6) {
        ["file"]=>
        string(70) "/home/foo/sites/default/sites/all/modules/civicrm/CRM/Core/Invoke.php"
        ["line"]=>
        int(52)
        ["function"]=>
        string(7) "_invoke"
        ["class"]=>
        string(15) "CRM_Core_Invoke"
        ["type"]=>
        string(2) "::"
        ["args"]=>
        array(1) {
          [0]=>
          &array(3) {
            [0]=>
            string(7) "civicrm"
            [1]=>
            string(7) "mailing"
            [2]=>
            string(4) "view"
          }
        }
      }
      [4]=>
      array(6) {
        ["file"]=>
        string(72) "/home/foo/sites/default/sites/all/modules/civicrm/drupal/civicrm.module"
        ["line"]=>
        int(445)
        ["function"]=>
        string(6) "invoke"
        ["class"]=>
        string(15) "CRM_Core_Invoke"
        ["type"]=>
        string(2) "::"
        ["args"]=>
        array(1) {
          [0]=>
          &array(3) {
            [0]=>
            string(7) "civicrm"
            [1]=>
            string(7) "mailing"
            [2]=>
            string(4) "view"
          }
        }
      }
      [5]=>
      array(2) {
        ["function"]=>
        string(14) "civicrm_invoke"
        ["args"]=>
        array(2) {
          [0]=>
          &string(7) "mailing"
          [1]=>
          &string(4) "view"
        }
      }
      [6]=>
      array(4) {
        ["file"]=>
        string(42) "/home/foo/sites/default/includes/menu.inc"
        ["line"]=>
        int(527)
        ["function"]=>
        string(20) "call_user_func_array"
        ["args"]=>
        array(2) {
          [0]=>
          &string(14) "civicrm_invoke"
          [1]=>
          &array(2) {
            [0]=>
            string(7) "mailing"
            [1]=>
            string(4) "view"
          }
        }
      }
      [7]=>
      array(4) {
        ["file"]=>
        string(34) "/home/foo/sites/default/index.php"
        ["line"]=>
        int(21)
        ["function"]=>
        string(27) "menu_execute_active_handler"
        ["args"]=>
        array(0) {
        }
      }
    }
    ["previous":"Exception":private]=>
    NULL
  }
}


Mar 13 09:57:59  [info] $backTrace = #0 /home/foo/sites/default/sites/all/modules/civicrm/CRM/Core/Error.php(459): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /home/foo/sites/default/sites/all/modules/civicrm/CRM/Core/Invoke.php(55): CRM_Core_Error::handleUnhandledException(Object(CiviCRM_API3_Exception))
#2 /home/foo/sites/default/sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:3))
#3 [internal function](): civicrm_invoke("mailing", "view")
#4 /home/foo/sites/default/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#5 /home/foo/sites/default/index.php(21): menu_execute_active_handler()
#6 {main}`

**Comment by MegaphoneJon** [comment]
I'm pretty sure this is a Flexmailer issue, not a Mosaico issue - partly from the backtrace, partly because I had what I'm pretty sure was the same error yesterday on a non-Mosaico site.

**Comment by mattwire** [comment]
Can you test with flexmailer 1.0.beta2?

**Comment by mattwire** [comment]
Closing following 2.6 release. Please reopen if still an issue
