### ISSUE TITLE
HTML <title> tag is 'TITLE' when mailing is viewed in browser 

### ISSUE THREAD

**Issue by roblog** [veda-consulting/uk.co.vedaconsulting.mosaico#245]
The HTML <title> tag reads 'TITLE' when mailing is viewed in browser mode, for example: 
https://annaforredcar.org.uk/civicrm/mailing/view?reset=1&id=104 

UPDATE: after a bit more probing I've deduced that the template used for the mailing in the above link, is a new template based on versafix-1. I was ale to locate the new template in the database, and manually edit the <title> tag, so it is sort of fixed.

The <title> tag works fine for new mailings using the versafix-1 template, so it seems that there is a problem at the point where the new template is created, and it is stored on the database, with the <title> tag set as 'TITLE'. Hope that helps a little ..

**Comment by mattwire** [comment]
Closing following 2.6 release. Please reopen if still an issue
