### ISSUE TITLE
Feature Request - Append beginning of subject with [TEST] when sending test emails.

### ISSUE THREAD

**Issue by themak1985** [veda-consulting/uk.co.vedaconsulting.mosaico#247]
I have stopped sending test emails to other members of our board via civi - simply because they all freak out when they get the email - thinking its final - etc. This takes place even when i tell them to expect a draft/test email message. Currently i send it to myself and then forward with a note that this is a draft.

This is super low on the priority list, but would it be possible to append the beginning of the email subject of test emails with something like [TEST]?  If we want to get even more complicated - maybe a slot to append a message to the top of the email for recipients of the test email to read.

We have completely switched from MailChimp to Mosaico/CiviMail, but the aforementioned features are two that I miss. Thanks everyone for your great work on this!

**Comment by samuelsov** [comment]
Just a quick support of this issue. Some of the users i support are in need of this feature.
In CiviMail, the string `ts('[CiviMail Draft]')` is append to the subject. We could keep the same.

But i believe it could be a core CiviCRM issue as Mosaico is calling a function sendTest from Core.
I will propose a patch to core first and close this one if it's accepted.

**Comment by samuelsov** [comment]
I guess we can close this because the Core Pull Request has been merged.

**Comment by totten** [comment]
Yup, agree, this is fixed elsewhere.

We've done some more juggling on this issue:
* Short version: I'd recommend upgrading to Flexmailer v1.0-beta1+ (with https://github.com/civicrm/org.civicrm.flexmailer/pull/28).
* Long version: See the table in https://github.com/civicrm/civicrm-core/pull/12758#issuecomment-446843869
