### ISSUE TITLE
Selecting a template from the first screen tries to print it

### ISSUE THREAD

**Issue by rocxa** [veda-consulting/uk.co.vedaconsulting.mosaico#25]
The links are in this format:  /civicrm/mosaico/editor?snippet=2#twjeqag

I have a feling the ?snippet=2 means print this page? as every time I select a template the printer dialog box of my web browser opens.

**Comment by rocxa** [comment]
This also happens when opening a previously saved template for editing.
http://******************/civicrm/mosaico/editor?snippet=2#twjeqag

**Comment by deepak-srivastava** [comment]
Yeah we are aware of it. We ended up using it as only option where there is least amount of JS and theme interference, plus we get full screen. 

Think we 'll have to come up with new snippet similar to 2 but not print.

**Comment by rocxa** [comment]
Adding an if statement to CRM/common/print.tpl is a quick fix to this problem.

`{crmRegion name='page-footer' allowCmsOverride=0}
{if strpos($tplFile, 'Mosaico') == false}
  <script type="text/javascript">
    window.print();
  </script>
{/if}
{/crmRegion}`

**Comment by rocxa** [comment]
I tried creating another snippet which was a copy of print.tpl (e.g. noprint.tpl) without the window.print() but the copied print.tpl seemed to load up all of Civi's css/js and interfered with Mosacio's user interface so it was easier just to patch print.tpl instead.

**Comment by deepak-srivastava** [comment]
@rocxa thanks for investigating. Any ideas how to do it without touching civi core file, like doing something within the extension that would achieve the same? May be overriding JS or tpl in worst case?

**Comment by rocxa** [comment]
Adding this to the Mosaico page templates (before the print.tpl is loaded)  would stop the printing action:

  window.print = function () {
    return false;
  }

**Comment by mark-rodgers** [comment]
This was resolved in PR #31

**Comment by deepak-srivastava** [comment]
Thanks @rocxa
