### ISSUE TITLE
TinyMCE editor plugin settings

### ISSUE THREAD

**Issue by sunilpawar** [veda-consulting/uk.co.vedaconsulting.mosaico#251]
Allow admin to add/remove tinymce editor plugin.

domain-name/civicrm/admin/mosaico?reset=1
<img width="721" alt="mosoico_admin" src="https://user-images.githubusercontent.com/377735/39509152-c4c785a4-4e02-11e8-994f-9dbfb2363d6c.png">

**Comment by sunilpawar** [comment]
#250

**Comment by homotechsual** [comment]
We've taken a different approach to this by changing the defaults to those used on the mosaico demo.

**Comment by mattwire** [comment]
Closing following 2.6 release. Please reopen if still an issue
