### ISSUE TITLE
Mosaico versafix-1 Template not loading / Edit 

### ISSUE THREAD

**Issue by Rar9** [veda-consulting/uk.co.vedaconsulting.mosaico#254]
When I click onto the versafix-1 from NEW base Template, the template starts loading, but I only get a grey screen.

It will appear also in Configured templates: but when pressing edit i get the same grey screen.

The other 2 templates seam to load fine.

**Comment by Rar9** [comment]
any update only see a grey background when trying to use this versafix template

**Comment by MegaphoneJon** [comment]
@rar9 Could you check your JavaScript console for errors?  I was experiencing the same thing today and I saw this:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://<mysite>/sites/all/civicrm-custom/extensions/uk.co.vedaconsulting.mosaico/packages/mosaico/templates/versafix-1/template-versafix-1.html. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

I know this site has some CORS customizations, maybe yours does too?

**Comment by Rar9** [comment]
If u tell how/where to check

**Comment by MegaphoneJon** [comment]
@rar9 See this: https://sevenspark.com/docs/how-to-check-javascript-errors

**Comment by Rar9** [comment]
i get 22 error
![Screenshot_1](https://user-images.githubusercontent.com/2239608/59637951-5540c080-9157-11e9-85ec-accae05a4d6d.png)

**Comment by mattwire** [comment]
Closing following 2.6 release. Please reopen if still an issue
