### ISSUE TITLE
Spell Checker in Mosaico

### ISSUE THREAD

**Issue by kngs** [veda-consulting/uk.co.vedaconsulting.mosaico#259]
I have yet to get the EXPERIMENTAL Mosaico Message Templates extension to work to allow spell checking on Mosaico templates (and am also concerned about it's use by the average user as noted in the extension).  Is there any plan and/or timing on getting spell checking directly available in Mosaico?
Thanks - love Mosaico!!

**Comment by pbatroff** [comment]
This extension could help you out: https://github.com/ginkgostreet/com.ginkgostreet.mosaicotoolbarconfig/blob/master/mosaicotoolbarconfig.php

This is what I did to add browser spellcheck to TinyMCE: 

https://github.com/systopia/com.ginkgostreet.mosaicotoolbarconfig/commit/23695d53f9bec8bf86dad09b621a11c8c9eab06f

Good luck!

**Comment by mattwire** [comment]
Fixed in next release after 2.3
