### ISSUE TITLE
Uploading an image shows then breaks with error

### ISSUE THREAD

**Issue by rocxa** [veda-consulting/uk.co.vedaconsulting.mosaico#26]
Images show briefly and then error:
no decode delegate for this image format `/tmp/magick-ab1Slan2' @ error/constitute.c/ReadImage/566

Answer, imagemagick install is probably duff..
http://stackoverflow.com/questions/30005612/imagemagick-no-decode-delegate-for-this-image-format

Although for me imagemajick shows all the necessary delegates and phpinfo shows all the supported formats and I still get the error :-(

Great (much needed) extension to CiviMail btw :-)

**Comment by deepak-srivastava** [comment]
@rocxa Not sure we can help, but we can try setup one wamp install and see how it goes.

**Comment by rocxa** [comment]
I have confirmed that imagemagick is working fine via php (creating thumbnails etc) on my server but seems to break when used via Mosaico.  It is probably going to be something silly like Mosaico looking in the wrong place/or using the wrong folders for images.

**Comment by deepak-srivastava** [comment]
Does runcheck=1 detects anything (make sure to use latest release)? 

If you can identify what path/url appears wrong to you, i can probably suggest where to correct. Its mostly config vars.

**Comment by rocxa** [comment]
I have discovered the problem is caused by empty index.html files that are added to all directories on our server to (i think) stop directory listings?!

the Utils.php file in the Mosaico extension doesn't look specifically for image files so get caught out by these html files (and probably any other type of file) in the image directories and tries to convert them to images.

**Comment by deepak-srivastava** [comment]
@rocxa thanks for your PR.

re: index.html - may be its worth adding checks for such files when runcheck=1 in the url? I remember being hit by it.

**Comment by deepak-srivastava** [comment]
Closing this ticket now. Please re-open if any issues. Thanks.
