### ISSUE TITLE
Mosiac Default css is hidding all the templates from the page view.

### ISSUE THREAD

**Issue by swastikpareek** [veda-consulting/uk.co.vedaconsulting.mosaico#260]
After setting up fresh drupal 7 v 59 and enabling civicrm theme with dummy data. If I enable Mosiaco and try to see all the available templates, The page doesn't showing the whole content and hides templates -
Please refer the screenshot.
<img width="1379" alt="screen shot 2018-06-13 at 5 39 47 pm" src="https://user-images.githubusercontent.com/3340537/41350753-c262b0e0-6f31-11e8-8b2f-b2a3fe44e899.png">
This happen because in `packages/mosaico/src/css/style_mosaico.less` file : 232 . following css is written which seems unnecessary. - 
<img width="342" alt="screen shot 2018-06-13 at 5 50 45 pm" src="https://user-images.githubusercontent.com/3340537/41350919-53fad4c4-6f32-11e8-9f9b-aa8ce04eb200.png">

**Comment by mattwire** [comment]
Closing following 2.6 release. Please reopen if still an issue
