### ISSUE TITLE
angular.js error: Module 'crmMosaico' is not available

### ISSUE THREAD

**Issue by StijnVanhandsaeme** [veda-consulting/uk.co.vedaconsulting.mosaico#261]
When I enable  Mosaico extension I get an error on the status page as well as on the new mailing page:

`Error: [$injector:modulerr] Failed to instantiate module crmApp due to:
[$injector:modulerr] Failed to instantiate module crmMosaico due to:
[$injector:nomod] Module 'crmMosaico' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.11/$injector/nomod?p0=crmMosaico
minErr/<@http://localhost/sites/all/modules/civicrm/bower_components/angular/angular.js?pa9jmk:68:12
module/<@http://localhost/sites/all/modules/civicrm/bower_components/angular/angular.js?pa9jmk:2133:17
ensure@http://localhost/sites/all/modules/civicrm/bower_components/angular/angular.js?pa9jmk:2057:38
module@http://localhost/sites/all/modules/civicrm/bower_components/angular/angular.js?pa9jmk:2131:14
loadModules/<@http://localhost/sites/all/modules/civicrm/bower_components/angular/angular.js?pa9jmk:4669:22
forEach@http://localhost/sites/all/modules/civicrm/`

Using civicrm 5.2.1 in drupal 7.59 and mosaico 2.0-beta4.1528762072 

Let me know if I can provide more info thelp solving this issue or things to try. 
Thank you.

**Comment by mattwire** [comment]
Closing following 2.6 release. Please reopen if still an issue
