### ISSUE TITLE
Mailings not sending

### ISSUE THREAD

**Issue by Dietermartens** [veda-consulting/uk.co.vedaconsulting.mosaico#262]
We've updated our CiviCRM to version 5.2.2 and Mosaico to version 2.0 beta 4 and since then we are not able to send any mailing from CiviCRM. To be clear we can mail to a person individually. Because we are hosting our website on a VPS I was able to check the logs on the outgoing emails. I noticed that emails (to one person) are going out correctly, but when I try to send a mailing I get something like this "The sender address <b.2987.15354.3059f5f6f547a2d6@> is not a valid 553 5.1.2 RFC-5321 address."

I'm hosting on a Plesk server 17.5.2 with PHP 7.1.

**Comment by MegaphoneJon** [comment]
I think the best venue for this is Stack Exchange (https://civicrm.stackexchange.com).  Could you please create a question and include a screenshot of your bounce processing email settings?  They're at **Administer menu » CiviMail » Mail Accounts**, and press **Edit** next to your bounce processing account.

**Comment by Dietermartens** [comment]
Jul  3 20:37:09 srv1 postfix/cleanup[5738]: 127618DFC48: message-id=<20180703183709.127618DFC48@srv1.domain.tld>
Jul  3 20:37:09 srv1 postfix/qmgr[2653]: 127618DFC48: from=<>, size=2893, nrcpt=1 (queue active)
Jul  3 20:37:09 srv1 postfix/bounce[5752]: DE494877FA9: sender non-delivery notification: 127618DFC48
Jul  3 20:37:09 srv1 postfix/qmgr[2653]: DE494877FA9: removed
Jul  3 20:37:09 srv1 postfix/error[5753]: 127618DFC48: to=<b.2991.15358.54e38646f6197eee@>, relay=none, delay=0.02, delays=0.01/0.01/0/0, dsn=5.1.3, status=bounced (bad address syntax)
