### ISSUE TITLE
Greeting Tokens not placed

### ISSUE THREAD

**Issue by edurrr** [veda-consulting/uk.co.vedaconsulting.mosaico#266]
Hello,

When i create a new Mailing with Mosaico, neither the preview nor the final email populate the tokens {contact.email_greeting} correctly (postal greeting doesn't work either).

Here the test template i used:

![template](https://user-images.githubusercontent.com/41587594/43090404-88288748-8ea7-11e8-8ade-bb5514859c25.png)

There is no text placed for the token (here the preview, the E-Mail that is sent is identical - in test and real mode):
![preview_and_mail_version](https://user-images.githubusercontent.com/41587594/43090459-ae57d996-8ea7-11e8-9f4a-371d6307c0b0.png)

The problem both occurs in the plain-text and the HTML Version.

Interestingly, in the "View in Browser"-Version, the token works fine:
![browser_version](https://user-images.githubusercontent.com/41587594/43090473-ba1c949c-8ea7-11e8-9401-c4916a62d3cd.png)

The greeting token also works fine when creating a legacy Mailing without using mosaico.

Other tokens (unsubscribe Link, etc.) are unaffected.

Versions:
PHP: PHP 7.0.30-0ubuntu0.16.04.1
Mysql 14.14
Drupal: 7.59
CiviCRM: 5.3.1
Mosaico: 2.0-beta4.1528762072
Shoreditch: 0.1-alpha20
Flexmailer: 0.2-alpha5

**Comment by DavidHepper** [comment]
Yes, I second this.
CiviCRM 5.3.1 on Wordpress
Mosaico: 2.0-beta4.1528762072

**Comment by jusfreeman** [comment]
Just chiming in that we've seen this bug too.

**Comment by jusfreeman** [comment]
We will submit a PR for this one, feel free to beat us to it :)

**Comment by michael-chaplin-gmcvo** [comment]
I can confirm all these tokens are broken when I send a test email from within the Mosaico editor:

{contact.email_greeting}
{contact.email_greeting_id}
{contact.postal_greeting_id}
{contact.postal_greeting}

Is there a patch or release that fixes this?

We currently have version 2.0.1556289017

**Comment by jusfreeman** [comment]
@mikantchap when we tested this using these versions, it was working - so no PR required from us.

Have you tried testing with these versions? The bug may have come back.

CiviCRM - 5.11.0
Mosaico - 2.0-beta4
FlexMailer - 1.0-beta1
Shoreditch - 0.1-alpha30

**Comment by michael-chaplin-gmcvo** [comment]
Using

CiviCRM 5.13.4
Mosaico 2.0 (Shoreditch not required)
Flexmailer 1.0-beta2
PHP version 7.1.29


I can confirm all these tokens are broken when I send a test email from within the Mosaico editor:

{contact.email_greeting}
{contact.email_greeting_id}
{contact.postal_greeting_id}
{contact.postal_greeting}

**Comment by jusfreeman** [comment]
Thanks @mikantchap 

I'll add {contact.addressee} to that list of tokens that do not work.

Agileware Ref: CIVIMOSAIC-12

**Comment by jusfreeman** [comment]
Particularly problematic if you are using these tokens to email both Individual and Organisation contacts. There's no way to address both types of contacts using a single token.

**Comment by mattwire** [comment]
Can you upgrade to mosaico 2.1 and flexmailer 1.1 and confirm if the problem still exists?

**Comment by michael-chaplin-gmcvo** [comment]
Using

CiviCRM 5.13.4
Mosaico 2.1.1559427853
Flexmailer 1.1.0
PHP version 7.1.29

I can confirm all these tokens are broken when I send a test email from within the Mosaico editor:

{contact.email_greeting}
{contact.email_greeting_id}
{contact.postal_greeting_id}
{contact.postal_greeting}

Are you struggling to reproduce the error?

**Comment by mattwire** [comment]
> Are you struggling to reproduce the error?

Just wanted to be clear that it was still an issue now we've got official releases.  It's something you'll probably want @totten to take a look at but he may need funding do do that.
