### ISSUE TITLE
Feature Request: Change template image

### ISSUE THREAD

**Issue by jorich-2000** [veda-consulting/uk.co.vedaconsulting.mosaico#267]
When creating a new template from the existing ones (eg versafix) it would really hep to be able to change the default image displayed with the template.
Also ability to hide default empty template so users have to use the modified one

**Comment by totten** [comment]
I agree this would be good. It feels a bit silly browsing through a thumbnail gallery when all the thumbnails are identical. With a large list of templates, the gallery feels almost unusuable. (A plaintext list or autocomplete would arguably be more usable than a gallery of identical thumbnails...)

In the past, the main hurdle has been a technical consideration -- auto-generating a thumbnail based on the user's actual template requires a fairly deep stack (e.g. *Install a web-browser on the web-server or setup a connection to some pool of scriptable web-browsers*), and it'd be hard to coordinate that in Civi's distribution channel.

The way you report it is thought provoking. *Any* process which changes the template's thumbnail would be an improvement. For example, these would be improvements over the status quo:

* Allow admins to upload a custom thumbnail.
* Assign each instance of a template an arbitrary color, and convert the standard thumbnail to that color.
* Add a random icon in the corner of the thumbnail (eg colored dots... animal emojis... or anything visually differentiably).

Of course, it would still be ideal to generate real/live thumbnails. I'm not sure there's a business-model where one can run that for free on the web, but maybe it

**Comment by DavidHepper** [comment]
I support allowing admins to upload a custom thumbnail. You can be picky about the size allowed, to keep them small.

**Comment by jorich-2000** [comment]
Is there any progress on this? - there really is no point to a thumbnail gallery where all the images are the same
A simple solution of allowing an image to be uploaded to the template would suffice
