### ISSUE TITLE
XML file is missing the downloadUrl

### ISSUE THREAD

**Issue by michaelmcandrew** [veda-consulting/uk.co.vedaconsulting.mosaico#269]
When trying to install referencing the xml file, I get the following error:

```
buildkit@scout:/var/www/gpie$ cv ext:download @https://civicrm.org/sites/civicrm.org/files/extensions/uk.co_.vedaconsulting.mosaico-2.0-beta4.1528762072-info.xml
Using extension feed "https://civicrm.org/extdir/ver=5.3.1|uf=Drupal|status=stable|ready=ready"
Extension cache does not contain requested item(s)
Refreshing extension cache
The specified XML file is missing the key and/or downloadUrl (@https://civicrm.org/sites/civicrm.org/files/extensions/uk.co_.vedaconsulting.mosaico-2.0-beta4.1528762072-info.xml).
Tip: To customize the feed, review options in "cv ext:download --help"
Tip: To browse available downloads, run "cv ext:list -R"
```

I'm guessing that is because your XML file is missing the downloadUrl.

Easy to get around it if you can specify the download link but I thought you might like to know.

**Comment by mattwire** [comment]
Hey @michaelmcandrew fancy adding a PR for this?

**Comment by michaelmcandrew** [comment]
at some point yes. today, no :)

**Comment by totten** [comment]
@michaelmcandrew  Aah, the law of unintended consequences. :)

In `civicrm.org`'s dataflow, the raw `info.xml` files under `sites/civicrm.org/files` generally don't have a `downloadUrl` . This is true of many (if not all) extensions.

Requests usually come through a page controller (e.g. `https://civicrm.org/extdir/ver=5.8.alpha1|uf=Drupal|status=|ready=/uk.co.vedaconsulting.mosaico.xml`) which loads the raw file and injects `downloadUrl`. (It might do some other cleanup, but I'm not certain about that.) It's entirely accidental (IMHO) that one can download the raw `info.xml` from `c.o`.

If you go through the page controller, that should work:

```
cv ext:download '@https://civicrm.org/extdir/ver=5.8.alpha1|uf=Drupal|status=|ready=/uk.co.vedaconsulting.mosaico.xml'
```

But maybe the idea here is to pin to a specific version?

* If I were you, I'd just use the `<key>@<zip-url>` notation for pinning. 
* If the idea is to have an idiom that generally works for downloading a specific version, then I'd suggest adding a route or two for that purpose:
    * `https://civicrm.org/extinfo/KEY/VERSION.xml` ==> `https://civicrm.org/extinfo/uk.co.vedaconsulting.mosaico/2.0-beta4.xml` ==> Return the normalized XML
    * `https://civicrm.org/extinfo/KEY/VERSION.zip` ==> `https://civicrm.org/extinfo/uk.co.vedaconsulting.mosaico/2.0-beta4.zip` => Redirect to the actual download URL
