### ISSUE TITLE
thumbnails missing for uploaded images

### ISSUE THREAD

**Issue by thomst** [veda-consulting/uk.co.vedaconsulting.mosaico#27]
When uploading an image into the gallery the thumbnails are not created/shown.

**Comment by thomst** [comment]
All that was needed to fix this on my system was to create the following folder:
sites/default/files/civicrm/persist/contribute/uploads/thumbnails

**Comment by deepak-srivastava** [comment]
I haven't been able to understand this solution. May be someone could explain.

My understanding is it doesn't need thumbnail directory. It creates an image of size thumbnail on the fly, using ImageMagick.

**Comment by rocxa** [comment]
We had to manually create the uploads/static and uploads/thumbnails directories as well to get images to upload and resize.  Otherwise they would just 'appear' to work while in Mosaico but wouldn't be saved and loaded again when you used a saved template from CiviCRM.

**Comment by deepak-srivastava** [comment]
It does try to create static dir on installation - https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/master/mosaico.php#L40. Might want to check why that didn't work.
Probably we should add a check for its existence anyway.

W.r.t thumbnail - we 'll try track down where its using it and/or add a check.

**Comment by deepak-srivastava** [comment]
Closing this ticket. Re-open if any issues. Thanks.
