### ISSUE TITLE
Building a New Template

### ISSUE THREAD

**Issue by stevekessler** [veda-consulting/uk.co.vedaconsulting.mosaico#275]
Hi, 

Is there a step by step set of instructions for making a new template for Mosaico in the CiviCRM structure?  I am trying to piece together the instructions I have found and I am just not getting it right. 

Thanks,
Steve

**Comment by wflanagan** [comment]
@stevekessler did you sort it out?

**Comment by stevekessler** [comment]
@wflanagan, sorry I did not see your response until now. I can get the theme to be seen but I cannot add blocks for the life of me.

**Comment by Rar9** [comment]
+1 Yes some guide would be appreciated for creating a new mailing block template

**Comment by JKingsnorth** [comment]
The best way of learning is to look at the example templates provided by mosaico: versafix and the ted one.

There's also some information here:

- https://github.com/voidlabs/mosaico/wiki/Template-language
- https://github.com/voidlabs/mosaico/blob/master/templates/tutorial/mosaico-tutorial.md
