### ISSUE TITLE
Templates do not load in New Mailing (Traditional) 

### ISSUE THREAD

**Issue by John-B** [veda-consulting/uk.co.vedaconsulting.mosaico#278]
after installing Mosaico, calling MessageTemplate get in the API explorer returns and empty array; and the dropdown for selecting a Message Template which appears when visiting CiviCRM > Mailings > New Mailing (Traiditiona) is not populated.

After installing Mosaico a schema class is added by the extension's schema  to civicrm/CRM/Core/DAO/AllCoreTables.data.php for the table civicrm_msg_template. Its name is MessageTemplate. This has the same name as the class defined in  civicrm-core/xml/schema/Core/MessageTemplate.xml 
For reasons I do not understand this clash of naming creates a problem, and I have discovered that manually hacking civicrm/CRM/Core/DAO/AllCoreTables.data.php to change 
`  'CRM_Mosaico_DAO_MessageTemplate' => [
    'name' => 'MessageTemplate',
    'class' => 'CRM_Mosaico_DAO_MessageTemplate',
    'table' => 'civicrm_mosaico_msg_template',
  ],
`
to 
`  'CRM_Mosaico_DAO_MessageTemplate' => [
    'name' => 'MosaicoMessageTemplate',
    'class' => 'CRM_Mosaico_DAO_MessageTemplate',
    'table' => 'civicrm_mosaico_msg_template',
  ],
`
to remove the name clash with the core MessagesTemplate fixes the problem.

**Comment by bazzspeed** [comment]
This does not appear to be an issue with my setup, can you please retest and also comment on what versions you're using.

_My setup:_
    
    CiviCRM: 5.11 and all extensions are up-to-date:
    Related Permissions Module (nz.co.fuzion.relatedpermissions) version 1.6
    FlexMailer (org.civicrm.flexmailer) version 1.0-beta1
    CiviCRM Multisite (org.civicrm.multisite) version 2.6
    CiviCRM Bootstrap theme (org.civicrm.shoreditch) version 0.1-alpha30
    Mosaico (uk.co.vedaconsulting.mosaico) version 2.0-beta4.1544700816

**Comment by MegaphoneJon** [comment]
Same as @bazzspeed here - same version of Civi, all extensions up to date, running the master branch of Mosaico.

@John-B has this issue been fixed?  If so we can close this.

**Comment by John-B** [comment]
This is OK now. Using Mosaico version from https://civicrm.org/extensions/mosaico-civicrm-integration/version-20-beta4 on CiviCRM 5.10.3, which I think is the same version of Mosaico that gave a problem previously, though a higher version of Civi and of PHP.
