### ISSUE TITLE
use of image with same name does not overwrite

### ISSUE THREAD

**Issue by shawnholt** [veda-consulting/uk.co.vedaconsulting.mosaico#28]
I found that if I use a new image with the same name in another place, it will not overwrite or create a new name - just uses the old one.  note it looks fine in drag/drop but when I download i see the old image.  Using unique names for all images solves the problem.

**Comment by deepak-srivastava** [comment]
Hmm, we can probably append a hash to uploaded file, like the way civi does for file uploads.

Would you like to PR that fix?

**Comment by deepak-srivastava** [comment]
Fixed with PR - https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/pull/37
