### ISSUE TITLE
WordPress issues with bootstrap theme

### ISSUE THREAD

**Issue by yorkshirerose** [veda-consulting/uk.co.vedaconsulting.mosaico#284]
Have a recent install of WordPress v4.9.8 + CiviCRM 5.7.2 (with the new version of CiviCRM Admin Utilities v0.6.2) and tried to install Mosaico. Couldn't get the templates to display and the layout is all on one page instead of neatly split into three.

Finally managed to get it up and running by disabling Shoreditch and using a different theme on WordPress (Scaffold Version: 1.2.2) but the layout is still wrong (although it does work so it's less urgent!)

<img width="960" alt="untitled" src="https://user-images.githubusercontent.com/43925307/50052302-bc82a700-0119-11e9-96f8-1d5180326775.png">

**Comment by christianwach** [comment]
@yorkshirerose A few thoughts:

* Have you cleared CiviCRM's caches? Easily done by checking the box in CiviCRM Admin Utilities settings page and hitting Save Changes. 
* Have you also force-refreshed your browser?
* Have you switched to one of the WordPress default themes?

FWIW, this what I see on a test install of WordPress 4.9.9 + CiviCRM Admin Utilities 0.6.2 (with admin theme enabled) + TwentySeventeen theme + CiviCRM 5.7.2 + Mosaico 2.0-beta4.1528762072:

<img width="1440" alt="screen shot 2018-12-16 at 11 23 43" src="https://user-images.githubusercontent.com/726936/50053016-8c410580-0125-11e9-9ec6-6ed5c2e58d62.png">

If the only difference is the theme, perhaps check what resources they are loading and if they're doing so in `wp-admin`? I've seen themes offer back-end options pages but load their resources everywhere. You should be able to dequeue their assets on CiviCRM pages if they're blanket-loading CSS or JS files.

**Comment by mattwire** [comment]
Shoreditch doesn't support wordpress.  But Mosaico works well without shoreditch installed so I'm going to close this.
