### ISSUE TITLE
JSON error on image upload

### ISSUE THREAD

**Issue by alexmarketaccess** [veda-consulting/uk.co.vedaconsulting.mosaico#287]
My setup is 
Mosaico 1.1 (2018-05-18)
CiviCRM 5.9.0
Joomla! 3.9.1
PHP 7.1

When I try to upload an image, it looks like the image uploads, but then I get the message:

Unexpected upload error (SyntaxError: JSON:parse: unexpected character at line 1 column 1 of the JSON data) 

and then the block containing the image refreshes and the image is not shown.

I checked directory structure, and I have:

public_html/media/civicrm/persist/contribute
public_html/media/civicrm/persist/contribute/images
public_html/media/civicrm/persist/contribute/uploads/thumbnails

and in fact, I see the images have successfully been uploaded to 
public_html/media/civicrm/persist/contribute/
public_html/media/civicrm/persist/contribute/uploads/thumbnails

But as you can see in short movie below, the images won't appear in the template:

https://drive.google.com/file/d/1oSoW0gLksenoiGS7daSzlJjUb3pvyLw3/view?usp=drivesdk

Any ideas what is wrong and how to resolve?

**Comment by deepak-srivastava** [comment]
Have you considered upgrading? Looking at the civicrm and php version, mosaico 2.x sounds better fit. Although i'm not sure of it's state on joomla, is worth a try. 
Note: 1.x is no longer officially supported and upgrading might take less time than debugging the problem.

If you still want to put effort in debugging and finding the cause/fix, might want to check browser console and see the ajax response which is causing the error. And that might give more clues.

**Comment by mattwire** [comment]
Please update to 2.0  1.x is no longer supported

**Comment by yorkshirerose** [comment]
I realise this is a closed issue but I'm getting the same error message on a site running:
CiviCRM 5.24.6
Mosaico 2.3.1572289217 
PHP 7.2.30

Nothing in the CiviCRM logs or the Drupal 'Recent Logs Report' to give an indication what's causing it.

Any ideas?
