### ISSUE TITLE
mixed content messages on versafix placeholder images

### ISSUE THREAD

**Issue by jmcclelland** [veda-consulting/uk.co.vedaconsulting.mosaico#288]
When editing a template based on versafix, I get mixed-content warnings from my browser.

It seems that the version of mosaico that is shipping with this extension includes a version of the versaifx template that includes the place holder images using http://mosaico.io instead of https://mosaico.io.

See https://github.com/voidlabs/mosaico/blob/master/templates/versafix-1/template-versafix-1.html

In fact, the templates seem to have a lot of differences and the version of mosaico that ships with this extension (https://github.com/civicrm/mosaico) is quite old.

I suspect there would need to be a lot of testing to upgrade it so it might not happen soon, but wanted to at least get a placeholder in here. 

On a related note, is there any documention on how we could maintain our own mosaico template that would not get overwritten when we upgrade this extension? That might provide a more elegant solution to this problem.

**Comment by jmcclelland** [comment]
I just opened a pull request against https://github.com/civicrm/mosaico, which might make for the easiest fix to this problem.

**Comment by mattwire** [comment]
Closing following 2.6 release. Please reopen if still an issue
