### ISSUE TITLE
Unable to upload images

### ISSUE THREAD

**Issue by JKingsnorth** [veda-consulting/uk.co.vedaconsulting.mosaico#29]
We were seeing problems with uploading images because of this part of CRM_Mosaico_Utils::processUpload

`      foreach ( $_FILES[ "files" ][ "error" ] as $key => $error )
      {
        if ( $error == UPLOAD_ERR_OK )
        {
`

$_FILES["files"]["error"] is an int not an array, so it can't use 'foreach'. Wouldn't it be better to use a structure like:

`      foreach ( $_FILES[ "files" ][ "error" ] as $key => $file_array )
      {
        if ( $file_array['error'] == UPLOAD_ERR_OK )
        {
`

This makes more sense to me as a loop - iterating over each file, rather than each error on a file?

**Comment by JKingsnorth** [comment]
I would submit a PR but we're fighting with a couple of other image uploading bugs at the moment so I can't verify that this proposed fix is a good idea ;]

**Comment by deepak-srivastava** [comment]
@JKingsnorth sounds fine to me. Please go ahead and do a PR. We 'll test & merge. Thanks.

**Comment by deepak-srivastava** [comment]
Also please give details about your environment, php version etc, when you PR. Will help us test. Thanks.

**Comment by JKingsnorth** [comment]
Will do, thanks deepak. As a side note, it looks like you also need to 'build' mosaico. Not just unpack the extension? Is this correct? It doesn't look like all the dependencies are there by default, which is causing us some additional problems. Eg: the code requires 'express' but the 'express' package isn't there unless you build mosaico as per their instructions.

**Comment by deepak-srivastava** [comment]
No probs. Let us know your findings. Re: build - mosacio is released after build. Just unpack should work. If its not, may be something wrong with build for your environment?

**Comment by JKingsnorth** [comment]
Could be, thanks for the help with this. We're stuck with a riddle at the moment where the page seems to send an AJAX POST request when you upload a file. But when it hits the processUpload function, it arrives as a GET request - so the '$_FILES' array is empty and cannot process it.

What I don't understand is why, if this is a legitimate bug, it isn't broken for everyone using the php backend. Not sure how it can be working -anywhere- :P But presently files aren't being uploaded to our server. It looks like they are, when you build a template the thumbnails are generated, but the files don't go into persist/contribute/

**Comment by JKingsnorth** [comment]
Could be, but I'm confused as to why:

- If I write a dummy form locally that just POSTs the file to /upload; it works correctly. The server recognizes the 'POST' request and uploads the file.

- When I use Mosaico's interface to upload the file, the ajaxSend event shows that it is making a POST call to /upload. However, we've put a line in /upload that prints the $_SERVER variables, and it says that the request type is 'GET'.

This suggests to me that it's not a config issue on the environment, but a problem with Mosaico or the interaction with Mosaico and the /upload script (possibly a problem with the jQuery-file-upload components.

Perhaps it's a problem with nodeJS which I guess is a requirement of running Mosaico - even if you use the PHP backend?

**Comment by JKingsnorth** [comment]
Hmn, maybe not. Just a wild goose chase again. Doh!

**Comment by JKingsnorth** [comment]
Looks like it could be an environment issue as I've got it working on localhost now. Will post back what we found in another issue with a bit more clarity. Thanks again for your time @deepak-srivastava
