### ISSUE TITLE
"Unexpected error talking to server" when saving template

### ISSUE THREAD

**Issue by josh-ecocentre** [veda-consulting/uk.co.vedaconsulting.mosaico#291]
Hi everyone,

Just installed Mosaico for CiviCRM 5.7.2 on Drupal 7.

Tried to make a dummy template and hit the save button but received an error saying "Unexpected error talking to server - contact us!" It then cleared the image that I had inserted there. 

(I followed the steps of 1) installing shoreditch, 2) installing flexmailer, 3) installing mosaico)

Any ideas on what to do?

Cheers,
Josh

@deepak-srivastava 

<img width="951" alt="mosaico blank screen when saving template" src="https://user-images.githubusercontent.com/47312876/52192816-1002ad00-28a0-11e9-8f03-4984c5966722.png">

**Comment by netzih** [comment]
Did you check your firewall settings.
I had something like this on a wordpress install and it turned out to be the wordfence firewall plugin blocking it.
I had to whitelist the param

**Comment by josh-ecocentre** [comment]
@netzih yeah have seen from what I've ready elsewhere that many people had that issue, however I don't think its to do with that. I'm using Drupal and don't have a firewall module installed, and couldn't find any firewall settings on cpanel.

**Comment by mattwire** [comment]
Closing following 2.6 release. Please reopen if still an issue
