### ISSUE TITLE
URL's broken when click-through tracking enabled

### ISSUE THREAD

**Issue by aydun** [veda-consulting/uk.co.vedaconsulting.mosaico#293]
With click-through tracking disabled, the links work as expected to https://mysite/wp-content/uploads/2017/05/doc.pdf

When click-through tracking is enabled the link is mangled to https://mysite/home/webuser/www/www/wp-content/plugins/civicrm/civicrm/extern/url.php?u=470&qid=29987

It should be https://mysite/wp-content/plugins/civicrm/civicrm/extern/url.php?u=470&qid=29987

Possibly related to https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/165

Mosaico 2.0-beta4.1528762072  Civi 5.8.1  WP 5.0.3

**Comment by themak1985** [comment]
@aydun 

Are you using an old template or is this happening with base templates too?

Sometimes the issue is with old templates. I suspect that if you were to recreate your template from from a new versafix-1 or whatever base you are using - all would work without issue.

**Comment by aydun** [comment]
@themak1985 - it turns out not to be a Mosaico issue but related to wp-cli that was being called from cron to run the scheduled job.  See https://lab.civicrm.org/dev/wordpress/issues/18
