### ISSUE TITLE
versafix template has profile_link that doesn't seem to work

### ISSUE THREAD

**Issue by jmcclelland** [veda-consulting/uk.co.vedaconsulting.mosaico#294]
In the UI, when you are editing the Versafix template and click the head and then switch to the content tab, the Unsubscribe link has three options: Profile, Unsubscribe, and None.

Choosing None makes it go away (nice), choosing Unsubscribe makes it create a working unsubscribe link, but choosing Profile seems to create a broken link (it takes you to https://[site.org]/sites/all/modules/civicrm/extern/[profile_link]).

In mosaico.php there is a line that is commented out with a FIXME, which is a hint :).

Given the [response to this upstream ticket](https://github.com/voidlabs/mosaico/issues/488), maybe the profile_link option should simply be removed from packages/mosaico/templates/versafix-1/template-versafix-1.html (which I guess means a patch to our mosaico code instead of a patch here?

**Comment by Rar9** [comment]
when will this  Versafix template work again?
