### ISSUE TITLE
Unexpected Upload Error

### ISSUE THREAD

**Issue by PalanteJon** [veda-consulting/uk.co.vedaconsulting.mosaico#3]
There seems to be some broken functionality on my install around the image upload.  You can see that the placeholder language isn't present (the one that says "166x130" for the dimensions), and I get the JSON error at the bottom of this screenshot when I try to add a photo.

I'm willing to help debug, but don't know where to start.  If you have any pointers I can take a crack at this.
![workspace 1_123](https://cloud.githubusercontent.com/assets/1796012/13437848/51798624-dfb4-11e5-911b-4b69ca122213.jpg)

**Comment by deepak-srivastava** [comment]
@PalanteJon 
1. Do you have extension resource url set? Urls built from them help images to load.
2. Do you see anything in JS console?

I'm assuming you using latest code (alpha2 as of now).

**Comment by PalanteJon** [comment]
@deepak-srivastava It's so obvious how to start troubleshooting this once you say it, I'm not sure why I didn't do the obvious.

Anyway, I checked my "Network" tab in my dev tools, and I see that the extension expects an "img" folder that's not part of the git repo.  That doesn't answer the "unexpected upload" issue, but certainly explains the missing images.

**Comment by deepak-srivastava** [comment]
So placeholder image url should be in format like - 
http://example.org/civicrm/mosaico/img/?method=placeholder&params=166%2C90

However its not a directory. It initiates a callback function (processImg):
https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/master/CRM/Mosaico/Utils.php#L171
Which on the fly generates an image with that dimension. 
So something wrong in there. Your screen says upload error. So most likely uploads or uploads/static dir is not writeable by web user (like suggested in installation instruction - https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/master/README.md) ?

**Comment by PalanteJon** [comment]
@deepak-srivastava I've got it sorted!  My apologies - I didn't restart Apache after installing ImageMagick.

I'm guessing that a lot of novice users won't catch this issue - especially since ImageMagick support is compiled into PHP by default in many configurations, but not (e.g.) on Debian by default.

If you're amenable, I'll submit a PR that invokes `hook_civicrm_check` to check for the existence of ImageMagick, and throw an error if it's not running?

**Comment by deepak-srivastava** [comment]
@PalanteJon that would be awesome :+1:

**Comment by PalanteJon** [comment]
Hmm - I wrote my code in #4 before I saw this post!  If you like, I can also add the code there.  I still think it makes sense to add it to `hook_civicrm_check`, for those of us who make a living monitoring CiviCRM installs :)  Let me know - otherwise we can close this and just continue on #4.

**Comment by deepak-srivastava** [comment]
@PalanteJon that looks good for now.

**Comment by jaapjansma** [comment]
I had an installation with Wordpress and I had the same problems with uploading images. I solved it by changing the following lines in CRM/MosaicoUtils.php

     BASE_URL' => $civiConfig->extensionsURL . '/uk.co.vedaconsulting.mosaico/packages/mosaico/',

     /* local file system base path to where image directories are located */
     //'BASE_DIR' => dirname( dirname( $_SERVER[ "SCRIPT_FILENAME" ] ) ) . "/",
    'BASE_DIR' => $civiConfig->extensionsDir . '/uk.co.vedaconsulting.mosaico/packages/mosaico/',

I have added a **slash /** after `$civiConfig->extensionDir . '`

I have also added a map thumbnails in packages/mosaico/uploads

**Comment by R-Frost** [comment]
firstly  thank you very much for this extension - this is really exciting.

Extension is working just fine.. all except for the images - cant upload or display.. Uploaded images  show for a second or so and then up comes the JSON error and images disappear.  Firefox gives slightly different error message to Chrome...  unexpected character in  line 1 column 1

Wordpress 4.5.2  Civi 4.6.16  extension Alpha 5  resource URLs set
