### ISSUE TITLE
Does this work to edit system message templates?

### ISSUE THREAD

**Issue by JoeMurray** [veda-consulting/uk.co.vedaconsulting.mosaico#30]
Does this currently allow one to edit system message templates?

Is it feasible to do that or a lot of effort either in integrating the functionality into the pages or in modifying the existing system message templates?

**Comment by deepak-srivastava** [comment]
Nope it does not. 

Mosaico templates have their own format of storing messages (includes metadata). So unless a template was built using it, it can't load/import other templates.

I remember seeing such requests on mosaico.io. I'll dig down a bit more and see whats the status.

**Comment by JoeMurray** [comment]
I think it would be very valuable. 

BTW, what is your estimate for when a production version will be ready? What remains to be done and what help is required?

**Comment by veda-consulting** [comment]
@JoeMurray we release a beta release last week, we feel this is production ready.

**Comment by deepak-srivastava** [comment]
@JoeMurray just a note that the import feature is experimental. What it does is basically creates a block of text in block with html from message template. Idea is that the user then picks up right blocks in the builder, and modifies the template. Once done, clicking save creates a mosaico template. We have added a warning to the feature to make it more clear:

> WARNING: This is experimental feature. Please note that the content may not appear exactly in same layout. However using the builder, by adding new blocks, you can turn it into a layout you desire. This feature is intended to import your old message templates in builder, so you can re-use and create new mosaico templates.
> 
> If you really want to make most of mosaico builder, its recommended to create a new one from "Mosaico Message" tab.
> 
> Note that the feature doesn't modify your existing message template. Pressing SAVE in template builder will create new message template. If you intend to create a copy of an existing mosaico template, use the new copy feature instead, available in "Mosaico Messages" tab.
>

**Comment by deepak-srivastava** [comment]
Closing this one for now. Can open new tickets for any discussions on experimental feature.
