### ISSUE TITLE
Duplicate menu Item for 'New Mailing (Traditional)'

### ISSUE THREAD

**Issue by chumkui** [veda-consulting/uk.co.vedaconsulting.mosaico#302]
I did a test upgrade today to Version 2.0 of Mosaico - all went well, but it has created an additional menu item 'New Mailing (Traditional)' in the CivicRM Mailing menu.  So I have now have two items that are identical with Mosaico Templates sandwiched in between.  I think it is linked to the 'fixing' of [ Issue 197](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/commit/f082c52084e51d9c60f43f649df07218a777a333)

**Comment by mattwire** [comment]
This is probably because of an old install of mosaico that didn't add the menu in the "standard" way.  It can be fixed by deleting manually from the navigation menu
