### ISSUE TITLE
New Mailing gives double Civi

### ISSUE THREAD

**Issue by loganbear** [veda-consulting/uk.co.vedaconsulting.mosaico#307]
When selecting New Mailing, after latest Civi upgrade (5.15.3), the New Mailing option displays a double Civi header with nothing else, and the menu options change to "https://[civicrm_url]/a/#:.  With Mosaico disabled, the New Mailing menu option gives the expected results.  I even ran Mosaico without Shoreditch to see if it was a theme error, and I got the same result.

![Screen Shot 2019-05-14 at 12 03 12 PM](https://user-images.githubusercontent.com/939958/57713464-869e0c00-7640-11e9-8f1d-4f64ef9cc28b.png)

**Comment by loganbear** [comment]
Actually, this issue started with the CIvi upgrade 5.15.2.

**Comment by MegaphoneJon** [comment]
@loganbear Is this still happening for you, or is it good to close this issue?
