### ISSUE TITLE
official 2.0 release warns of missing dependencies

### ISSUE THREAD

**Issue by Upperholme** [veda-consulting/uk.co.vedaconsulting.mosaico#309]
I updated from the 2.0 beta over the weekend, by downloading the tarball, extracitnig into my extensions folder and deleting the older mosaico directory. Now getting this. I'll try re-installing via a different install option. But right now I can't access the Mosaico interface or send a mailing that's ready to go.

 ![Screenshot 2019-05-20 at 09 39 20](https://user-images.githubusercontent.com/5860951/58008016-61e3e180-7ae3-11e9-8798-70df2043ccfe.png)

**Comment by mattwire** [comment]
@Upperholme Where did you download the tarball from? github or the link from here: https://civicrm.org/extensions/email-template-builder

the github tarball won't work as there is an additional build step to include the packages.  You need the zip from civicrm.org/extensions

**Comment by Upperholme** [comment]
Thanks, that's got it sorted.

**Comment by mattwire** [comment]
@Upperholme Great, I've updated the notes on the github release page too so it should be clearer!
