### ISSUE TITLE
Migrated templates not loading

### ISSUE THREAD

**Issue by kelizoliva** [veda-consulting/uk.co.vedaconsulting.mosaico#310]
This is issue is occurring for Drupal 7.63 using CiviCRM 5.13.4 and PHP 7.0.x. Both image magick and gd are available on the system.

Upgraded to Mosaico v2, and ran the template migration assistant. Now selecting any of the migrated templates results in a blank/navy screen, rather than the expected template edit screen. The three templates that come packaged with v2 load without any issues. There are no errors coming up in the Civi logs, Drupal logs or apache logs.

Any ideas?

**Comment by kelizoliva** [comment]
Also noting that all caches have been cleared, emptied templates_c/, checked all permissions.

**Comment by jusfreeman** [comment]
@kelizoliva check the javascript console script errors. Check the network console for 404 - resource not found errors.

Mosaico templates and Mosaico mailings store absolute paths in the body_html so if any of the URLs changes then all the templates and mailings will not load, URLs are broken. The process to fix is to run a series of find/replace SQL queries on the database to fix.

**Comment by jusfreeman** [comment]
@kelizoliva See #87

**Comment by kelizoliva** [comment]
Ah, thanks for the info! I will review that other thread.

**Comment by kelizoliva** [comment]
Actually going to leave this open until I actually check on this to see if it is a related issue.

**Comment by mattwire** [comment]
Closing following 2.6 release. Please reopen if still an issue
