### ISSUE TITLE
Error Loading Images using GD

### ISSUE THREAD

**Issue by ryanlrobinson** [veda-consulting/uk.co.vedaconsulting.mosaico#312]
The issue occurs when attempting to upload an image in the template builder. We receive the message "Unexpected upload error (Service unavailable (with message))". It also writes to the Drupal log:

Error: Class 'Imagick' not found in CRM_Mosaico_Utils::processUpload() (line 231 of /home/pillar/public_html/sites/default/files/extensions/uk.co.vedaconsulting.mosaico/CRM/Mosaico/Utils.php).

We traced that to find that the code seems to have a clear reference to the Imagick class even though the setting in /civicrm/admin/mosaico?reset=1 is set to "Intervention Image API (gd)" and GD is installed and working. But this code doesn't seem to allow for GD instead of ImageMagick. Please add this support ASAP.

**Comment by tapashdatta** [comment]
Hi @ryanlrobinson Did you find any solution for this issue? thanks

**Comment by ryanlrobinson** [comment]
It's not a true solution, just a workaround, but here's a diff of what my colleague came up with:

```
@@ -228,14 +228,8 @@
           if (move_uploaded_file($tmp_name, $file_path) === TRUE) {
             $size = filesize($file_path);

-            $image = new Imagick($file_path);
-
-            $image->resizeImage($config['THUMBNAIL_WIDTH'], $config['THUMBNAIL_HEIGHT'], Imagick::FILTER_LANCZOS, 1.0, TRUE);
-            // $image->writeImage( $config['BASE_DIR'] . $config[ THUMBNAILS_DIR ] . $file_name );
-            if ($f = fopen($config['BASE_DIR'] . $config['THUMBNAILS_DIR'] . $file_name, "w")) {
-              $image->writeImageFile($f);
-            }
-            $image->destroy();
+            // Imagemagick not working, so simply copy same file as thumbnail
+            copy($file_path, $f);
```

**Comment by tapashdatta** [comment]
@ryanlrobinson Thanks that worked. although not best solution but good workaround.

**Comment by francescbassas** [comment]
Same issue. I suspect it should be fixed in some way similar to

`CRM/Mosaico/Utils.php`
```
-            $image = new Imagick($file_path);
-
-            $image->resizeImage($config['THUMBNAIL_WIDTH'], $config['THUMBNAIL_HEIGHT'], Imagick::FILTER_LANCZOS, 1.0, TRUE);
-            // $image->writeImage( $config['BASE_DIR'] . $config[ THUMBNAILS_DIR ] . $file_name );
-            if ($f = fopen($config['BASE_DIR'] . $config['THUMBNAILS_DIR'] . $file_name, "w")) {
-              $image->writeImageFile($f);
-            }
-            $image->destroy();
+            Civi::service('mosaico_graphics')->createResizedImage($file_path, $config['BASE_DIR'] . $config[ THUMBNAILS_DIR ] . $file_name, $config['THUMBNAIL_WIDTH'], $config['THUMBNAIL_HEIGHT']);
```

@totten could you check it out?

**Comment by tapashdatta** [comment]
@francescbassas thanks for the patch, it seems to worked for me.

**Comment by francescbassas** [comment]
@tapashdatta great, but I insist that someone who knows the code better should review it. I pulled it out by intuition.

**Comment by francescbassas** [comment]
@tapashdatta great, but I insist that someone who knows the code better should review it. I pulled it out by intuition.

**Comment by agileware-fj** [comment]
Confirming again that @francescbassas's change works.
The call to createResizedImage is consistent with the Imagick class code used.

I've also done a quick search through the code and can't find any other direct references to Imagick outside of the service class.
