### ISSUE TITLE
Mosaic templates only opening in traditional mailer

### ISSUE THREAD

**Issue by egrubbs-accd** [veda-consulting/uk.co.vedaconsulting.mosaico#313]
When Mosaico extension was uploaded, we did not get a new menu item (New Mailing (Traditional)). We still have Mailings > New Mailing, but this opens the traditional mailer. (Screenshot attached)
![mosaico]

(https://user-images.githubusercontent.com/52002145/59773209-3f2c2080-927b-11e9-9d2d-a5cd68109d7b.PNG)

I can use Mosaico templates in the traditional mailer, but the template looks pretty different (altered layout, no buttons etc). 

Using Mosaico 1.1 on CiviCRM 5.11

**Comment by mattwire** [comment]
Closing following 2.6 release. Please reopen if still an issue
