### ISSUE TITLE
Smarty not working for default first nae when first name is null

### ISSUE THREAD

**Issue by netzih** [veda-consulting/uk.co.vedaconsulting.mosaico#314]
I would like to send my emails and start with "dear contact first name" but I want there to be a default when a contact has no first name listed.
With smarty you can type "{capture assign=first_name}{contact.first_name}{/capture}
Dear {$first_name|default:Friend},
{if $first_name}"
And it will do that (works with traditional mailing) but with Mosaico it is not working.

**Comment by larssandergreen** [comment]
Smarty is not compatible with Mosaico:

https://civicrm.stackexchange.com/questions/28471/smarty-and-mosaico-compatibility
