### ISSUE TITLE
Securi flagging jquery-file-upload as out-dated.

### ISSUE THREAD

**Issue by caracolmzd** [veda-consulting/uk.co.vedaconsulting.mosaico#318]
> Status: Outdated
>Warning: Found outdated jQuery File Upload plugin inside: ./sites/default/files/civicrm/ext/uk.co.vedaconsulting.mosaico/packages/mosaico/dist - Version: 5.42.1 - Please update asap.

However I can't see clearly that this jquery plugin is actually used, and the references in `unused.js` makes it seem it may not be a real dependency.

This is likely an issue that should be reported upstream, but if it is indeed being deprecated upstream, then it seemed like reporting to you first would be most productive since I'm not sure  how closely this extension is tracking upstream.

**Comment by caracolmzd** [comment]
I do actually see that this plugin is used:

``` shell 
CRM/Mosaico/Page/Editor.php:31:      "{$mosaicoDistUrl}/vendor/jquery.fileupload.js?r={$cacheCode}",
CRM/Mosaico/Page/Editor.php:32:      "{$mosaicoDistUrl}/vendor/jquery.fileupload-process.js?r={$cacheCode}",
CRM/Mosaico/Page/Editor.php:33:      "{$mosaicoDistUrl}/vendor/jquery.fileupload-image.js?r={$cacheCode}",
CRM/Mosaico/Page/Editor.php:34:      "{$mosaicoDistUrl}/vendor/jquery.fileupload-validate.js?r={$cacheCode}",
CRM/Mosaico/Page/Editor.php:68:      'fileuploadConfig' => array(
```

This also appears that the dependency is not just in the upstream code, but in this extension.
Let me know if I should open an issue on the mosaico repo, or if there is anything else I can do to support you on this issue.

Cheers

**Comment by mattwire** [comment]
Closing following 2.6 release. Please reopen if still an issue
