### ISSUE TITLE
{action.unsubscribeUrl} from template doesn't work

### ISSUE THREAD

**Issue by haraldballuch** [veda-consulting/uk.co.vedaconsulting.mosaico#32]
I've added a block to the template "packages/mosaico/templates/versafix-1/template-versafix-1.html", so that it can be used as standard footer with an unsubscribe link, generated by a CiviCRM token.

The block works so far, but inserting the block into a specific mail changes the link. In the template, the link is "{action.unsubscrineUrl}". After inserting it is changed to "https://domain.com/sites/default/files/civicrm/ext/uk.co.vedaconsulting.mosaico/packages/mosaico/templates/versafix-1/{action.unsubscribeUrl}". The only way to deal with this, is to change the URL after insert back to "{action.unsubscribeUrl}". Of course this is not so comfortable and can be easily forgotten.

Is there a way to preserve the token link, during the process of inserting a block into a mail?

**Comment by rocxa** [comment]
It appears Mosaico doesn't check for tokens in href="", it just tries to fix the url if it doesn't look absolute.  It looks like someone (https://github.com/bago) has tried to improve this a bit but no support for tokens yet.

https://github.com/voidlabs/mosaico/commit/8e35081fcae8e982295fc37d0e51182050d8ff7c#diff-791928bf427ad5b26b37620862d67e7eL133 

Is there a way to stop Mosaico from converting token urls universally.. I imagine not as token are in different formats for almost every mailer software so perhaps a CiviCRM specific solution is the answer here.

Overriding the js function _templateUrlConverter (canonicalize in the current version) to also look for the {*} token format and leave it alone may work.

**Comment by rocxa** [comment]
To test the fix..

Search for  _templateUrlConverter=function(e,t)

Add 

`t.match("^{[A-Za-z0-9_\.]+}")|| `

to the other match criteria after the return statement for that function e.g.

`_templateUrlConverter=function(e,t){return t.match("^{[A-Za-z0-9_\.]+}")||t.match(/^[^\/]*:/)||t.match(/^\//)||t.match(/^\[/)||t.match(/^#?$/)?null:e+t},`

Works for me with CiviCRM tokens such in the format {something_123.something_else123}

**Comment by deepak-srivastava** [comment]
The latest beta release has this fixed, like suggested by @rocxa. 
@haraldballuch Would be great if you could test if the fix works for you? Thanks.

**Comment by deepak-srivastava** [comment]
Closing this one. Please re-open if its still an issue with latest beta release. Thanks.
