### ISSUE TITLE
v5.15 - Failed to locate Mosaico graphics driver. 

### ISSUE THREAD

**Issue by marcelklehr** [veda-consulting/uk.co.vedaconsulting.mosaico#320]
Hey there,

I've just tried to install this extension on CiviCRM 5.15 and got loads of errors in the admin settings as well as an error about graphics drivers not being found although gd *and* imagick are installed and can be used in php.

**Comment by MegaphoneJon** [comment]
@marcelklehr I'm using Mosaico on CiviCRM 5.15.  Could you please paste the text of the errors into this issue?  It's difficult to provide help without seeing them.

It may also be more helpful to post this to https://civicrm.stackexchange.org; more people will see it there.

**Comment by marcelklehr** [comment]
Sorry. Here goes:

```
Error: Failed to locate Mosaico graphics driver. Either "mosaico_graphics" is invalid or the autodetection failed.
```

```
Notice: Undefined index: html_type in CRM_Admin_Form_Setting->getQuickFormType() (line 282 of /var/www/services/civicrm/web/sites/all/modules/civicrm/CRM/Admin/Form/SettingTrait.php).
Notice: Undefined index: name in CRM_Admin_Form_Setting->getQuickFormType() (line 284 of /var/www/services/civicrm/web/sites/all/modules/civicrm/CRM/Admin/Form/SettingTrait.php).
Notice: Undefined index: html_type in CRM_Admin_Form_Setting->getQuickFormType() (line 285 of /var/www/services/civicrm/web/sites/all/modules/civicrm/CRM/Admin/Form/SettingTrait.php).
```
(times ~7)

**Comment by marcelklehr** [comment]
Mmmh. Disabling and re-enabling the extension worked wonders. Thanks for the hint to [check civi stackexchange](https://civicrm.stackexchange.com/questions/30856/failed-to-locate-mosaico-graphics-driver/31270#31270)!
