### ISSUE TITLE
Feature request: Will the "download" button come back?

### ISSUE THREAD

**Issue by haraldballuch** [veda-consulting/uk.co.vedaconsulting.mosaico#325]
Up to version 1.1 it was possible to download the html from within the gui of mosaico. Since version 2 the button is gone. Is it planned to bring this button back? 
For our workflow this was very useful, for example to create a webversion independently from the CiviCRM server.

**Comment by eileenmcnaughton** [comment]
@totten @mountev - any thoughts?

**Comment by deepak-srivastava** [comment]
I don't think it's on radar, unless @totten has any plans.

For concept approval - one thing for discussion could be "what happens to tokens". Tokens are workflow dependent and may not get parsed for download. 

Work around could be using view-in-browser and downloading the html, but that's more number of clicks.

**Comment by haraldballuch** [comment]
Regarding parsing of tokens:
What makes sense, depends on what you plan to do with the HTML. If you want to use it to be able to send a mailing with a text part, that was not automatically created, see [Feature request: individual text part of mailing](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/324), then it fits perfectly, if the tokens are not parsed.

If you want to use the html for a web version of the mailing, then parsing of tokens could be better. But in most cases you have to adapt the content created by the tokens to something anonymous any way. So for this two use cases the parsing of the tokens is not necessary or even not wanted.

I tried the suggested work around with downloading the preview-in-browser html, but I failed. Probably because it is loaded by JavaScript I get only some useless html-code. Is there a way to get the html of the mailing (without sending a test message and copying it there from the source)?
