### ISSUE TITLE
Button Text Issues

### ISSUE THREAD

**Issue by themak1985** [veda-consulting/uk.co.vedaconsulting.mosaico#328]
So I am surprised this isn't an issue for anyone else - using latest Civi and Drupal7 or Wordpress.

When I go to change the text of a button, if I try to delete the text first or replace it - it gets stuck - meaning I can't type anything.  My only solution has been to insert a token and edit from the middle of the token then delete text to the right and left. Not ideal.

has anyone else experienced this - or is it just me on 3 websites?

**Comment by MegaphoneJon** [comment]
I'm not seeing this.  I just recorded the following video on a site running Civi 5.16.3, latest Drupal, and Mosaico 2.1.1559427853.  Are we talking about the same thing?


![mosaicobutton](https://user-images.githubusercontent.com/1796012/63960286-2058c000-ca5c-11e9-9c6b-f0a84a909aa4.gif)

**Comment by themak1985** [comment]
I think I have narrowed this down to only happening when editing buttons that existed in a template or in a previously sent email that is being reused. New blocks are unaffected. I can only type one letter - but in example of headline - i lost the text box completely.  Also happening only in Versafix-1 (at least thats the only one we use.) https://columbiauniversity.zoom.us/recording/share/554qnqWuKvHFb_5kMMxj-LfRWb9XjjlFUJkC4jQ0X_awIumekTziMw?startTime=1567100249000

**Comment by MegaphoneJon** [comment]
@themak1985 I tried replicating what you're showing on a reused email, and I couldn't replicate it.  I can't make a video because it's not my mailing to share.  However, I would check your Developer Tools (press F12) and check the *Console* tab for errors.

**Comment by themak1985** [comment]
All I can see is the following, seems to be an issue with tinymce. The first error is from wordpress - the second is from drupal - they are essentially the same thing.


`Uncaught TypeError: Cannot read property 'firstChild' of null
    at p.isEmpty (tinymce.min.js?r=3lwYZ:4)
    at A.<anonymous> (tinymce.min.js?r=3lwYZ:10)
    at t.i [as fire] (tinymce.min.js?r=3lwYZ:8)
    at A.fire (tinymce.min.js?r=3lwYZ:8)
    at p.s (tinymce.min.js?r=3lwYZ:10)
    at e (tinymce.min.js?r=3lwYZ:2)
    at HTMLAnchorElement.m (tinymce.min.js?r=3lwYZ:2)
isEmpty @ tinymce.min.js?r=3lwYZ:4
(anonymous) @ tinymce.min.js?r=3lwYZ:10
i @ tinymce.min.js?r=3lwYZ:8
fire @ tinymce.min.js?r=3lwYZ:8
s @ tinymce.min.js?r=3lwYZ:10
e @ tinymce.min.js?r=3lwYZ:2
m @ tinymce.min.js?r=3lwYZ:2`


`tinymce.min.js?r=xu5eX:4 Uncaught TypeError: Cannot read property 'firstChild' of null
    at p.isEmpty (tinymce.min.js?r=xu5eX:4)
    at A.<anonymous> (tinymce.min.js?r=xu5eX:10)
    at t.i [as fire] (tinymce.min.js?r=xu5eX:8)
    at A.fire (tinymce.min.js?r=xu5eX:8)
    at p.s (tinymce.min.js?r=xu5eX:10)
    at e (tinymce.min.js?r=xu5eX:2)
    at HTMLAnchorElement.m (tinymce.min.js?r=xu5eX:2)
isEmpty @ tinymce.min.js?r=xu5eX:4
(anonymous) @ tinymce.min.js?r=xu5eX:10
i @ tinymce.min.js?r=xu5eX:8
fire @ tinymce.min.js?r=xu5eX:8
s @ tinymce.min.js?r=xu5eX:10
e @ tinymce.min.js?r=xu5eX:2
m @ tinymce.min.js?r=xu5eX:2`

**Comment by themak1985** [comment]
I am starting to wonder if I just need to rebuild the templates - I made a new one - the error does not occur - (the templates were made in Mosaico 3/4 beta - not sure which.)

What I am able to replicate however is entering delete twice on a button (highlight all text, push delete, push delete again) will make it no longer editable.  (is there a mosaico demo out there I can test this further on?)
