### ISSUE TITLE
Installing on Drupal 8.7 / Civi 5.16.3 - Out of memory error

### ISSUE THREAD

**Issue by jamie-tillman** [veda-consulting/uk.co.vedaconsulting.mosaico#329]
After installing on a system with Drupal 8.7 and Civi 5.16.3, the New Mailing page fails to load and reports an out of memory error in the error log.  I have 4G allocated to PHP memory_limit and every other page in the system seems to load.  Disabling the extension allows the page to load.

**Comment by eileenmcnaughton** [comment]
@seamuslee001 @totten any ideas? 

@jamie-tillman do you have a lot of mailings or a lot of groups in your system

**Comment by jamie-tillman** [comment]
This is essentially a test system.  Very few groups and mailings.  Id say
less than 10 of each.

**Comment by seamuslee001** [comment]
I have no idea. Maybe something permissions related on API calls or something but I dunno.

**Comment by michael-chaplin-gmcvo** [comment]
have you installed flexmailer as per https://civicrm.org/extensions/email-template-builder ?

**Comment by jamie-tillman** [comment]
> 
> 
> have you installed flexmailer as per https://civicrm.org/extensions/email-template-builder ?

This was more than a month ago, but as I recall I did install according to those instructions.  If I run another test (the one I was using has been removed) I'll confirm it and report back here.

That said, the installation steps are quite brief so it seems it would be simple to put in some basic checks.  It's impossible to catch all conditions, of course, but having the app simply crash out from memory exhaustion due to a missing dependency is a sure path to a poor user experience and lack of adoption.

**Comment by jamie-tillman** [comment]
Also, I corrected the title of the issue I created.  I'm sure it was obvious, but I wasn't using Drupal 5 for this!

**Comment by jackrabbithanna** [comment]
I seen several PHP out of memory errors with CiviCRM and Drupal 8 when there's an exception and the error handling has Drupal data in it like the user object, and the backtrace variable data can get HUGE.

If you edit CRM/Core/Error.php in CiviCRM Core
debug_var() method
comment out/change this bit:
```
else {
  //ob_start();
      //  var_dump($variable);
      //  $dump = ob_get_contents();
     //   ob_end_clean();
      $out = "\n\$$variable_name";
}
```
Civi will get on and return from that function and you should see a CiviCRM error page with the exception message.

From there you can figure out what the real issue is because the out of memory error was after the exception thrown.

**Comment by mattwire** [comment]
Closing following 2.6 release. Please reopen if still an issue
