### ISSUE TITLE
Smileys produce truncated mails

### ISSUE THREAD

**Issue by aydun** [veda-consulting/uk.co.vedaconsulting.mosaico#330]
If someone pastes in a smiley eg  😁 in the mail content then the mail looks ok on screen but is truncated at that point when sending.

Not sure whether the problem is in the message composition or sending function.

**Comment by eileenmcnaughton** [comment]
Isn't this because the DB field is not utfmB8?

**Comment by mattwire** [comment]
This is a utf8mb4 issue
