### ISSUE TITLE
Translation (in french and others languages)

### ISSUE THREAD

**Issue by UshaMakoa** [veda-consulting/uk.co.vedaconsulting.mosaico#336]
Hello
I'd like to have the top bar in mosaico translated in french (the Save, Gallery... buttons).
I've translated in french the most of stings that were not alreay translated in transifex. But it's not enough.
I saw that there are translations files already in the library and in the version is used in CiviCRM (thanks @mattwire). It's here https://github.com/voidlabs/mosaico/tree/v0.15/res/lang
But it doesn't seem to be activated in the Mosaico Civi extension.
Does anybody have already activated it in some way ?
If not does anyone would be interested in improve it ? Perhaps I could pay for it, it depends the time necessary to do it. And I hope I'll be able in a couple of weeks to do it by myself or contribute by other ways...
If not does anyone would have in idea of where in the code I could change the locale ?

Thanks for reading,

**Comment by mattwire** [comment]
This will be in the next release now that #338 has been merged
