### ISSUE TITLE
Create Mailings, not a real permission?

### ISSUE THREAD

**Issue by caracolmzd** [veda-consulting/uk.co.vedaconsulting.mosaico#341]
The CRM_Mosaico_Utils::processImg() function handles requests for placeholder images.
A user without admin permissions reported not being able to upload images. Investigation revealed that drag and drop to upload was un-usable because placeholder images were not rendered and Chrome is a terrible browser.

The permission check here:
https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/2.x/CRM/Mosaico/Utils.php#L300
... requires "create mailings".

I could find this permission nowhere. 

A similar question went un-answered on this blog post:
https://civicrm.org/comment/9270#comment-9270

**Comment by homotechsual** [comment]
It's very much a real permission - see https://github.com/civicrm/civicrm-core/blob/bdeb5d154507df2dc913fc1ee9aaedfaa4721c04/CRM/Mailing/Info.php as an example.

**Comment by homotechsual** [comment]
and more examples: https://github.com/civicrm/civicrm-core/search?q=create+mailings&unscoped_q=create+mailings

**Comment by caracolmzd** [comment]
resolved by: #342

**Comment by caracolmzd** [comment]
Yeah, as I've learned, it is a real permission but it only exists if some condition is met... having to do with a "workflow".
https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/340#issuecomment-545916953

I wonder if it is added by flexmailer??

**Comment by seamuslee001** [comment]
@ginkgomzd no its been around for ages, you have to set workflow process in the CiviMail component settings iirc
