### ISSUE TITLE
After updating to 2.3 Civi continues to alert me about an update to 2.3 being available

### ISSUE THREAD

**Issue by Upperholme** [veda-consulting/uk.co.vedaconsulting.mosaico#343]
And I note that you've updated the info.xml file just 17 hours ago. So if I replace my installed info.xml with the current master will that fix the problem?

**Comment by MegaphoneJon** [comment]
This isn't specific to Mosaico, it sounds like for whatever reason your CiviCRM hasn't deleted `version-msgs-cache.json`.  This was a bug in older versions, it can also happen for file permission reasons.  If you delete that file the message should go away.  It'll also go away on its own when that cache is invalidated (every 72 hours).
