### ISSUE TITLE
Updates overwrite template files

### ISSUE THREAD

**Issue by Upperholme** [veda-consulting/uk.co.vedaconsulting.mosaico#344]
Not unreasonably, when Mosaico is updated, the new version installs its own base template files. Notably for me, as all my templates are based on the versafix-1 base, when this happens of course my templates lose access to the custom fonts that I coded into my version of versafix-1.
So, not a bug as such, but for forgetful types like me, a great feature would be an alert that reminds me that any cusotmisations to base templates will be lost in an update.

Or better yet, is there a way to store custom base template files outside of the extension's directory, somewhere like sites/default/files/civicrm/custom/mosaico ?

**Comment by francescbassas** [comment]
@Upperholme you can do exactly what you say. See "Custom Templates Directory" setting on your "Mosaico Settings" page civicrm/admin/mosaico?reset=1.

**Comment by Upperholme** [comment]
@francescbassas Thanks for that. I didn't know this setting even existed!
