### ISSUE TITLE
Translations not loaded

### ISSUE THREAD

**Issue by skyslasher** [veda-consulting/uk.co.vedaconsulting.mosaico#346]
Hello,

the translation files do not get loaded on Mosaico start. It seems that the configuration searches a wrong path:
https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/2.x/CRM/Mosaico/Page/Editor.php#L107
This should be 
`    $translationFile = CRM_Core_Resources::singleton()->getPath(E::LONG_NAME, "packages/mosaico/dist/lang/mosaico-{$lang}.json");
`

Regards
Andreas

**Comment by mattwire** [comment]
@skyslasher See #362 please confirm if it fixes the issue
