### ISSUE TITLE
View in browser has relative paths

### ISSUE THREAD

**Issue by pbatroff** [veda-consulting/uk.co.vedaconsulting.mosaico#349]
When view in browser is used, the shipped mosaico icons are displayed in relative paths, e.g. `/sites/default/files/civicrm/persist/mosaico_tpl/versafix-1.1/img/icons/fb-rdcol-96.png`. Can be reproduced by creating a mailing with social Icons, and then view in browser, and inspect element of the social Icon.

The HTML Code for the mail is parsed before sending by URLFilter, to adjust relative file paths, so the links are valid there. I think it would make sense to add that to the view in Browser page as well. The same code could be used, but in a page hook.

**Comment by thoni56** [comment]
I'm not sure I exactly understand the description of this issue, it seems technical to me ;-)

I'm experiencing something similar. In the editor the social icons are showing up as expected but not in the sent emails or in the web view.

I'm on CiviCRM 5.20.2 with the latest Mosaico (on Joomla). In the web view the path is 

    <webroot>/templates/versafix-1/img/social_def/facebook_bw_ok.png

but the icon is actually here:

    <webroot>/media/civicrm/custom_ext/uk.co.vedaconsulting.mosaico/packages/mosaico/templates/versafix-1

So it seems that the path is not generated correctly when creating the published views.
