### ISSUE TITLE
Invisible (white) a:visited links in desktop Outlook

### ISSUE THREAD

**Issue by ryanlrobinson** [veda-consulting/uk.co.vedaconsulting.mosaico#354]
Hi,

We have deployed Mosaico to a client and they caught an issue with the styling. When you click on a link in desktop Outlook, the link then goes invisible - white, against a white background. I haven't encountered the problem viewing in browser or from Outlook web app. Their template is built off the versafix-1 template.

Could anybody either direct me to how to override that, or implement a fix for the next version?

Thanks

**Comment by rick-compucorp** [comment]
Have also had some reports of this. Same experience as @ryanlrobinson. Browsers ok, but Outlook causing the issue.
