### ISSUE TITLE
The tinymce floating panel won't go away 

### ISSUE THREAD

**Issue by johncronan** [veda-consulting/uk.co.vedaconsulting.mosaico#356]
This appears to have something to do with the show/hide behavior of the tinymce panel, when clicking on a block to edit its text. Sometimes it doesn't get hidden when you click out. Then, as you're scrolling through the content in your template, it attaches itself to the top of the various blocks.

Oddly, whatever the source of the problem is, it's getting saved to my template. So when I bring it up again in a freshly loaded page, the problem is still there.

In fact, it can end up happening more than once! Here's what my template looks like now, if I scroll to the very bottom:

![Screen Shot 2020-01-23 at 4 18 27 PM](https://user-images.githubusercontent.com/159399/73028890-17e29680-3dfc-11ea-86c2-f541d60b49e9.png)

**Comment by a-sassmannshausen** [comment]
One of my customers had this issue.  It was resolved after clearing the browser cache and restarting the browser.  Perhaps that is the same for you?

Alex
