### ISSUE TITLE
Wrong path to social icons in mailing and when pre-viewing in browser

### ISSUE THREAD

**Issue by thoni56** [veda-consulting/uk.co.vedaconsulting.mosaico#357]
When a mailing is previewed in the browser using "Preview" from the mailing list the social icons have incorrect URL:s. This happens for sent and non-sent mailings.

The URL used is (in Joomla): <root>/templates/versafix-1/img/social_def/facebook_bw_ok.png

but it really should be: <root>/media/civicrm/custom_ext/uk.co.vedaconsulting.mosaico/packages/mosaico/templates/versafix-1//img/social_def/facebook_bw_ok.png

This also propagates to the mails sent to users, the icons are not visible.

Don't know if this is Joomla-specific since the issue has been discussed (and fixed?) previously.

Using 2.3.1572289217 on CiviCRM 5.21.2 on Joomla 3.9.15

**Comment by thoni56** [comment]
This issue is still present in 2.5.1597918155.

**Comment by mattwire** [comment]
Closing following 2.6 release. Please reopen if still an issue

**Comment by thoni56** [comment]
I can't re-open this, but it is still present in 2.7..1621893607, both in mailing and in web view. Should I open a new issue? Will that make you fix it?

I have "patched" it in our installation creating a symbolic link from `/templates/versafix-1`  to `/media/civicrm/custom_ext/uk.co.vedaconsulting.mosaico/packages/mosaico/templates/versafix-1`. This at least fixes the web view.

The mailing still has incorrect icons though...
