### ISSUE TITLE
Images resized with poor quality

### ISSUE THREAD

**Issue by bsilvern** [veda-consulting/uk.co.vedaconsulting.mosaico#358]
Uploaded images are resized with poor quality due to the PHP function imagejpeg being called with a invalid "quality" parameter of NULL, where "quality" should be an integer, with 100 being the best quality.

The root of the problem is in CRM/Mosaico/Graphics/Intervention.php::createResizedImage at the line 
  `$img->save($destFile);`

That function, /vendor/intervention/image/src/Intervention/Image/Image.php::save, defaults the second parameter, "quality", to NULL.

That NULL value ultimately propagates to vendor/intervention/image/src/Intervention/Image/Gd/Encoder.php::processJpeg() which makes the call to imagejpeg with quality set to NULL.

Changing the line in Intervention.php to
  `$img->save($destFile, 100);`
produces much improved quality on uploaded images.

Recommendation: Make the quality value a configurable parameter, e.g. in civicrm.settings.php, with a default value of 90.

Tested on Mosaico 2.3.1572289217.

**Comment by mattwire** [comment]
@bsilvern Thankyou for investigating. I've just tested this and I'm not sure how it can be getting passed as NULL. Because there is a function in Intervention\Image which handles NULL and automatically sets it to 90: https://github.com/Intervention/image/blob/master/src/Intervention/Image/AbstractEncoder.php#L229-L243

**Comment by bsilvern** [comment]
I went back and looked at it again, and you are of course correct. I have no idea why I thought I saw imagejpeg callled with quantity = NULL. Sorry to have wasted your time, @mattwire.

Please consider though my suggestion to make quality configurable. What brought me here was an image that had unsatisfactory quality with the default quality value of 90. At 100 it was much improved. I'll be leaving my setting at 100 and patching it after each update.
