### ISSUE TITLE
ImageMagick not detected

### ISSUE THREAD

**Issue by axon-obriend** [veda-consulting/uk.co.vedaconsulting.mosaico#36]
![screen shot 2016-09-09 at 10 22 45](https://cloud.githubusercontent.com/assets/2123583/18396474/d93ddaaa-7691-11e6-801d-841565cf9e2f.png)

I've installed the mosaico extension alpha7 for a client (Wordpress 4.5.4/CiviCRM 4.7.9/php 5.6.25). The site is hosted on Siteground and I've added 
extension=imagick.so
to the php.ini file, as Siteground instructs. I've got another site hosted on Siteground (Drupal/CiviCRM 4.6.20) with the basically the same configuration except that alpha6 is installed that's not giving me a problem. I haven't found any stray php.ini's. I've tried installing alpha6 on the client getting the warning and I don't get the message on the dashboard, but I still see it when I'm using Mosaico.

ImageMagick is ImageMagick 6.9.4-5 Q16 x86_64 2016-05-31 and the module version is 3.4.2 per phpinfo() (screenshot attached).

Any idea why the warning is triggered?

**Comment by axon-obriend** [comment]
This may be the real culprit. When Mosaico alpha6 or alpha7 is enabled on CiviCRM 4.7, I get the error message

> Warning: Smarty error: unable to read resource: "CRM/common/wysiwyg.tpl" in <removed>/wp-content/plugins/civicrm/civicrm/packages/Smarty/Smarty.class.php on line 1094

This file is present on CiviCRM 4.6, but is not shipped with CiviCRM 4.7. It's got something to do with ckEditor
http://civicrm.stackexchange.com/questions/12012/ckeditor-is-undefined-when-form-is-being-loaded-in-model-frame-outside-of-civic/12034#12034

**Comment by deepak-srivastava** [comment]
@axon-obriend thanks. We looking into it. Will come back with findings.

**Comment by axon-obriend** [comment]
Downloaded the most recent copy with pull request #37 included and I'm still getting the warning about ImageMagick.

**Comment by deepak-srivastava** [comment]
@axon-obriend Yep, so tpl warning we fixed, but doesn't seem connected with imagemagick. The code that produces the warning is - https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/master/CRM/Mosaico/Page/Index.php#L14. You Might want to check along those lines - which one is failing and why.

**Comment by deepak-srivastava** [comment]
`if (!(extension_loaded('imagick') || class_exists("Imagick"))) {//Imagick not installed}`

So it's possible one is true while other is false as explained in http://stackoverflow.com/questions/1475830/why-would-a-loaded-php-extension-fail-on-class-instantiation.

In my setup for e.g i've also got extension loaded as:
```
deepak@thinkpad:/etc/php5/apache2/conf.d$ cat 20-imagick.ini 
; configuration for php imagick module
extension=imagick.so
```

**Comment by axon-obriend** [comment]
This code snippet
```
<?php
if (extension_loaded('imagick')) {
        echo "ImageMagick extension is available<br>";
} else {
        echo "ImageMagick NOT avaiable<br>";
}
if (class_exists('Imagick')) {
        echo "Imagick class exists<br>";
} else {
        echo "Imagick class DOES NOT exist<br>";
}
?>
```
Results in this output

> ImageMagick extension is available
> Imagick class exists

**Comment by axon-obriend** [comment]
Something's wrong with your if statement, I think
`if (!(extension_loaded('imagick') || class_exists("Imagick"))) {//Imagick not installed}`
The condition would be
`not (TRUE or TRUE)`
which would evaluate FALSE, meaning Imagick is NOT installed, when it actually is. I don't think you want to negate that condition.

**Comment by deepak-srivastava** [comment]
If you add your code to the extension in the same php file (somewhere on top inside run() method), are the results same?

**Comment by axon-obriend** [comment]
I put that code snipped inside the run() method and I'm getting

> ImageMagick NOT available
> Imagick class DOES NOT exist

I put a phpinfo.php file in the same directory
wp-content/uploads/civicrm/ext/uk.co.vedaconsulting.mosaico/CRM/Mosaico/Page
and it shows ImageMagick available.

**Comment by axon-obriend** [comment]
This is a hosting provider issue with Siteground. I had previously asked their support about enabling ImageMagick and they previously supplied an incomplete answer:

php.ini needs to be edited in the webroot to include
`extension=imagick.so`
** ALSO ** .htaccess needs to be edited to include the line
`SetEnv PHPRC /home/bio4clim/websites/sandbox.bio4climate.org/htdocs/php.ini`

**Comment by deepak-srivastava** [comment]
Cool, glad you figured it out. Closing this ticket now. Thanks.

**Comment by ivanask** [comment]
I am getting "Unexpected upload error" when trying to upload image in Email Template Builder.

Use case:
1) Environment: Hosted (Linux) website on SiteGround + Joomla + CiviCRM
Versions
PHP 7.0.29
Joomla! 3.8.6
CiviCRM 4.7.31

2) Installation/administration: I have read the post [Mosaico CiviCRM integration](https://civicrm.org/extensions/email-template-builder)
then manually downloaded and installed the following extensions:  CiviCRM Bootstrap theme and FlexMailer and installed (it's one of the listed extensions) the extension: Mosaico.

Applied the following being already stated in this post:
> php.ini needs to be edited in the webroot to include
> extension=imagick.so
> ** ALSO ** .htaccess needs to be edited to include the line
> SetEnv PHPRC /path/to/php.ini

Tried several PHP code snippets and running ImageMagick from a cron job:
`/usr/bin/convert public_html/image.jpg -resize 64x64 public_html/resize_image.jpg`
It is all working.

The error ImageMagick not installed is cleared from the Message Template Builder but within CiviCRM System Status I have the error "the ImageMagick library is not installed. The Email Template Builder extension will not work without it."
And I am getting "Unexpected upload error" when trying to upload image in Email Template Builder.
As a result I am not able to upload the image.
