### ISSUE TITLE
ts() problem in ang/crmMosaico/BlockSchedule.html

### ISSUE THREAD

**Issue by UshaMakoa** [veda-consulting/uk.co.vedaconsulting.mosaico#366]
I use the last mosaico version 
In transifex all strings are already translated in french.
https://www.transifex.com/civicrm/civicrm_extensions/translate/#fr/mosaico/170929245

The problem :

In the same file :
ang/crmMosaico/BlockSchedule.html

These lines are NOT translated in French :
```
<label class="crmMosaico-schedule-title">{{ts('Schedule email to:')}}</label>

<label for="schedule-send-at">{{ts('Send on..')}}</label>

```
This one is WELL translated :
`<label for="schedule-send-now">{{ts('Send immediately')}}</label>
`
I don't understand what's the difference.
Any idea ?

Thanks

PS : would it be possible to add these translations of the Mosaico UI directely in the extension ?
https://github.com/voidlabs/mosaico/tree/master/res/lang
in
uk.co.vedaconsulting.mosaico/packages/mosaico/res/lang 
?

**Comment by GuillaumeSorel** [comment]
I face exactly the same issue with this configuration Drupal 7.69 / CiviCRM 5.21.0 / latest version of Mosaico.
Improving the localization within CiviCRM is a real challenge and need!
Thanks for your commitment
Guillaume

**Comment by UshaMakoa** [comment]
Hi @mattwire Do you have any idea about this issue?

**Comment by mattwire** [comment]
Hi @UshaMakoa I don't know - could it be something to do with the ".." and ":" in the strings that is breaking it?

**Comment by UshaMakoa** [comment]
Thanks perhaps
@mlufty any idea ?

**Comment by UshaMakoa** [comment]
Thanks @mattwire

**Comment by mattwire** [comment]
@UshaMakoa It might not  be fixed but I wanted to close old issues. We will soon release a mosaico version with latest library so you will need to test that for translation issues.

**Comment by UshaMakoa** [comment]
ok could you please add the https://github.com/MAKOA-France/CiviVersafix-FR/tree/0.18.9 french version as a template and the dist/lang/mosaico-fr.json ? 

[mosaico-fr.zip](https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/files/11314294/mosaico-fr.zip)
