### ISSUE TITLE
Mosaico Sharing block is not working 

### ISSUE THREAD

**Issue by agileware-ash** [veda-consulting/uk.co.vedaconsulting.mosaico#372]
Hello, 

When I try to use the sharing block on the template - it is not working properly. 

-  Facebook share block shows an error message "href should represent a valid URL"

- Twitter share link: Comes up with blank twitter field

- LinkedIn share link: Not sure. Comes up with login page but we haven’t been able to test further.

Cheers,
Ashwin

**Comment by agileware-justin** [comment]
Agileware Ref: CIVIMOSAIC-33

**Comment by agileware-pengyi** [comment]
This can be closed.
The block is not in the extension. To have this, the Mosaico package needs to be updated.

**Comment by netzih** [comment]
I am not sure if I should open a new issue, But I am seeing this block in the extension and having the same issue as OP
Am I missing something?
