### ISSUE TITLE
Can't drag-drop or add image

### ISSUE THREAD

**Issue by twomice** [veda-consulting/uk.co.vedaconsulting.mosaico#373]
With uk.co.vedaconsulting.mosaico version 2.3.1572289217:

When I attempt to add an image to a mailing, I'm now seeing the strange behavior shown in the below animated gif.
![bad-behavior](https://user-images.githubusercontent.com/759449/80239997-c928e080-8626-11ea-91e1-e5a2f820d1cf.gif)

Basically, something seems to be wrong with the styling of the hover area for the images, such that the mouse can never reach the upload button nor the "drop" area.

After observing this bad behavior, I have tried all of the following steps in order, each time reloading the mailing in the browser and checking again for proper behavior, and at no point have I yet been able to observe correct behavior:

1. Verified that php-imagick is installed on this system (although I'm not certain that's even a requirement anymore)
1. `cv flush; wp cache flush`
2. Upgraded CiviCRM from 5.19.4 to 5.42.3; then `cv flush; wp cache flush`
3. Deactivated all WordPress plugins other than civicrm; then `cv flush; wp cache flush`
4. Uninstalled all CiviCRM extensions other than flexmailer and mosaico; then `cv flush; wp cache flush`
5. Uninstalled flexmailer and mosaico, deleted the files from the local drive for both of them, and re-installed in-app by clicking "download and install"; then `cv flush; wp cache flush`

For reference, I expected to see functionality something like this (taken from another site with the same mosaico version):
![good-behavior](https://user-images.githubusercontent.com/759449/80239938-ae566c00-8626-11ea-8053-b3679db7415a.gif)

What else could I try to get this to work?

**Comment by martst** [comment]
I have the same problem with my Joomla+CiviCRM system. 
The img block is created with the following line:
`<img width="258" vspace="0" hspace="0" border="0" alt="" data-bind="virtualAttrStyle: 'width: 100%; '+'max-width: '+(imageWidth()+'px')+';'+'', virtualAttr: { alt: image().alt(), width: imageWidth() }, wysiwygSrc: { width: imageWidth() , height: null, src: image().src, placeholder: { width: imageWidth() , height: 150, text: 'w'+imageWidth() +''} }" style="width: 100%; max-width: 258px;" src="https://www.xxx.xxx.xxx/index.php?option=com_civicrm&amp;task=civicrm/mosaico/img&amp;method=placeholder&amp;params=258%2C150">`
but if I hover over this line in the console it show img 0x0. If this the problem or something else ?

**Comment by francescbassas** [comment]
Apparently identic issue has discussed here https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/186. Probably something wrong with your imagick installation. In my case it was this https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/186#issuecomment-459798376.

Alternatively Mosaico can also work with GD library. Have you tried playing with the "Mosaico graphics driver" setting on Mosaico settings page at /civicrm/admin/mosaico?

This problem has also been discussed on SE [Failed to locate Mosaico graphics driver](https://civicrm.stackexchange.com/questions/30856/failed-to-locate-mosaico-graphics-driver).

**Comment by martst** [comment]
I don't believe this problem is the same as #186 as the problem appears before anything is done with images. The beginning of the animated Gif shows it is not possible to drop the image as the drop area is too small.

**Comment by francescbassas** [comment]
@martst I wouldn't be so sure. Precisely you say 

> in the console it show img 0x0

The "Drop an image here" image could not be generated and instead is a 0x0 region where it is not possible to do the drag & drop action.

**Comment by twomice** [comment]
The patch in [this comment](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/292#issuecomment-497709542) in issue #292 solves my issue.

@martst , if the above patch does not solve your issue, perhaps you have a different problem and might consider a separate ticket.

@veda-consulting Any thoughts on how @deepak-srivastava 's patch fits in here, and whether it could be merged to master for future releases?

**Comment by martst** [comment]
@twomice , Thanks for the pointer. I tried the patch but there is no change in the display. I have also checked imagick and GD again and can't find any issues so it must be a different problem. I will keep debugging the issue.

**Comment by twomice** [comment]
Thanks for confirming, @martst . I do recommend opening a separate issue to track your situation and solution. Best luck!

**Comment by mattwire** [comment]
@twomice Is this fixed in 2.5?

**Comment by twomice** [comment]
@mattwire Considering that this issue is fickle (per OP, it happens on one site with certain versions, and not on another site with the same versions), and considering we've fixed it with a patch (per [my comment above](https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/issues/373#issuecomment-620071719)) I'm not confident I can repeat the issue, and thus not confident to verify that it's fixed in 2.5. From what you know of the code changes represented by #367 and #348, would you expect that the relevant patch has been incorporated in 2.5?

**Comment by bkaless** [comment]
In my case the installation of php7.3-gd solved my problem, because I forgot this installation when changing from php7.2 to php7.3.

**Comment by aydun** [comment]
If you're not seeing the placeholder images, check your browser's developer tools to see what url is being requested and the response.

**Comment by twomice** [comment]
My experience indicates that the issue in my OP is resolved without patches in version 2.5. I'll close this now, but please feel free to re-open if the OP issue is not resolved for you in 2.5.
