### ISSUE TITLE
Link to an anchor on same page changes

### ISSUE THREAD

**Issue by aarded** [veda-consulting/uk.co.vedaconsulting.mosaico#380]
We are using CiviMail with mails created by Mozaico.
We want to create a content table into the email with an anchor to the corresponding topic. 
The code below works fine into a html page:

```
Content:<br>
- <a href="#topic1">Title topic one</a><br>
- <a href="#topic2">Title topic two</a><br>
- <a href="#topic3">Title topic three</a><br>
- <a href="#topic4">Title topic four</a></p>
```

However, used with CiviMail, after the email is send, the references #topic1, #topic2, #topic3 and #topic4 are replaced into the received email by external links, in something like _href="https://crm.xxxxxxxx.yy/sites/all/modules/civicrm/extern/url.php?u=1234&amp;qid=56789"_
And these are not working (page not found).
Am I doing something wrong? How can I set a link to an anchor on same page? A link to an anchor on another page is working fine.

Tnx.

**Comment by mattwire** [comment]
This is probably a local configuration issue. If it is still a problem please try the ~dev-mosaico channel at http://chat.civicrm.org or https://civicrm.stackexchange.com
