### ISSUE TITLE
Problem after installing version 2.5

### ISSUE THREAD

**Issue by oschopfer** [veda-consulting/uk.co.vedaconsulting.mosaico#395]
I upgraded from 2.4 to 2.5 today.
I'm getting the message "Mosaico cannot be displayed because this system does not meet all requirements"

In the details, here is the message:
"Mosaico requires dependencies in its "packages" folder. Please consult the README.md for current installation instructions."

I tried clearing all possibles caches, it didn't solve the problem.

What can I do?

I'm runing CiviCRM 5.26.2 on Drupal 7.

**Comment by tapashdatta** [comment]
@oschopfer I am also having the same issue after upgrading. I have experienced this before as well when upgraded directly from within CiviCRM. 
I had solve this by downloading the package manually from https://civicrm.org/extensions/email-template-builder
It appears v2.5 is yet to be listed on CiviCRM extension site.

**Comment by mattwire** [comment]
Sorry! The extension publisher made it available before it was built. That's now fixed and the download for 2.5 will work. If you already downloaded please download again.

**Comment by oschopfer** [comment]
Thank you, everything fine.
