### ISSUE TITLE
Packages are missing - 2.5

### ISSUE THREAD

**Issue by Dubidubiduu** [veda-consulting/uk.co.vedaconsulting.mosaico#396]
Upgraded to Mosaico (uk.co.vedaconsulting.mosaico) version 2.5, then upgraded Civi to 5.28.2 and Wordpress 5.5. 

So I get:

> Mosaico: Packages are missing
> Mosaico requires dependencies in its "packages" folder. Please consult the README.md for current installation instructions.

Having a look at README.md, it states:

> ## Compatibility / Requirements
> * CiviCRM 5.24+
> * PHP-ImageMagick - recommended.
> * [FlexMailer](https://docs.civicrm.org/flexmailer/en/latest/) 1.1+

but at wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Fextensions&reset=1 I have

> FlexMailer(org.civicrm.flexmailer) | Aktiviert | 1.1.1

So, what to do?

**Comment by mattwire** [comment]
Sorry! The extension publisher released it before it had built. It is now fixed. If you already downloaded please download again via https://civicrm.org/extensions/email-template-builder
