### ISSUE TITLE
packages directory missing?

### ISSUE THREAD

**Issue by mwestergaard** [veda-consulting/uk.co.vedaconsulting.mosaico#399]
Trying 2.5 on a test box, I received "Packages are missing" error. I see that check is in mosaico.php for verifying existence of files in the packages directory, but I don't see a packages directory in 2.5. I copied it from a previous version and all seems well.

**Comment by mattwire** [comment]
Please download 2.5 again. There was a brief period (24 hours) where 2.5 was available but missing packages.

**Comment by mwestergaard** [comment]
@mattwire Thanks for the speedy response. I guess I am still missing something. I cloned the 2.5 repository and I don't see two directories that are on my production system that is still at 2.3.1572289217: "packages" and "vendor".

**Comment by mattwire** [comment]
You need to download the extension from here where the pre-built zip file contains the packages https://civicrm.org/extensions/email-template-builder - this is also where the in-app installer gets it from. If you wish to clone the repository you must follow the instructions to to build the packages yourself: https://docs.civicrm.org/mosaico/en/latest/develop/

**Comment by mwestergaard** [comment]
Thanks, I wasn't thinking. After the first issue, I thought I'd be clever and go straight to the source.
