### ISSUE TITLE
Saving draft results in "Leave site?" warning

### ISSUE THREAD

**Issue by larssandergreen** [veda-consulting/uk.co.vedaconsulting.mosaico#400]
After editing the content of a message, clicking Save draft results in a browser pop-up warning that says "Leave site? Changes you made may not be saved" with Cancel and Leave buttons. Clicking Leave still results in the mailing being saved, so the warning is incorrect. 
Seems to have started in 2.5. Happens in Chrome and Safari. CiviCRM 5.28.3 on Drupal 7.

**Comment by larssandergreen** [comment]
This also happens after editing the Mosaico Templates. Edit a template on the Mosaico Templates page, save the edits, then try to close the tab and Chrome gives a Changes may not be saved message.

**Comment by totten** [comment]
Another/similar symptom observed in Firefox 76 / macOS / D7 -- after submitting a mailing, your're done, so it does a redirect to the list of mailings. The redirect shows an extra nag to confirm that you want to navigate away.

Reverting #391 (from #319) locally fixes this problem... but obviously then there's no warning warning if you accidentally navigate away.

I haven't tested the flows mentioned above, but I suspect it's the same issue -- that the `onbeforeunload` needs to be more nuanced.

**Comment by mattwire** [comment]
@larssg-wildsight To fix this we'd need either some funding to write a fix (which should be a simple case of nuancing the `window.onbeforeunload` as you say or for you/someone to submit a pull request to fix the issue. Based on what you've said, that it affects templates and the cancel button it's probably less than an hour to develop a fix.

**Comment by larssandergreen** [comment]
I have submitted #409, which fixes this issue. We've been using this without issue.

**Comment by seamuslee001** [comment]
I see that 409 has been merged is there anything more needed?

**Comment by larssandergreen** [comment]
No, this is sorted now. Closing.
