### ISSUE TITLE
Getting a 'page not found' error when I click the desired template in a new mailing.

### ISSUE THREAD

**Issue by HeneryH** [veda-consulting/uk.co.vedaconsulting.mosaico#408]
This is my first new mailing (I installed the mosaico ext already).
When I click the desired template (versafix-1) I go to a blank page not found page
`http://<mydomain>/civicrm/a/#/mailing/2`
This was the second attempt, hence the /2.

Any ideas?

**Comment by HeneryH** [comment]
Oh, sorry. Drupal 8 and Civi 5.31-dev
Version 2.5.1597918155 downloaded from the Civi UI as per the instructions.

**Comment by HeneryH** [comment]
Should these directory exist after installation?  Mine don't.
```
Mosaico Custom Templates Directory = [civicrm.files]/mosaico_tpl
Mosaico Custom Templates URL = [civicrm.files]/mosaico_tpl
```
```
./web/sites/default/files/civicrm$ ls -la
total 32
drwxr-xr-x  8 www-data  www-data 4096 Nov 18 11:14 .
drwxrwx---  8 webmaster www-data 4096 Nov 18 11:13 ..
drwxr-xr-x  2 www-data  www-data 4096 Nov 18 11:14 ConfigAndLog
drwxr-xr-x  2 www-data  www-data 4096 Nov 18 11:14 custom
drwxr-xr-x 17 www-data  www-data 4096 Nov 18 13:37 ext
drwxr-xr-x  3 www-data  www-data 4096 Nov 18 11:14 persist
drwxrwxrwx  3 www-data  www-data 4096 Nov 18 14:50 templates_c
drwxr-xr-x  3 www-data  www-data 4096 Nov 18 11:14 upload
```

**Comment by eileenmcnaughton** [comment]
Sometimes with angular a blank page is a delayed page & it loads if you wait. If it's broken there are usually js errors you can find by inspecting in your browser

**Comment by HeneryH** [comment]
Bingo on the diagnosis...
`Failed to load resource: the server responded with a status of 404 (Not Found)
DevTools failed to load SourceMap: Could not load content for http://<mydomain>/libraries/civicrm/core/bower_components/angular/angular.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by HeneryH** [comment]
Hmm... the library is there but no .map file.  Where would that come from?
```
./web/libraries/civicrm/core/bower_components/angular$ ls -la
total 1536
drwxrwxr-x  2 webmaster webmaster    4096 Nov 18 16:30 .
drwxrwxr-x 35 webmaster webmaster    4096 Nov 18 16:30 ..
-rw-rw-r--  1 webmaster webmaster     343 Nov 18 16:30 angular-csp.css
-rw-rw-r--  1 webmaster webmaster 1374778 Nov 18 16:30 angular.js
-rw-rw-r--  1 webmaster webmaster  176531 Nov 18 16:30 angular.min.js
-rw-rw-r--  1 webmaster webmaster      48 Nov 18 16:30 index.js
```

**Comment by eileenmcnaughton** [comment]
Hmm - I have it on my install - I wonder if d8 somehow didn't generate it - @seamuslee001 any idea? (if you want to get the file right now I think you can download a tarball & copy it from there)

**Comment by seamuslee001** [comment]
something in the composer downloads might be ignoring it but I would say the missing .map file won't be your problem (map files just help browsers pretty print minified js)

**Comment by HeneryH** [comment]
I’ll take a look when I get home. I have another VM that was working fine
that was built last week.

**Comment by HeneryH** [comment]
You're right @seamuslee001 .  That error went away when I added the map file and now I am left with a simple page not found 404.

The error messages I posted in posts 1 and 4 are two errors: the one as you suggested which is insignificant and the second simple 404.

Not much to go on.

**Comment by HeneryH** [comment]
Did anything meaningful change in the last week?

**Comment by HeneryH** [comment]
Very very strange...   I happened to be on the demo site to poke around the API Explorer and in seeing that they were running on a newer version (and perhaps more unstable) than my 5.31-dev I decided to do an upgrade to 5.32-dev.

Now the Mosaic mailer works.

I can't explain it but will leave this here in case anyone else runs into it.
