### ISSUE TITLE
Missing image in mailing

### ISSUE THREAD

**Issue by mikantchap** [veda-consulting/uk.co.vedaconsulting.mosaico#424]
We have a mailing that somehow includes an image path such as:

sites/default/files/civicrm/persist/contribute/images/uploads/static/CC_Mosaico_graphic_1_3cdb88214d1f5f4ea2b0cce19ba344c2.png

This is not added manually, and we can't see where is comes from.

In Thunderbird it results in a large unsightly placeholder block.

Mosaico 2.5.1597918155
Civi 5.28.2
Drupal  7.75

**Comment by mattwire** [comment]
Closing following 2.6 release. Please reopen if still an issue

**Comment by mikantchap** [comment]
2.6 hasn't solved it. Have you any idea of the origin of this file? Can we safely remove the img tag from the template by editing the db?

Don't know how to re-open an issue btw. @mattwire

**Comment by francescbassas** [comment]
This image path seems an upload image from Mosaico editor. I don't quite understand the problem. Is it a specific problem? Are you able to reproduce it? Maybe you can complete your description with images and steps to reproduce for others can help you.

**Comment by mikantchap** [comment]
The image isn't there to edit (and hasn't been uploaded). Its like Mosaico has added a table, containing a table, containing a fictitious image.
Maybe https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/issues/348 ?
I'm going to try editing the templates in the db.

**Comment by mattwire** [comment]
Please re-open if still an issue on mosaico 3.1
