### ISSUE TITLE
If the number of groups and mailings for recipients is greater than 25, the list is silently truncated

### ISSUE THREAD

**Issue by larssandergreen** [veda-consulting/uk.co.vedaconsulting.mosaico#428]
There is a limit of 25 for the number of groups or mailings you can include or exclude from a mailing. That's a not a problem, but there is no warning or message when you exceed the number of groups. They are just silently reduced to 25 if you go to the next page and return or save and exit. Ideally, there would be some kind of notification as the user wouldn't be likely to notice that the list had been truncated or may not look at that page again before sending the mailing.

Obviously not that common of a problem, but I thought I should at least report it here so people can find this in the future.

**Comment by eileenmcnaughton** [comment]
Oh - that signals an api v3 call without the param ['options' => ['limit' => 0]]

without that it defaults to 25

I don't suppose you have identified the call?

**Comment by larssandergreen** [comment]
@eileenmcnaughton Sorry, I haven't.

**Comment by bhahumanists** [comment]
This one, possibly? https://github.com/civicrm/civicrm-core/blob/52817fca33c632c65e52afba8b0848bc065aebd4/ang/crmMailing/services.js#L130

**Comment by larssandergreen** [comment]
That looks like it, thanks!
I will try that out.

**Comment by larssandergreen** [comment]
[Fixed in core.](https://lab.civicrm.org/dev/core/-/issues/2539) Thanks @bhahumanists
