### ISSUE TITLE
 PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/vhosts/xxx/web/sites/default/files/civicrm/ext/uk.co.vedaconsulting.mosaico/mosaico.civix.php on line 247

### ISSUE THREAD

**Issue by Rar9** [veda-consulting/uk.co.vedaconsulting.mosaico#429]
With drupal 9 php 7.4x im getting with upgrade to civicrm 5.34

PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/vhosts/xxx/web/sites/default/files/civicrm/ext/uk.co.vedaconsulting.mosaico/mosaico.civix.php on line 247

**Comment by mattwire** [comment]
Fixed via https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/pull/426 and will be in Mosaico 2.7

**Comment by Rar9** [comment]
Thanks Any ETA?

**Comment by seamuslee001** [comment]
2.7 was released in may so I think this can be closed

**Comment by mattwire** [comment]
This is actually fixed in 2.8 which will be released tomorrow
