### ISSUE TITLE
Does this need Flexmailer extension requirement?

### ISSUE THREAD

**Issue by loganbear** [veda-consulting/uk.co.vedaconsulting.mosaico#432]
With Flexmailer now part of core, does the extension still need to be a requirement?  Couldn't this extension use the Flexmailer in core, especially since the extension in github is now frozen and archived?

**Comment by eileenmcnaughton** [comment]
@loganbear yes it does require 'a' flexmailer extension - preferably the one in core - but people do need to have that enabled. Are you looking at some docs that are unclear?

**Comment by loganbear** [comment]
How do you get mosaico to use the module in core?  The one that gets enabled when enabling mosaico comes from https://github.com/civicrm/org.civicrm.flexmailer which is archived in github.  And you can't disable that extension, because you're told that mosaico requires it.
--

**Comment by eileenmcnaughton** [comment]
@loganbear are you saying it downloads that extension? Or that it uses it if already downloaded?

**Comment by loganbear** [comment]
Okay - I had to disable/uninstall/delete the code on my extension directory in order for mosaico to recognize flexmailer that is in core.  Now it's looking at the core Flexmailer.  Thank you for your help.

**Comment by eileenmcnaughton** [comment]
@loganbear yay
