### ISSUE TITLE
 permission to delete templates?

### ISSUE THREAD

**Issue by CsarRamos** [veda-consulting/uk.co.vedaconsulting.mosaico#436]
Hello, I'm testing mosaico templates cannot be deleted unless I have permission to administer CiviCRM, does anyone know if there is another permission? Or could an improvement be considered? 

Thanks!

**Comment by CsarRamos** [comment]
Hi, I have found how to do it with the CiviCRM api permission hooks, I have created an extension to delete templates depending on a permission along with other functionalities. If you have any suggestions please let me know.

CiviCRM Extension: https://civicrm.org/extensions/mosaico-extras

**Comment by andyburnsco** [comment]
Ideally I think this ought to look at "delete in civimail" permission
