### ISSUE TITLE
Autosave - possible Make it Happen?

### ISSUE THREAD

**Issue by larssandergreen** [veda-consulting/uk.co.vedaconsulting.mosaico#444]
I think quite a few folks have run into frustrations with lost work in Mosaico mailings. Some work has been done to prevent users from clicking away by accident, but I think an autosave feature that saves the mailing as you work would probably be very helpful for many (and is becoming pretty standard these days, so users are frustrated to find that Mosaico doesn't do this).

Would someone be willing to take this on? Does anyone have a rough sense of how much work this would be? If it is reasonable, I think this could be a fundable Make it Happen. We would certainly kick in for this and there is at least one other [org who are interested](https://civicrm.stackexchange.com/questions/38675/auto-save-mailing-editing-template-in-mosaico). This is probably the biggest problem we have with CiviCRM in our org right now and I'm sure we're not alone.

Depending on how big of a project this is, it could possibly also be combined with work in core to lock mailings when they are being edited by another user or at least to warn that another user has a mailing open for editing, [as I've suggested here.](https://lab.civicrm.org/dev/mail/-/issues/85). Together, I think these two improvements would save a couple days of staff time per year in our org alone.

**Comment by mattwire** [comment]
This is probably of interest to @bhahumanists as well. Autosave already works on the template editor I think? In order to implement and test this properly I would estimate between 4-8 hours work. If setting up a Make it Happen it would probably be a good idea to extend the scope (ie. +10-16 hours) to upgrade the mosaico library to latest version as well.

**Comment by larssandergreen** [comment]
That seems reasonable. We might even just be able to skip the Make it Happen and just do the autosave itself split between a few orgs. Can you share a cost estimate in dollars? Email is in my profile here if you prefer.

**Comment by mattwire** [comment]
@larssandergreen Thankyou I have sent you an email

**Comment by petednz** [comment]
i would chip in to help

**Comment by larssandergreen** [comment]
@petednz Great! Matt is going to scope this soon and then I'll get the MiH up.

**Comment by petednz** [comment]
@mattwire any idea on timeframe for this?

**Comment by mattwire** [comment]
> 1) Auto-save in Mosaico editor
> Prominent, persistent warning if auto-save stops working, recommending closing and re-opening the editor

MJW:
Currently autosave is not implemented. CiviCRM core has an implementation of "autosave" in the angular `CrmAutosaveCtrl` control - that autosaves the mailing details (every 5 minutes) but not the mosaico editor changes - they are only saved when you click close or test.
To implement an autosave that handles the mosaico part we'll need to implement an instance of the `CRMAutoSaveCtrl` via a mosaico plugin that understands how to save changes from the mosaico editor.

> 2) Warning when attempting to edit mailing that another user is editing, thinking this is in core as it applies equally to all types of mailing
> Not sure the best way to implement this, but these are just rough thoughts:
> User starts editing mailing -> flag is set with time
> User saves any changes -> flag is updated with time
> User saves and exits -> flag is unset
> User tries to edit mailing that has active flag -> check time, if less than some reasonable time in the past (maybe 30-60 minutes) then pop-up warning/confirmation: It looks like another user is editing this mailing and you will lose saved changes if you both edit at the same time. Are you sure you want to edit this mailing?

Relatedly, I also have seen that sometimes if someone leaves a Mosaico mailing editor open and then opens another for the same mailing in another window, they aren't able to save in the new window. If that's closely related, maybe it's something that could be dealt with at the same time as autosave? Not a high priority, I don't think, so only if it makes sense.Hi Lars,

MJW:
Currently the "Mailing has not been saved, Content maybe out of date, please refresh the page and try again" message is triggered based on the modified_date field in the civicrm_mailing table. Each time the mailing is "saved" the modified_date is checked and then updated. So if one active window "saves" the mailing it gets the updated modified_date and other windows cannot save.
Leaving the mosaico editor open and opening in another window is virtually the same thing technically so makes sense to resolve at the same time.

Proposed solution is to:
Add a new field "editor_id" which is updated to contain the contact_id of the user that is editing the mailing.
- When the user finishes editing clear the editor_id field.
- When another user tries to edit the mailing check the "editor_id" field is empty or the modified_date is greater than 30-60 minutes.
- If the mailing is being edited by another user display a message with the name of that contact and ask if you want to edit anyway.
- If the mailing is being edited and you try to save but the editor_id has changed display a message saying "the message is being edited by {contact name} - if you save you will overwrite their changes".

**Comment by petednz** [comment]
@mattwire @larssandergreen was there any further discussion on this?

**Comment by nc3man** [comment]
Our organization is also very interested in this. Please let us know how we may contribute. @petednz @mattwire @larssandergreen

**Comment by mattwire** [comment]
See https://civicrm.org/make-it-happen/mosaico-autosave

**Comment by colemanw** [comment]
Work is underway: see https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/pull/471

**Comment by totten** [comment]
I'm curious if anyone here (and also @seamuslee001 @monishdeb) has feedback on a fiddly aspect of autosaving.

When storing a Mosaico composition, we store both a JSON representation and an HTML representation. Exporting the HTML representation is moderately expensive (eg 200-300ms on an i3-10100) and must be executed in the browser's main UI thread. If you export HTML while the user is interacting with the editor, it can create funny effects (eg the drag/drop feels more jittery).

I've opened two PRs, which use different strategies to work around this:

* #471 fires the `sync` method with a fixed schedule (*eg every 1,000ms*). To avoid `exportHTML()` issues, it simply does not call `exportHTML()`. Instead, it allows the HTML to grow stale - and later repairs the HTML when the user clicks "Save" or "Test". (Allowing the system to save stale HTML creates some more edge-cases; the PR discussion identifies other steps needed to address those edge-cases.)
* #472 fires the `sync` method after a moderate period of idleness (*eg 4,000ms*) or after an extended period of activity (*eg 90,000ms*). It saves a complete record (both HTML+JSON), so it avoids the obvious issues with #471. However, the schedule is less predictable, and it periodically emits a JS console warning.

**Comment by mattwire** [comment]
This got implemented in an earlier 2.x release

**Comment by petednz** [comment]
thx for updating here. any implications on size of log tables or have you managed to avoid that type of bloat?

**Comment by MegaphoneJon** [comment]
@petednz It definitely adds to log table size.  OTOH - I've used the log tables to establish that at no point did someone change a token that they claimed they did.
