### ISSUE TITLE
DEFAULT_AVATAR_SIZE undefined constant - error logs filling with PHP warnings

### ISSUE THREAD

**Issue by nc3man** [veda-consulting/uk.co.vedaconsulting.mosaico#448]
We are running Civi 5.33.4 ESR on Wordpress 5.7.1, with Mosaico 2.6.1610013608, PHP 7.3. We were having problems with saving a Mosaico mailer (possibly some Wordfence conflict or blocking but that's another issue), so we were examining our site logs. Our logs are filling daily with this message:
`[Tue Apr 27 10:32:29.159085 2021] [fcgid:warn] [pid 4756:tid 140109684930304] [client 75.80.40.13:62976] mod_fcgid: stderr: PHP Warning:  Use of undefined constant DEFAULT_AVATAR_SIZE - assumed 'DEFAULT_AVATAR_SIZE' (this will throw an Error in a future version of PHP) in /home/karrud1/sdbikecoalition/wp-content/plugins/wp-civi-mosaico-master/civicrm_php/CRM/WpCiviMosaico/Utils.php on line 115, referer: https://sdbikecoalition.org/wp-admin/admin.php?page=CiviCRM&q=civicrm/mosaico/iframe&snippet=1`

 Sounds like a simple fix for someone familiar with the code and should be done anticipating PHP evolution. Thnx.

**Comment by seamuslee001** [comment]
This looks like related to a custom Utils file not connected to this extension
