### ISSUE TITLE
How to add new socials to the social block

### ISSUE THREAD

**Issue by eth4ever** [veda-consulting/uk.co.vedaconsulting.mosaico#459]
The TikTok social button is not available in de predefined socials of the Mosaico social block. Is there a way to add other predefined buttons in the footer like TikTok?

**Comment by eth4ever** [comment]
The work around I found was to change the images of Google+ (doesn't excist any more) for the image op TikTok.
The images are found here: sites/default/files/civicrm/ext/uk.co.vedaconsulting.mosaico/packages/mosaico/templates/versafix-1/img/social_def/
The google+ images are: google+_ok.png (colored image) and google+_bw_ok.png (black and white image).

**Comment by MegaphoneJon** [comment]
Thank you for sharing this workaround, I'd been thinking about this myself recently.
