### ISSUE TITLE
add fr.json

### ISSUE THREAD

**Issue by dev-allinappli** [veda-consulting/uk.co.vedaconsulting.mosaico#460]
Could you add this file for French in `/packages/mosaico/dist/lang` instead of the one provided by default that is not correctly translated?

[mosaico-fr.json.zip](https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/files/6710518/mosaico-fr.json.zip)

**Comment by mattwire** [comment]
Please re-open if still an issue on mosaico 3.1
