### ISSUE TITLE
Setting to hide base templates not working in WordPress?

### ISSUE THREAD

**Issue by themak1985** [veda-consulting/uk.co.vedaconsulting.mosaico#464]
Hi there,

This is low priority, but if I hide even one template, I no longer have access to any of my templates (base or otherwise) and the mosaico templates screen is blank. Only error I could find using dev tools is:

```
angular.js:15697 TypeError: Cannot read property 'title' of undefined
    at filterTemplate (angular-modules.304309a9b179c7ab6f8557b610a15c88.js:3984)
    at Yt (lodash.min.js:10)
    at Function.Ce (lodash.min.js:38)
    at angular-modules.304309a9b179c7ab6f8557b610a15c88.js:3997
    at angular.js:18075
    at m.$digest (angular.js:19242)
    at angular.js:19562
    at Yg.completeTask (angular.js:21403)
    at angular.js:6879 "Possibly unhandled rejection: {}"
```
The issue is only on WordPress, on my drupal site, this works as intended.

**Comment by mattwire** [comment]
@themak1985 For clarity - what CMS does this *not* work on?

**Comment by themak1985** [comment]
Updated, sorry about that.  It is on my wordpress site.

**Comment by themak1985** [comment]
Now nothing is working.

**Comment by themak1985** [comment]
![Screen Shot 2021-07-14 at 7 53 51 PM](https://user-images.githubusercontent.com/28904266/125707215-386e7409-0c9a-42c6-a85f-69cbfecf2d7b.png)
![Screen Shot 2021-07-14 at 7 53 20 PM](https://user-images.githubusercontent.com/28904266/125707216-6814fcd4-ca43-496b-ad86-61158d2dd8a8.png)

**Comment by themak1985** [comment]
I figured out problem - it was somehow related to a custom template we had (civiversafix) we removed folder and database entry from civicrm_mosaico_template and then all worked just fine.
