### ISSUE TITLE
Trying To Trouble Shoot Blank Screen - Security Issue?

### ISSUE THREAD

**Issue by themak1985** [veda-consulting/uk.co.vedaconsulting.mosaico#466]
I can't get any of the mosaico screens (block editor) to load - Drupal 8, Civi 5.38 - I see this in Dev tools and not sure how to fix it.

`Mixed Content: The page at 'https://example.org/civicrm/a/#/mailing/37' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://example.org/sites/default/files/civicrm/ext/uk.co.vedaconsulting.mosaico/packages/mosaico/templates/versafix-1/template-versafix-1.html'. This request has been blocked; the content must be served over HTTPS.`

**Comment by themak1985** [comment]
This could be related to #457

**Comment by mattwire** [comment]
This sounds like a local configuration issue rather than a mosaico problem.

**Comment by MegaphoneJon** [comment]
Check `CIVICRM_BASE_URL` in `civicrm.settings.php` and make sure it's https.  You can also likely configure your web server to redirect all requests to HTTPS.
