### ISSUE TITLE
Misaligned block and not rounded corners on Outlook desktop

### ISSUE THREAD

**Issue by Stoob** [veda-consulting/uk.co.vedaconsulting.mosaico#467]
Microsoft O365 for Desktop 16.0.14326 on a Windows 10 PC this is a new phenomenon we see:

Civi 5.40.2 using Mosaico extension vers 2.7.1621893607

- the 534x200 block specifically is always incorrect width, regardless of image size uploaded
- the buttons have no round radius

Wondering if this is a new issue?  Anyone else seen?  What is the fix? (images below)
![block-mosaico](https://user-images.githubusercontent.com/1683473/134545128-f2a28f4e-579b-4444-892c-23da6e219a94.png)

![4354535](https://user-images.githubusercontent.com/1683473/134545915-7ea51e50-49aa-43fb-83da-1dc991cd3b36.png)

**Comment by Stoob** [comment]
Just confirming again on a different site that this is an issue, although somewhat different manifestation, it is misaligned within the block not outside (below). I have noticed for what it is worth that Outlook is mistreating the buttons and failing to respect their border radius not just from Mosaico but from other mail sources, such as Nextdoor.com.

![misalign](https://user-images.githubusercontent.com/1683473/135656721-55ab9e91-5176-409c-a2d6-85210b4fe15c.png)

**Comment by mattwire** [comment]
Please re-open if still an issue on mosaico 3.1
