### ISSUE TITLE
Upgrade to 2.8 fatal error

### ISSUE THREAD

**Issue by cdhassell** [veda-consulting/uk.co.vedaconsulting.mosaico#475]
I clicked the link in the Extensions page to upgrade the Mosaico extension to version 2.8 and got a popup reading "DB error: Unknown error".  The debug log output is below. This is on Wordpress 5.8.2, Civicrm 5.43.0, PHP 7.3.32. 

Nov 20 02:39:43  [error] $Fatal Error Details = Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => exceptionHandler
        )

    [code] => -1
    [message] => DB Error: unknown error
    [mode] => 16
    [debug_info] => 
    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255))
      RETURNS VARCHAR(255)
      DETERMINISTIC
      NO SQL
    BEGIN
      DECLARE output   VARCHAR(255) DEFAULT '';
      DECLARE iterator INT          DEFAULT 1;
      WHILE iterator < (LENGTH(input) + 1) DO
        IF SUBSTRING(input, iterator, 1) IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9') THEN
          SET output = CONCAT(output, SUBSTRING(input, iterator, 1));
        END IF;
        SET iterator = iterator + 1;
      END WHILE;
      RETURN output;
    END [nativecode=1419 ** You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)]
    [type] => DB_Error
    [user_info] => 
    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255))
      RETURNS VARCHAR(255)
      DETERMINISTIC
      NO SQL
    BEGIN
      DECLARE output   VARCHAR(255) DEFAULT '';
      DECLARE iterator INT          DEFAULT 1;
      WHILE iterator < (LENGTH(input) + 1) DO
        IF SUBSTRING(input, iterator, 1) IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9') THEN
          SET output = CONCAT(output, SUBSTRING(input, iterator, 1));
        END IF;
        SET iterator = iterator + 1;
      END WHILE;
      RETURN output;
    END [nativecode=1419 ** You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)]
    [to_string] => [db_error: message="DB Error: unknown error" code=-1 mode=callback callback=CRM_Core_Error::exceptionHandler prefix="" info="
    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255))
      RETURNS VARCHAR(255)
      DETERMINISTIC
      NO SQL
    BEGIN
      DECLARE output   VARCHAR(255) DEFAULT '';
      DECLARE iterator INT          DEFAULT 1;
      WHILE iterator < (LENGTH(input) + 1) DO
        IF SUBSTRING(input, iterator, 1) IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9') THEN
          SET output = CONCAT(output, SUBSTRING(input, iterator, 1));
        END IF;
        SET iterator = iterator + 1;
      END WHILE;
      RETURN output;
    END [nativecode=1419 ** You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)]"]
)

Nov 20 02:39:43  [debug] $backTrace = #0 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(942): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php(922): CRM_Core_Error::exceptionHandler(Object(DB_Error))
#2 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/vendor/pear/db/DB.php(997): PEAR_Error->__construct("DB Error: unknown error", -1, 16, (Array:2), "\n    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255))\n      RE...")
#3 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php(575): DB_Error->__construct(-1, 16, (Array:2), "\n    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255))\n      RE...")
#4 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php(223): PEAR->_raiseError(Object(DB_mysqli), NULL, -1, 16, (Array:2), "\n    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255))\n      RE...", "DB_Error", TRUE)
#5 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/vendor/pear/db/DB/common.php(1928): PEAR->__call("raiseError", (Array:7))
#6 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/vendor/pear/db/DB/mysqli.php(936): DB_common->raiseError(-1, NULL, NULL, "\n    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255))\n      RE...", "1419 ** You do not have the SUPER privilege and binary logging is enabled (yo...")
#7 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/vendor/pear/db/DB/mysqli.php(406): DB_mysqli->mysqliRaiseError()
#8 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/vendor/pear/db/DB/common.php(1234): DB_mysqli->simpleQuery("\n    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255))\n      RE...")
#9 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/packages/DB/DataObject.php(2696): DB_common->query("\n    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255))\n      RE...")
#10 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/packages/DB/DataObject.php(1829): DB_DataObject->_query("\n    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255))\n      RE...")
#11 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/CRM/Core/DAO.php(468): DB_DataObject->query("\n    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255))\n      RE...")
#12 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/CRM/Core/DAO.php(1619): CRM_Core_DAO->query("\n    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255))\n      RE...", FALSE)
#13 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/Civi/Core/SqlTriggers.php(217): CRM_Core_DAO::executeQuery("\n    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255))\n      RE...", (Array:0), TRUE, NULL, FALSE, FALSE)
#14 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/CRM/Contact/BAO/Contact.php(3422): Civi\Core\SqlTriggers->enqueueQuery("\n    CREATE FUNCTION civicrm_strip_non_numeric(input VARCHAR(255))\n      RE...")
#15 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/Civi/Core/SqlTriggers.php(53): CRM_Contact_BAO_Contact::triggerInfo((Array:5), NULL)
#16 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(396): Civi\Core\SqlTriggers->rebuild()
#17 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/CRM/Extension/Manager.php(228): CRM_Core_Invoke::rebuildMenuAndCaches(TRUE)
#18 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/CRM/Extension/Downloader.php(121): CRM_Extension_Manager->replace("/tmp/tmp-79Xrch//uk.co.vedaconsulting.mosaico")
#19 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/api/v3/Extension.php(239): CRM_Extension_Downloader->download("uk.co.vedaconsulting.mosaico", "https://download.civicrm.org/extension/uk.co.vedaconsulting.mosaico/2.8.16371...")
#20 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_extension_download((Array:4))
#21 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/Civi/API/Kernel.php(149): Civi\API\Provider\MagicFunctionProvider->invoke((Array:8))
#22 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/Civi/API/Kernel.php(81): Civi\API\Kernel->runRequest((Array:8))
#23 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/api/api.php(22): Civi\API\Kernel->runSafe("Extension", "download", (Array:2))
#24 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/CRM/Admin/Form/Extensions.php(201): civicrm_api("Extension", "download", (Array:2))
#25 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(534): CRM_Admin_Form_Extensions->postProcess()
#26 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/CRM/Core/StateMachine.php(144): CRM_Core_Form->mainProcess()
#27 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Next.php(43): CRM_Core_StateMachine->perform(Object(CRM_Admin_Form_Extensions), "next", "Next")
#28 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Admin_Form_Extensions), "next")
#29 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Admin_Form_Extensions), "next")
#30 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php(352): HTML_QuickForm_Page->handle("next")
#31 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/CRM/Core/Page/Basic.php(395): CRM_Core_Controller->run()
#32 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/CRM/Core/Page/Basic.php(140): CRM_Core_Page_Basic->edit(2, NULL)
#33 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/CRM/Admin/Page/Extensions.php(105): CRM_Core_Page_Basic->run()
#34 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(313): CRM_Admin_Page_Extensions->run((Array:3), NULL)
#35 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem((Array:15))
#36 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke((Array:3))
#37 /home/dhwpuser/testdomain/wp-content/plugins/civicrm/civicrm.php(1178): CRM_Core_Invoke::invoke((Array:3))
#38 /home/dhwpuser/testdomain/wp-includes/class-wp-hook.php(303): CiviCRM_For_WordPress->invoke("")
#39 /home/dhwpuser/testdomain/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters("", (Array:1))
#40 /home/dhwpuser/testdomain/wp-includes/plugin.php(470): WP_Hook->do_action((Array:1))
#41 /home/dhwpuser/testdomain/wp-admin/admin.php(259): do_action("toplevel_page_CiviCRM")
#42 {main}

**Comment by MegaphoneJon** [comment]
This isn't Mosaico-specific.  The relevant part of the error is `You do not have the SUPER privilege and binary logging is enabled`.  This is discussed generally in [this Stack Exchange post](https://stackoverflow.com/questions/56389698/why-super-privileges-are-disabled-when-binary-logging-option-is-on).

Is this a server you control, or shared hosting?  I'm guessing the latter - but if you control the server, turn off binary logging unless you have a reason for it, in which case you need to grant the SUPER privilege to your MySQL user.

For shared hosting, contact your host.  It seems likely they turned on binary logging recently because otherwise you'd have received this error on installation of Civi.  If you have a good webhost, they'll address this for you.  If not, this webhost isn't suitable for running Civi.

I can't think of any good reason for a shared host to have binary logging enabled though, except maybe some exotic backup scheme,. So hopefully this was something experimental and getting user complaints will cause them to reconsider.

**Comment by cdhassell** [comment]
It's a VPS on Dreamhost. I'll contact them. Thank you for your help!

**Comment by cdhassell** [comment]
Follow up for others interested in this subject: We are basically SOL.  Dreamhost shared mysql has been upgraded to v8.0, and no longer supports functions and triggers. To get that ability, you now have to pay for a separate mysql VPS account.  I told them they would lose us as a customer instead.  Now I'm a bit annoyed and looking for a new hosting company.  Do other hosting companies require an upgrade to use functions and triggers?

**Comment by mattwire** [comment]
> Do other hosting companies require an upgrade to use functions and triggers?

Generally I'd say no. You kind of get what you pay for with some of the big providers like dreamhost who push low prices but very limited spec. and arbitrary restrictions on what you can do.

You can often get away with "generic" shared hosting for a while but eventually something like this may happen and is out of your control. Better to use a hosting provider that supports CiviCRM. See https://civicrm.org/partners-contributors?custom_157=Hosting (or we also offer CiviCRM hosting - https://www.mjwconsult.co.uk/en/hosting/)
