### ISSUE TITLE
Grey Screen on any template or mosaico mailing

### ISSUE THREAD

**Issue by netzih** [veda-consulting/uk.co.vedaconsulting.mosaico#477]
When loading an old mailing or I am getting a grey screen, The developer logs say ```Uncaught Unable to find <html> opening and closing tags in the template``` on template-loader.js
On WP 5.8.2 Civi 5.42.1 Mosaico 2.8

Here is a screenshot.
![image](https://user-images.githubusercontent.com/48005023/146101369-abd5ea4c-0957-4af0-9d48-974bdaca2a4c.png)

**Comment by netzih** [comment]
Still not sure what the issue is, But moved the site with the databases to a different server and the issue went away, Not sure if it's a server configuration...

**Comment by netzih** [comment]
Still not sure what the issue is, But moved the site with the databases to a different server and the issue went away, 
so it seems it was a server configuration even though other civi installations on the server do not have these isssues...
So I guess I'll close this for now.

**Comment by MegaphoneJon** [comment]
This issue occurs when paths change.  Here is some SQL I've run (probably some of it is unnecessary but harmless) to fix this issue recently (on a Drupal 7 to standalone migration):

```sql
UPDATE civicrm_mosaico_template SET metadata = REPLACE(metadata, 'https://oldsite.org', 'https://newsite.org');
UPDATE civicrm_mosaico_template SET html = REPLACE(html, 'https://oldsite.org', 'https://newsite.org');
UPDATE civicrm_mosaico_template SET metadata = REPLACE(metadata, 'sites/default/files/civicrm/ext', 'ext');
UPDATE civicrm_mosaico_template SET html = REPLACE(html, 'sites/default/files/civicrm/ext', 'ext');
UPDATE civicrm_mosaico_template SET metadata = REPLACE(metadata, 'sites/default/files/civicrm/persist', 'public/persist');
UPDATE civicrm_mosaico_template SET html = REPLACE(html, 'sites/default/files/civicrm/persist', 'public/persist');
UPDATE civicrm_mosaico_template SET metadata = REPLACE(metadata, 'sites%2Fdefault%2Ffiles%2Fcivicrm%2Fpersist', 'public%2Fpersist');
UPDATE civicrm_mosaico_template SET html = REPLACE(html, 'sites%2Fdefault%2Ffiles%2Fcivicrm%2Fpersist', 'public%2Fpersist');
```

Also, don't forget to copy the files from `persist/contribute` to their new location.
