### ISSUE TITLE
npm and deprecated `git://` URLs

### ISSUE THREAD

**Issue by totten** [veda-consulting/uk.co.vedaconsulting.mosaico#479]
The last few test runs failed on this

```
    npm ERR! Error while executing:
    npm ERR! /nix/var/nix/profiles/bknix-max/bin/git ls-remote -h -t git://github.com/SevInf/node-byline.git
    npm ERR! 
    npm ERR! fatal: remote error: 
    npm ERR!   The unauthenticated git protocol on port 9418 is no longer supported.
    npm ERR! Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
    npm ERR! 
    npm ERR! exited with error code: 128
```

Their blog has more info at https://github.blog/2021-09-01-improving-git-protocol-security-github/ 

TLDR:

* Github is killing support for `git://` URLs
* Today is a "brownout" -- they disabled `git://` temporarily to cause things to break. Final removal is in March.
* Something in `npm` depends on a deprecated `git://` URL, so it fails.

**Comment by totten** [comment]
@mattwire I believe Github has made the changes permanent now.

* I did a trial-run of building `mosaico` -- it failed: https://test.civicrm.org/view/Tools/job/Tool-Publish-mosaico/180/console
* Manually cloning repos with `git://` fails now:
    ```
    [bknix-max:/tmp] git clone git://github.com/civicrm/cv.git
    Cloning into 'cv'...
    fatal: remote error:
      The unauthenticated git protocol on port 9418 is no longer supported.
    Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
    ```

**Comment by mattwire** [comment]
I can't fix this - someone with jenkins access needs to.

https://test.civicrm.org/view/Tools/job/Tool-Publish-mosaico/
https://lab.civicrm.org/infra/ops/-/blob/master/jenkins-examples/Tool-Publish-mosaico.bash

I also can't see *where* the fix needs to be. @totten @seamuslee001

**Comment by totten** [comment]
Yeah, it was quite a mystery to me. I spent some time fiddling with `mosaico.git:package.json` and eventually figured out that updating `bower` fixes it.

Resulting PRs:

* https://github.com/civicrm/mosaico/pull/13
* https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/pull/525
