### ISSUE TITLE
Split out Mosaico Template builder permission 

### ISSUE THREAD

**Issue by rocxa** [veda-consulting/uk.co.vedaconsulting.mosaico#49]
Aim: to enable granting access to put together templates but not to edit all system templates and send emails.

I already have some code changes to do this so i'll put it in a PR soon.

**Comment by deepak-srivastava** [comment]
@rocxa Agree. Cool, looking forward to your PR :)

**Comment by rocxa** [comment]
#54

**Comment by rocxa** [comment]
new 'Access CiviCRM Mosaico' permission now merged into master by @deepak-srivastava
