### ISSUE TITLE
Translation of the editor

### ISSUE THREAD

**Issue by dev-allinappli** [veda-consulting/uk.co.vedaconsulting.mosaico#497]
The UI of the editor is a mix of French and English even though the rest of Mosaico is properly translated and everything related to the template also is, in the versafix template itself.

![image](https://user-images.githubusercontent.com/62597730/156574598-947378e1-0cd4-47a7-b5a9-fb4e914f115d.png)

This occurs for the top bar that should be translated through the fr.json file but is not entirely shown on the UI: `"Blocks": "Blocs",`

![image](https://user-images.githubusercontent.com/62597730/156574746-d91e494b-8aed-4010-9407-5793c81a9bcf.png)

This is important to us as our customers are based in French and do not speak good English ;-)

**Comment by dev-allinappli** [comment]
forcing the fr.json by deleting/uploading and flushing cache seemed to be a good workaround

**Comment by mattwire** [comment]
The editor translations are working in 3.1 release (they should have worked in 3.0 but there was a path issue)
