### ISSUE TITLE
Not allowed to make directories within the code writable by host

### ISSUE THREAD

**Issue by herbdool** [veda-consulting/uk.co.vedaconsulting.mosaico#5]
> Make sure uk.co.vedaconsulting.mosaico/packages/mosaico/uploads dir is writeable

This won't work on my host, Pantheon, which is too bad. Can't make a directory inside the code writable. The files directory is a symlink from a directory outside of the code. This seems to be a requirement of Mosaico but perhaps there's a way to overwrite that.

**Comment by deepak-srivastava** [comment]
In our list for future versions, is an improvement to make it work with civi uploads dir. Any contributions in that direction is most welcome.

**Comment by veda-consulting** [comment]
@deepak-srivastava is this something we can go back to the Mosaico team on? Others using the framework probably had the same issue?

**Comment by mark-rodgers** [comment]
@deepak-srivastava @veda-consulting I created a PR for this

**Comment by deepak-srivastava** [comment]
@mark-rodgers many thanks for the PR. Merged In. 

The idea of static_ sounds good to me. 
The other approach could be extension creating the dir - either during installation or just before it can't find it (or throwing the error). 

Seems like even after the static fix, there are going to be issues with files dir like #8. @mark-rodgers have you any got suggestions on that?

**Comment by mark-rodgers** [comment]
@deepak-srivastava based off your suggestion I made a PR that creates a static folder (755), if it does not already exist when installing the extension. I imagine this should resolve any issues @herbdool is having. I'll look further into #8 and see if I come up with any ideas on how to resolve his issue.

**Comment by deepak-srivastava** [comment]
@mark-rodgers thanks again :+1: 

Closing this issue now.
