### ISSUE TITLE
You will not be able to install/upgrade Mosaico until you have installed the org.civicrm.search_kit extension.

### ISSUE THREAD

**Issue by yurg** [veda-consulting/uk.co.vedaconsulting.mosaico#504]
Mosaico Version 2.8.1637146864 is installed  on CiviCRM [5.47.2] & Wordpress 5.9

Trying to upgrade gives: "You will not be able to install/upgrade Mosaico until you have installed the org.civicrm.search_kit extension." but we haven't. search_kit installed. 
Tried to move search_kit out of the core "ext" directory (wp-content/plugins/civicrm/civicrm/ext): no dice. 
I wonder if mosaico code is replaced manually (not via  civicrm extension upgrade system )  - would this break things? 
Please advise, thx.

**Comment by Upperholme** [comment]
Isn't it just a case of enabling the search kit extension - which is a core extension (so it will be listed on your site's Extensions page, but it won't be in your chosen extensions directory on your server (core extensions can be shipped with Civi and are stored in civicrm/ext/

**Comment by yurg** [comment]
@Upperholme Hard to tell, had to try a few combinations of extension disable / uninstall / enable, etc. 
Ended up with broken Mosaico due to Flexmailer issue: Flexmailer v5.45.1  is enabled, still Mosaico  hangs due to "missing extension, please read readme.md" or something like that.  Have given it up at the moment and sticked to the core mailings editor.
