### ISSUE TITLE
#474 follow up: can't install mosaico from extensions directory due to flexmailer confusion

### ISSUE THREAD

**Issue by yurg** [veda-consulting/uk.co.vedaconsulting.mosaico#505]
` [MegaphoneJon](https://github.com/MegaphoneJon) Please open a new issue? In that issue, please give the answers to the questions I asked above:
  Is the packages subfolder present in the mosaico extension folder?
  Do the permissions/file owner match the mosaico folder?
  What's the URL you downloaded version 2.8 from?`

@MegaphoneJon Thank you for stepping in!

- No, it is not: not quite sure if we need another copy of tinymce plugins and fontawesome but it feels like the subfolder presence proves the extension has been downloaded from a proper source.
- Yes, it does.
- I believe I've tried to install it from extensions directory lately (wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fadmin%2Fextensions&reset=1&action=browse) Please see below: would the error message be a bit confusing? It says "Extension Upgrade Failed. You will not be able to install/upgrade Mosaico until you have installed the org.civicrm.flexmailer extension." but flexmailer is NOT installed, it just sits in the available extensions list and it comes from the core extensions directory.
![image](https://user-images.githubusercontent.com/273282/159089581-b5f7180a-2b36-469c-b860-51c85c00ed5b.png)

**Comment by yurg** [comment]
@MegaphoneJon .. a few minutes later: indeed, it was "Extension Upgrade Failed. You will not be able to install/upgrade Mosaico until you have installed the org.civicrm.flexmailer extension."  I'm not a language expert  yet something a little bit more straightforward for non-english speakers (like me)  would be nice, like :"Some requirements are not met. Please install extensionname first."  
Not sure though if core patch (civicrm/CRM/Extension/Downloader.php:82) is worth creating.

**Comment by MegaphoneJon** [comment]
@yurg I'm not clear from your first answer whether the `packages` folder is present.  You say "no it is not" but then say "the subfolder presence proves the extension has been downloaded from a proper source".

The core patch would be welcomed.  Native English speakers often lack perspective on what is and isn't clear language to folks who aren't 100% fluent in English.

**Comment by yurg** [comment]
@MegaphoneJon Sorry for being unclear, shoulda made simpler sentence. The "resources" folder was not there indeed.
It works now ( at least looks working, we'll see at the next big mailing ). Thanks!
