### ISSUE TITLE
Check for existence of php imagik extension on install

### ISSUE THREAD

**Issue by BailsBails** [veda-consulting/uk.co.vedaconsulting.mosaico#51]
More of a this would be helpful rather than a bug.

Could you check for the existence of the php imagik extension upon install and halt and feedback if not found?

Cheers

bails

**Comment by PalanteJon** [comment]
I actually added this some time ago: https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/master/mosaico.php#L250

I believe there's also a check when you load the page.  The check I reference above will pop up as a "critical issue" on Civi 4.7.  Are you using 4.6?  4.6 doesn't currently show warnings when extensions fail checks.

**Comment by BailsBails** [comment]
Hi Jon

Yes you guessed correctly this was on a 4.6. Glad to know its already in place for 4.7.

Thanks

Bails

**Comment by deepak-srivastava** [comment]
@BailsBails like @PalanteJon suggested the check is there for page load.

But don't think it gets triggered on extension install. I'll leave this ticket open incase somebody wants to PR/help this.

**Comment by MegaphoneJon** [comment]
@deepak-srivastava I think you can close this because this check I wrote will handle this: https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/2.x/mosaico.php#L170
