### ISSUE TITLE
Cannot process ~/afsearchMosaicoTemplateList/afsearchMosaicoTemplateList.aff.html: malformed entity name ()

### ISSUE THREAD

**Issue by Slubbinge** [veda-consulting/uk.co.vedaconsulting.mosaico#514]
When viewing Mosaico templates I receive this error notice. I have just upgraded from Mosaico 2.8 to 2.9. we are running CIVI 5.47.3 in Wordpress

**Comment by mattwire** [comment]
Please update to latest version and report if still an issue
