### ISSUE TITLE
Mosaico 2.9 - Templates: cannot edit existing templates after update

### ISSUE THREAD

**Issue by alexmarketaccess** [veda-consulting/uk.co.vedaconsulting.mosaico#516]
CiviCRM 5.48.0 
Afform: Core Runtime v 0.5 
Search Kit 1.0 beta3 
FlexMailer 5.48.0
WordPress 5.9.3

After updating from Mosaico  2.8 to 2.9 in my sandbox (and updating all URLs in Mosaico tables as a result of site URL change), I notice that the interface to edit existing templates isn't usable (Mailings->Mosaico Templates.

Here's what it looked like in 2.8

![faItt](https://user-images.githubusercontent.com/15691820/164063557-af34cf70-182e-46c3-9fa0-ca6b6396e2e6.png)

And here's what it looks like after update to 2.9:

![l4mVT](https://user-images.githubusercontent.com/15691820/164063629-90dee891-ba42-49ed-a6e2-c903db80307d.png)

So with 2.9, this new interface doesn't allow me to edit the templates -- nor can I change the template settings....

Any suggestions on how to resolve?

**Comment by seantwalsh** [comment]
@alexmarketaccess I'm debugging this currently on a site. Seems to be permissions related because users can see it when they have admin permissions but not just the edit message templates permission. In our case they aren't seeing anything listed.

**Comment by francescbassas** [comment]
Have you tried applying this patch? https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/pull/502/files

These changes are not present in version 2.9.

**Comment by seantwalsh** [comment]
I have not will give that a try. Thanks @francescbassas.

**Comment by alexmarketaccess** [comment]
With civiCRM 5.48.0 installed, and Mosaico 2.9.1645644008
When I Update wp-content/uploads/civicrm/ext/uk.co.vedaconsulting.mosaico/Civi/Api4/MosaicoTemplate.php
with the patch indicated above, the Mosaico Templates page at:
/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fmosaico-template-list
still behaves the same as it did prior to the patch

**Comment by alexmarketaccess** [comment]
@francescbassas @seantwalsh Any luck with this, the issue persists for me :-(

**Comment by mariav0** [comment]
> Have you tried applying this patch? https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/pull/502/files

I have tried the patch and it works. Without admin permission I can view and edit all templates again. Thank you!

**Comment by alexmarketaccess** [comment]
@seantwalsh @mattwire @francescbassas 
Hi, I'm coming back around to this issue ... which still persists for me... I applied the patch above but still no access to edit Templates. I tried creating a new template in case it was an issue with pre-existing templates, but nope -- all I get is the list of the templates, and all I can do is edit their Title.

**Comment by alexmarketaccess** [comment]
I'm providing an update in case anyone else has this issue. 
The issue was that /wp-content/**uploads**/civicrm/ext
contained:

Afform: Core Runtime v 0.5
Search Kit 1.0 beta3

And civiCRM was picking up these two extensions instead of the core versions found at:
 /wp-content/**plugins**/civicrm/ext

Form Core 5.48.0
Search Kit 5.48.0

To resolve the issue, I:

1. Disabled Mosaico
2. Disabled the Affrom and deleted the folder /wp-content/**uploads**/civicrm/ext/Afform, did a Extension Refresh, so it found the core version, enabled it and ran the associated database update.
3. Disabled Search Kit and deleted the folder /wp-content/**uploads**/civicrm/ext/SearchKit, , did a Extension Refresh, so it found the core version, enabled it and ran the associated database update.
4. Re-enabled Mosaico

And I was then able to edit the Mosaico templates successfully.

**Comment by MegaphoneJon** [comment]
@colemanw Is it possible to mark old versions of afform and search_kit as obsolete the way you did with API4?

**Comment by alexmarketaccess** [comment]
@MegaphoneJon @colemanw I'll second that motion -- seems like a wise idea to verify that the version numbers of dependent extensions meet the requirements for the target version of Mosaico.
