### ISSUE TITLE
Mosaico custom blocks

### ISSUE THREAD

**Issue by Bsymonds7749** [veda-consulting/uk.co.vedaconsulting.mosaico#519]
Hi, I’m new to Mosaico (my not-for-profit has just installed CiviCRM and Mosaico). I’m wondering if anyone has information on how to build a new custom content block for Mosaico? Specifically, I’d like to be able to scrape content from my Posts into the email. Can this be done? Has anyone ever built something like this? Thanks for your help. First steps :)

**Comment by MegaphoneJon** [comment]
Hi @Bsymonds7749!

Just to clear up terminology - I would consider a "custom content block" a block you can drag in from the left pane of Mosaico.  It sounds like you want to add content to an existing block, or more likely both.

There is an extension that claims to handle adding content from WordPress - [Content Tokens](https://civicrm.org/extensions/content-tokens).  I would test this on a non-Mosaico mailing first, and don't be surprised if it doesn't work out of the box - it seems like it's not really tested with WordPress.

To be clear - these pretty advanced topics!  You may want to discuss this with whomever set up CiviCRM, or another CiviCRM vendor if you feel this is outside your skillset.

### Automate Adding Content

If Content Tokens doesn't work, your best bet is probably to edit the code to get it working.  Note that this requires PHP coding skills - but it's less work than creating your own extension.

### Creating Custom Blocks

The best way to do this is to create a new base template, probably by copying your current template to use as a base. There are great instructions for that [on ArtfulRobot's blof](https://artfulrobot.uk/blog/adding-custom-block-mosaico-email-editor-civicrm) and [the official Mosaico CiviCRM documentation](https://docs.civicrm.org/mosaico/en/latest/api/#base-templates). Instructions for creating blocks is in the [upstream Mosaico documentation](https://github.com/voidlabs/mosaico/blob/master/templates/tutorial/mosaico-tutorial.md).  Important tip - define a new "base templates" folder in the Mosaico setting, don't put them in the extension's template folder, or you'll lose them every time you upgrade!

**Comment by Bsymonds7749** [comment]
Hi MegaphoneJon
Thanks so much for replying so quickly and with so much info. Those sound like good places for me to start.
I will probably end up talking to the people who set up our Civi but I’m trying to learn as much as possible to save on budget.
Appreciate your help
Bryn
