### ISSUE TITLE
Errors on save and on test send

### ISSUE THREAD

**Issue by sralsg** [veda-consulting/uk.co.vedaconsulting.mosaico#52]
We've recently installed the beta1 version, but are encountering errors saving and sending test messages. The templates are being saved in the browser, but not to CiviCRM. 4.6.22 on Drupal 7.50. Chrome 53 and Safari 10 on OSX both have the same results. Screenshot with console attached. These are the displayed messages:

Something went wrong while saving message template!
Something went wrong while sending email!

These are the log messages:

LOCATION	https://secure.wildsight.ca/civicrm/mosaico/dl
REFERRER	https://secure.wildsight.ca/civicrm/mosaico/editor?snippet=2

$backTrace = #0 /var/www/civicrm/4.6/CRM/Core/Error.php(364): CRM_Core_Error::backtrace("backTrace", TRUE) #1 /var/www/civicrm/4.6/CRM/Core/IDS.php(275): CRM_Core_Error::fatal("There is a validation error with your HTML input. Your activity is a bit susp...") #2 /var/www/civicrm/4.6/CRM/Core/IDS.php(190): CRM_Core_IDS->kick(Object(IDS_Report)) #3 /var/www/civicrm/4.6/CRM/Core/IDS.php(92): CRM_Core_IDS->react(Object(IDS_Report)) #4 /var/www/civicrm/4.6/CRM/Core/Invoke.php(139): CRM_Core_IDS->check((Array:3)) #5 /var/www/civicrm/4.6/CRM/Core/Invoke.php(83): CRM_Core_Invoke::init((Array:3)) #6 /var/www/civicrm/4.6/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3)) #7 /var/www/civicrm/4.6/drupal/civicrm.module(482): CRM_Core_Invoke::invoke((Array:3)) #8 [internal function](): civicrm_invoke("mosaico", "dl") #9 /var/www/drupal/git-7/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2)) #10 /var/www/drupal/git-7/index.php(21): menu_execute_active_handler() #11 {main}

$Fatal Error Details = Array ( [message] => There is a validation error with your HTML input. Your activity is a bit suspicious, hence aborting [code] => )

Notice:  Undefined variable: args in CRM_Core_IDS->kick() (line 257 of /var/www/civicrm/4.6/CRM/Core/IDS.php).

Warning: implode(): Invalid arguments passed in CRM_Core_IDS->kick() (line 257 of /var/www/civicrm/4.6/CRM/Core/IDS.php).

$IDS Detector Details (too long to post here).
![screen shot 2016-10-12 at 4 04 24 pm](https://cloud.githubusercontent.com/assets/14890322/19329491/5f6837e2-9096-11e6-94d6-fca2c41f7dbe.png)

**Comment by PalanteJon** [comment]
Those logs look like you've triggered CiviCRM's internal IDS.  This isn't a Mosaico-specific problem; it's pretty easy to trigger when editing messages without Mosaico.  Unless you have reason to believe that there's something Mosaico-specific about this?

I generally grant the "Bypass IDS" permission to anyone who has the ability to create mailings or templates.  For that matter, I grant it to anyone who's a member of the organization using CiviCRM.  Since you're on Drupal, you can find that permission at https://secure.wildsight.ca/admin/people/permissions.  Please grant it to the appropriate roles, and report back here if that fixes your issue?

All that said, I DO think it'd be good if Mosaico (and core Civi for that matter) more gracefully caught an IDS failure.

**Comment by sralsg** [comment]
Thanks @PalanteJon. Granting skip IDS check solves the problem.

This isn't something we've run into before otherwise editing messages.

**Comment by PalanteJon** [comment]
Happy to help!  The IDS often triggers when you include links to outside sites - so it's most likely the content of your message is a bit different this time.  Either way, glad it's resolved.

@deepak-srivastava This is good to close.

**Comment by sralsg** [comment]
Just for clarity, this was happening with a template containing nothing but a generic block dragged in. No outside links, nothing at all but sample text.

**Comment by deepak-srivastava** [comment]
@PalanteJon thanks for help.

Beta1 does catch the error but in a generic way at the moment - https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/master/packages/mosaico/src/js/ext/localstorage.js#L77 (and line 81). 

We probably at some point improve it to detect IDS and / or skip IDS check for mosaico templates, given mosaico templates would have their own permissions.
