### ISSUE TITLE
Anybody know how to fix this image issue?

### ISSUE THREAD

**Issue by gwxnny** [veda-consulting/uk.co.vedaconsulting.mosaico#521]
As you can see below, everytime I add an image it just becomes so tiny, but once i clicked away, it disappears!

![image](https://user-images.githubusercontent.com/99624743/166857147-f2fe334e-2446-4183-8fee-7530d4cce7f2.png)

**Comment by themak1985** [comment]
@gwxnny - this is an old issue, but my guess is that your resource URLs may be incorrect. 

Also are you using the latest version of mosaico?

Either way, I hope you resolved this in the last couple months.

**Comment by LuckyfishSoftware** [comment]
I'm experiencing the same issue using an up-to-date Mosaico (2.10.1665574809) with CiviCRM 5.54.0, Wordpress 6.0.3, and PHP 7.4. I've not made any changes to my resource URLs.

It last worked in early July. When I make a copy of the last working mailing and edit it, none of the images are displayed.

**Comment by LuckyfishSoftware** [comment]
Reverted back to 2.9.1645644008. Same issue.

**Comment by themak1985** [comment]
@DetroitGreenways what happens when you make an email from stock versafix template?

**Comment by LuckyfishSoftware** [comment]
@themak1985 Ah, I forgot to mention that. The same thing happens with the stock versafix template.

**Comment by LuckyfishSoftware** [comment]
@gwxnny Did you determine what caused this issue?
