### ISSUE TITLE
upstream versafix-1 "View in your browser" hidden on mobile devices (narrow viewport)

### ISSUE THREAD

**Issue by twomice** [veda-consulting/uk.co.vedaconsulting.mosaico#522]
This appears to be sn issue with the upstream versafix-1 project and not this extension directly. I take it this extension makes a point of not modiyfing the versafix-1 template code, right? 

So I've got two options to address this, which leads to 2 questions:
1. File an issue with upstream: Is that https://github.com/voidlabs/versafix-template ? 
1. Hack versafix-1 to my liking: Is that going to be lost with my next upgrade of this extension?

**Problem summary:**
(This bad behavior is visible in the mosaico "preview" feauture as well as in live emails. Screenshots here are from the "preview" feature.)

Mailings that use 'versafix-1' typically have two links at the top of the mailing body: "Unsubscribe" and "View in your browser".

In wide-format viewports (over 600px, apparently), both of these links display normally:
![wide](https://user-images.githubusercontent.com/759449/169394431-b07f3b4a-ddd2-4901-b9d7-e8980af56844.png)

However if you decresase the width of that preview  (or send a mailing and view it in a narrow browser window or in portait orientation on a typical mobile device), the "View in your browser" link is hidden:
![narrow](https://user-images.githubusercontent.com/759449/169394730-f9f9c21f-667e-4275-99d6-0d9a8ed15720.png)

**Technical analysis:**
This appears to be caused by the use of the "mobile-hide" class on the `<div>` element containing this link, in packages/mosaico/templates/versafix-1/template-versafix-1.html

**Comment by MegaphoneJon** [comment]
Upstream seems to be a bit unresponsive, and we're not using the latest version of upstream Mosaico - but if the problem *does* exist in upstream, a PR seems appropriate.

If you *do* decide to hack versafix-1, I strongly recommend creating a separate Mosaico templates directory (you can specify one in the Mosaico settings page) and copying versafix-1 there and giving it an alternate name.  Then you can use your alternate template as a basis for future mailings, and it won't get overwritten on upgrade.

**Comment by twomice** [comment]
Thanks. FYI that was the path we took: fork versafix-1 as a new template 'versafix-[client_name]-1' and make thee fix there; then educate the client users to use that template going forward. (It happens that they don't use the "copy mailing" approach to generate new mailings; if they had, we would have also gone in and edited the html in previous mailings to make this patch therein.)
