### ISSUE TITLE
Creating templates from base templates with a custom 'title' breaks loading templates

### ISSUE THREAD

**Issue by JKingsnorth** [veda-consulting/uk.co.vedaconsulting.mosaico#524]
Hi, I'm happy to do some testing of the current master version for a 2.10 release, given this important commit by @mattwire related to the guzzlehttp/psr7 library (https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/commit/e5a6c8d8dc7a36e6a5ef3ec7d95d075653129f27)

However, it looks like the nightly builds are currently failing? https://test.civicrm.org/view/Tools/job/Tool-Publish-mosaico/

**Comment by JKingsnorth** [comment]
failing builds is related to this: https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/issues/479

**Comment by totten** [comment]
@JKingsnorth You want to try the new nightly? After #525, the latest run of `Tool-Publish-mosaico` looks like it ran clean.

**Comment by JKingsnorth** [comment]
Thanks for the heads up @totten !

Unfortunately I've run into some issues, but I'm seeing them in the 2.9 version too. Our base templates are not loading on the 'New Mailing' page, and there's an error in the console log:

```
TypeError: Cannot read properties of undefined (reading 'title')
    at filterTemplate (builder?an=angular-...
```

Also, the mosaico template listing page has vanished.

So  this will hamper me testing for a 2.10 release until I can see what's happened here...

**Comment by JKingsnorth** [comment]
To get the template listing page working I had to:
- Enable SearchKit extension
- Disable Mosaico extension
- Re-enable Mosaico extension

The base templates are still missing in 2.10, although I managed to get them to appear in 2.9 (though I'm not sure how!)

**Comment by mattwire** [comment]
@JKingsnorth Is the template issue related to #516?

**Comment by JKingsnorth** [comment]
Possible. I think it's because` civicrm_api3('MosaicoTemplate', 'get'` is returning the 'base' property as the 'title' of the base template instead of the 'name' of the base template. So it can't find the base template in the list when it's trying to build the listing of templates.

**Comment by JKingsnorth** [comment]
Hmn, it is actually stored as the 'Title' of the base template in the database table 'civicrm_mosaico_template'

So the steps to reproduce are to create a custom base template with a 'title' that is different from the 'name', and then try to create a new template based on it. You'll see the 'base' field for the new template is the 'title' of the base, instead of the 'name', and then the template listing doesn't load.

**Comment by mattwire** [comment]
@JKingsnorth Is this still an issue?

**Comment by JKingsnorth** [comment]
I think we can close it, it's old and I've tested just now and haven't been able to recreate it. Thanks.
