### ISSUE TITLE
Images do not show in email client

### ISSUE THREAD

**Issue by andyburnsco** [veda-consulting/uk.co.vedaconsulting.mosaico#531]
Tested with version 2.9.1657273210 using autobuild here: https://docs.civicrm.org/mosaico/en/latest/develop/#publication - the "-latest.zip". Release 2022-07-08.

Civi 5.51.1 Multisite.

Using the test send email function, no image shows in email client. Inspecting the email HTML I see the image:

                <img class="mobile-full" alt="" style="border: 0px; display: block; vertical-align: top; max-width: 534px; width: 100%; height: auto;" src="https://example.org/wp-admin/admin.php?page=CiviCRM&amp;q=civicrm%2Fmosaico%2Fimg&amp;src=https%3A%2F%2Fexample.org%2Fwp-content%2Fuploads%2Fcivicrm%2Fpersist%2Fcontribute%2Fsites%2F1%2Fimages%2Fuploads%2Flp_logo_primary_500_73c2cafdcc9dc08fdc465d7351ccad31.png&amp;method=resize&amp;params=534%2Cnull" width="534" vspace="0" hspace="0" border="0">

If I view email in browser while logged in, it shows. It does not show if you are not logged in. I have  `access uploaded files` granted to anonymous users in WordPress Access Control.

**Comment by mattwire** [comment]
Should be fixed by https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/commit/8418b51434fe4b40e623c44ce38c6e1e15d7625c

**Comment by andyburnsco** [comment]
Confirmed this is working. Used 2022-10-03 build. Thank you greatly, @mattwire
