### ISSUE TITLE
What is the next version

### ISSUE THREAD

**Issue by eileenmcnaughton** [veda-consulting/uk.co.vedaconsulting.mosaico#534]
@mattwire I was looking at the fact there are [quite a few unreleased commits here](https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/compare/2.9...2.x) & that they (among other things) make tests pass - but then when I thought about what version would need to be tagged I realised it either needs to be 3.0 - which implies a major version change - or a new naming convention - ie. 2.9.1

I have a feeling the handling for switching might not always see 2.9.1 as 'higher' than 2.9 - but that is just a vague 'haven't I seen this before niggle'

I probably would go to `3.0.0` with the 'major change' being that the versioning system has changed

**Comment by totten** [comment]
What would be wrong with `2.10`?

**Comment by totten** [comment]
(I have no objection `X.Y.Z` in general - that's fine numbering. It just seems `2.10` is the natural progression, based on the numbering so far in this repo.)

**Comment by eileenmcnaughton** [comment]
oh right - I suppose so

**Comment by mattwire** [comment]
Yes, it would be 2.10. I'm generally happy to tag a release once someone provides feedback on the latest nightly to say it's all working ok

**Comment by francescbassas** [comment]
I can confirm that I'm running 2.9 with PR https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/pull/512 and https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/pull/502 applied for 3 months and all is working nice.

**Comment by francescbassas** [comment]
This it can be closed.
