### ISSUE TITLE
email not sent after server migration 

### ISSUE THREAD

**Issue by lshaw1968** [veda-consulting/uk.co.vedaconsulting.mosaico#560]
Drupal 9
Civicrm 5.56.1
mosaico 2.9

Message from drupal

Hook_civicrm_documents_entity_ref_spec should be updated to pass an array of parameter names to CRM_Utils_Hook::invoke(). Caller: CRM_Documents_Utils_HookInvoker::invoke Array ( [civi.tag] => deprecated 

Message from civicrm

![image](https://user-images.githubusercontent.com/46035740/209990805-9b56ba94-b2c0-4859-8a6f-03f40cb00025.png)

Log 
[warning] hook_civicrm_documents_entity_ref_spec should be updated to pass an array of parameter names to CRM_Utils_Hook::invoke(). Caller: CRM_Documents_Utils_HookInvoker::invoke

**Comment by adixon** [comment]
I wonder if this is the same issue? https://civicrm.stackexchange.com/questions/43273/db-error-unknown-error-when-trying-to-send-mosaico-civimail

Specifically, those warnings you're listing might not be the cause of the error, try looking in your browser console.

**Comment by mattwire** [comment]
This is most likely a local configuration issue - see stackexchange etc.
