### ISSUE TITLE
Unable to Edit Templates

### ISSUE THREAD

**Issue by gcpower** [veda-consulting/uk.co.vedaconsulting.mosaico#589]
I can create and save a template.  When I try to edit, I just see a blank screen.  The console shows the following error

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) 

https://www.web-developments.co.uk/bwc/bwc/wp-content/uploads/civicrm/ext/uk.co.vedaconsulting.mosaico/packages/mosaico/templates/versafix-1/template-versafix-1.html

I note that sub directory bwc appears twice, instead of the correct location - only once.  The versions are Mosaico 2.12.1682198437 CiviCRM 5.60.0 WordPress 6.2.  The same results appear on Safari 16.4.1  and Chrome 112.0.5615.121 

WordPress was migrated from Localhost.  CiviCRM was a fresh install.  I have deleted and reinstalled Mosaico and then updated to the new version.  Extension resource url is set at [civicrm.files]/ext/

To save any duplication of effort, I did email Matthew with this issue before realising the correct procedure.

**Comment by MegaphoneJon** [comment]
Check the `metadata` column of the `civcrm_mosaico_template` folder.  Does the wrong path appear there as well? If so, does changing it in the database fix your problem in the UI?

**Comment by gcpower** [comment]
Jon

Thank you very much for your reply.

I have been unable to look at this until today.  That was indeed the issue.  I have updated the metadata, deleted the existing mailings and created anew.  All working properly now.

Thank you very much.  That has saved much frustration and time.

Regards
Graham


Graham Clarkson
***@***.***
