### ISSUE TITLE
Mosaico: Packages are missing

### ISSUE THREAD

**Issue by chaplincircle** [veda-consulting/uk.co.vedaconsulting.mosaico#590]
Mosaico: Packages are missing
Mosaico requires dependencies in its "packages" folder. Please consult the README.md for current installation instructions.

Whatever I do, I can't get round the above error message.

What version can I simply upgrade to?

The read.me points to https://docs.civicrm.org/mosaico/en/latest/ but that doesn't advise about configuring packages.

Where is the packages folder anyway?

**Comment by MegaphoneJon** [comment]
@chaplincircle Without hearing what you've already tried it's hard to answer your question - but it sounds like you may have downloaded Mosaico from Github?

**Comment by chaplincircle** [comment]
Yes I did....and after the fact I saw the instruction not to do that!
How about putting that in the read.me so if you're looking on GitHub you stop at that point?

![image](https://user-images.githubusercontent.com/104565780/234308807-2d0ad264-5538-4a4a-a688-b45f9d79144a.png)


Guess I'll have to fix my
Directory Unwritable
Your extensions directory is not set or is not writable
issue then.

**Comment by mattwire** [comment]
@chaplincircle PR welcome :-)
