### ISSUE TITLE
api MosaicoTemplate.replaceurls 

### ISSUE THREAD

**Issue by aydun** [veda-consulting/uk.co.vedaconsulting.mosaico#591]
When changing domains or CMS (eg Drupal 7 to WordPress), URL's in the base templates need to be updated.  The api function `MosaicoTemplate.replaceurls` is intended to help with that, but the underlying function [CRM_Mosaico_BAO_MosaicoTemplate::replaceUrls()](https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/blob/5e62809e9632d9561cb1bfd4f90afc117abe5a30/CRM/Mosaico/BAO/MosaicoTemplate.php#L33) only updates the `metadata` field.   The `html` and `content` fields also need to be updated.

I have code that updates those fields as well and can put that in a PR.  That could either be an expansion of the existing api or a new function.  I don't see that the existing function is useful as it is since it only does one part of the job. But ... are there any circumstances where you want to only update the `metadata` field without corresponding changes in `html` and `content`?

**Comment by mattwire** [comment]
Seems like a good idea to me!

**Comment by mattwire** [comment]
Implemented via #593 in 3.0 release
