### ISSUE TITLE
extension broken on clean install ( CiviCRM 4.6.14 LTS )

### ISSUE THREAD

**Issue by mark-rodgers** [veda-consulting/uk.co.vedaconsulting.mosaico#6]
Screenshot attached below. When accessing the **Mailing => Message Template Builder**.

1. Page gets cut off
2. by VOX mail image does not exist.
3. when I click on a template, which is supposed to take me to the mosacio editor page, all I get is a screen with a solid red background.

![image](https://cloud.githubusercontent.com/assets/2798202/13652567/b87edc9a-e601-11e5-9f31-31dc1a265770.png)

**Comment by mark-rodgers** [comment]
After digging into the code a bit I noticed the extension uses the finfo function, after some research I discovered fileinfo is a php extension which I did not have enabled. Rebuilt apache using easyapache in WHM and it appears to be working a lot better now. Although the Message Template Builders page is still getting covered by the footer in the default drupal7 theme. Resizing the page doesn't help at all.

![image](https://cloud.githubusercontent.com/assets/2798202/13653940/8d56f6a8-e609-11e5-8d6f-164a83ad9b0e.png)

**Comment by veda-consulting** [comment]
@mark-rodgers thanks for the info Mark. @deepak-srivastava maybe we should add the fileinfo check as the other patch did?

@mark-rodgers also to note the template page is one that will be reviewed prior to a Beta release, currently its just showing the Mosaico templates page and the majority feel we should show a CiviCRM specific page.

**Comment by deepak-srivastava** [comment]
@veda-consulting have released alpha3 with fileinfo check. Also fixed template to look more like civi pages.

Closing this ticket for now.
