### ISSUE TITLE
HTML emails incorrect after PHP 8.2 update 

### ISSUE THREAD

**Issue by LuckyfishSoftware** [veda-consulting/uk.co.vedaconsulting.mosaico#618]
I upgraded our PHP from 7.4 to 8.2 then sent a test email. The HTML no longer displayed correctly in mail.google.com. The sender email was also not correct. 
![image](https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/assets/47638668/f9edef08-143d-4cae-be42-acf9a614e4aa)

I switched PHP back to 7.4, resent the email, and it looked correct. HTML test view of the email looked correct under both PHP versions, so perhaps this doesn't have anything to do with the extension. I did some searched on StackExchange, but didn't find a match.
![image](https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/assets/47638668/ae0a9591-aecf-4055-a70f-0191f8182d56)

I am running Civicrm 5.66.0 with Mosaico extension 3.3.1697392242 on Wordpress version 6.3.2.

**Comment by jofranz** [comment]
Generally speaking CiviCRM currently [does not support](https://docs.civicrm.org/installation/en/latest/general/requirements/#php-version) PHP 8.2

**Comment by LuckyfishSoftware** [comment]
I didn't know that. I will try PHP 8.1.

**Comment by LuckyfishSoftware** [comment]
I'm getting the same results under PHP 8.1.

**Comment by Upperholme** [comment]
Whilst CiviCRM core supports PHP8.1 that doesn't mean that the same is true for all extensions. I'm not sure about Mosaico?

**Comment by LuckyfishSoftware** [comment]
I just received an non-Mosaico email from CiviCRM and it has the same formatting issue. I'll close this issue since it appears to be a problem outside of this extension.
