### ISSUE TITLE
versafix-1 template not working

### ISSUE THREAD

**Issue by roblog** [veda-consulting/uk.co.vedaconsulting.mosaico#622]
Hi, we are getting the following js error with a fresh in stall of Mosaico v. 3.3.1697392242 on a Drupal 10 site with php 8.1 and Civi 5.67.0:

> Uncaught Unable to find <html> opening and closing tags in the template

The error occurs after clicking the Edit button in the design phase, and the result is a grey page which is empty apart from the main Civi menu.

The other two out of the box templates appear to be working ok.

**Comment by mattwire** [comment]
Check the versafix template html is not an empty file. If it is re-download the extension.

**Comment by roblog** [comment]
Hi. Are you referring to the file at  uk.co.vedaconsulting.mosaico/packages/mosaico/templates/versafix-1/template-versafix-1.html ?

I had actually already sussed out this file was empty so copied the file from another working installation of the extension on a different site. This gave me another js error (sorry cannot remember what it was). So then I completely reinstalled the extension and the file in question has the missing content, including the html open and close tags reported in the error message.

However, I am still getting the original error message, even though the re-installed version of the file has content in it. I have tried rebuilding  the Drupal cache, and the Civi cache, and have emptied out the templates_c folder and done a hard page refresh (Ctrl+F5) but none of these actions makes a difference.

**Comment by roblog** [comment]
I don't know if this is relevant but according to my Firefox browser console the error is occurring at line 202 of uk.co.vedaconsulting.mosaico/packages/mosaico/dist/rs/src/js/template-loader.js but the template-loader.js file does not actually exist in the site's filesystem.

**Comment by roblog** [comment]
It looks like the empty html template file got lodged in my Firefox browser cache. Ctrl+F5 didn't have any effect, so I tried it in a different browser and it worked. So i did "Forget about this site" in Firefox, and it is working there as well now.
