### ISSUE TITLE
Modified French translation

### ISSUE THREAD

**Issue by dev-allinappli** [veda-consulting/uk.co.vedaconsulting.mosaico#643]
Can you replace the existing file in `/packages/mosaico/dist/rs/lang` by this one? I can't find it in the repository to do a commit.

[mosaico-fr.json](https://github.com/veda-consulting-company/uk.co.vedaconsulting.mosaico/files/14988387/mosaico-fr.json)

**Comment by mattwire** [comment]
@allinappliadmin It needs to be a PR against https://github.com/civicrm/mosaico

**Comment by dev-allinappli** [comment]
done: https://github.com/civicrm/mosaico/pull/19
