### ISSUE TITLE
Issues on version 3.6

### ISSUE THREAD

**Issue by dev-allinappli** [veda-consulting/uk.co.vedaconsulting.mosaico#657]
After upgrading to last version (3.6) I noticed two issues:
- `Failed to load plugin: mailto from url https://domain.com/wp-content/uploads/civicrm/ext/uk.co.vedaconsulting.mosaico/packages/mosaico/dist/rs/plugins/mailto/plugin.min.js` I confirm that there's no `plugins` folder
- I can't edit the text of a text/image block created on a previous version but I can edit the image of this kind of block, so the image is only on the text part of it.

I had to downgrade back to 3.5 to be able to work again

**Comment by mattwire** [comment]
That's strange. Is the plugins folder existing on 3.5 package?

**Comment by dev-allinappli** [comment]
> That's strange. Is the plugins folder existing on 3.5 package?

no, I've checked on several instances. I still remember seeing it once on a previous version but that could have been a long time ago.

**Comment by mattwire** [comment]
> > That's strange. Is the plugins folder existing on 3.5 package?
> 
> no, I've checked on several instances. I still remember seeing it once on a previous version but that could have been a long time ago.

It was built automatically here: https://test.civicrm.org/view/Tools/job/Tool-Publish-mosaico/lastBuild/ can you see any issues?

**Comment by dev-allinappli** [comment]
sorry, I've totally forgotten that I was using addon Mosaicoextras. Fixed
