### ISSUE TITLE
Permission 'delete Mosaico template' should be declared with 'label' and 'description' keys

### ISSUE THREAD

**Issue by wintermoor** [veda-consulting/uk.co.vedaconsulting.mosaico#658]
On CiviCRM 5.75.1 with WordPress 6.6.2 & PHP 8.2.23 there is an error message on every backend page: 

Deprecated: Permission 'delete Mosaico template' should be declared with 'label' and 'description' keys. See https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_permission/ Caller: CRM_Core_Permission::assembleBasicPermissions in /homepages/8/d870413500/htdocs/civicrm/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php on line 1132

Does anybody know how to set the keys?

**Comment by mattwire** [comment]
The issue is in mosaico extras extension - see https://lab.civicrm.org/extensions/mosaicoextras/-/issues/2
