### ISSUE TITLE
Mosaico download tempate error

### ISSUE THREAD

**Issue by mark-rodgers** [veda-consulting/uk.co.vedaconsulting.mosaico#7]
The download button in Mosaico editor is not working correctly.
<img width="1402" alt="screen shot 2016-03-10 at 8 10 37 am" src="https://cloud.githubusercontent.com/assets/2798202/13675682/9abdc77a-e697-11e5-86f9-1c25339529fd.png">

**Comment by deepak-srivastava** [comment]
@mark-rodgers That's most likely due to one of "uk.co.vedaconsulting.mosaico/packages/mosaico/uploads" or "uk.co.vedaconsulting.mosaico/packages/mosaico/uploads/static" dir not being writeable (also mentioned with installation steps) ?

**Comment by mark-rodgers** [comment]
Wow I completely overlooked that, but yea I did notice I was missing a static directory so I create it and the file now downloads except all the images point to the images in the static folder except none of the images are readable by public, likely a permission issue?
