### ISSUE TITLE
Packages directory seems to be missing from repo when cloning today

### ISSUE THREAD

**Issue by BailsBails** [veda-consulting/uk.co.vedaconsulting.mosaico#73]
ls -lah uk.co.vedaconsulting.mosaico/
total 124K
drwxr-xr-x 11 bails dev 4.0K Nov 30 10:43 .
drwxr-xr-x  4 bails dev 4.0K Nov 30 10:43 ..
drwxr-xr-x  3 bails dev 4.0K Nov 30 10:43 api
drwxr-xr-x  2 bails dev 4.0K Nov 30 10:43 bin
drwxr-xr-x  3 bails dev 4.0K Nov 30 10:43 CRM
drwxr-xr-x  2 bails dev 4.0K Nov 30 10:43 css
drwxr-xr-x  8 bails dev 4.0K Nov 30 10:43 .git
-rw-r--r--  1 bails dev   25 Nov 30 10:43 .gitignore
-rw-r--r--  1 bails dev 1.2K Nov 30 10:43 info.xml
drwxr-xr-x  3 bails dev 4.0K Nov 30 10:43 js
-rw-r--r--  1 bails dev  34K Nov 30 10:43 LICENSE.txt
-rw-r--r--  1 bails dev 8.8K Nov 30 10:43 mosaico.civix.php
-rw-r--r--  1 bails dev 9.8K Nov 30 10:43 mosaico.php
-rw-r--r--  1 bails dev 4.5K Nov 30 10:43 README.md
drwxr-xr-x  2 bails dev 4.0K Nov 30 10:43 sql
drwxr-xr-x  3 bails dev 4.0K Nov 30 10:43 templates
-rw-r--r--  1 bails dev  905 Nov 30 10:43 TESTING.md
drwxr-xr-x  4 bails dev 4.0K Nov 30 10:43 xml

**Comment by deepak-srivastava** [comment]
Packages has moved to civi repo - https://github.com/civicrm/mosaico
There is a new build process. Check the new development steps for building the repo - https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/blob/master/README.md

Incase you want the last release version with packages dir, use beta1 tag to checkout.

**Comment by totten** [comment]
In `README.md`, we added instructions under `Development: Installation` about calling `setup.sh -D`. 

For the general download instructions under `How to Install`, perhaps we should be pointing to http://dist.civicrm.org/extension/uk.co.vedaconsulting.mosaico/ ?
