### ISSUE TITLE
Blank screen when creating Mosaico template

### ISSUE THREAD

**Issue by mfuggle** [veda-consulting/uk.co.vedaconsulting.mosaico#8]
I have installed the Mosaico CiviCRM extension seemingly successfully. However when I try to create a new template I get two errors in the Drupal log file as shown in the attached images.
I would appreciate it if someone could help me locate the problem.

Cheers
Martin Fuggle

![mosaico 1](https://cloud.githubusercontent.com/assets/1777429/13731626/ed452e48-e9c1-11e5-8756-3b7d09de2b49.jpg)
![mosaico 2](https://cloud.githubusercontent.com/assets/1777429/13731628/f4b3999e-e9c1-11e5-8cb4-b0c8da5387ec.jpg)

**Comment by mfuggle** [comment]
I have switched allow_url_fopen from off to on and that removed the errors above but I am now getting a 403 error and cannot see why. Permissions appear to be OK and directory/file ownership is www-data which is the Apache setting. Is that correct?

**Comment by deepak-srivastava** [comment]
@mfuggle Thanks for posting issues here. Your email was in my queue. Posting here means others also get the benefit and one of our team can respond quickly.

Check if there is any htaccess file in dist/img dir. 
I think drupal adds a htaccess file in anything thats in files fir. So may be keep the extension out of files dir or remove or fix any htaccess that might be present.

**Comment by mfuggle** [comment]
There is no htaccess file in dist/img. The permissions are 664 and the ownership is www-data:www-data on the files mentioned.

**Comment by deepak-srivastava** [comment]
May be some parent directories?

If nothing works out might be worth trying extension in another location. May be default dir? e.g - sites/default/uk.co.vedaconsulting.mosaico

**Comment by mfuggle** [comment]
This is certainly a permissions issue and with the extensions directory located in sites/default/files/etc the default directory has permissions of 555 which can't be changed otherwise Drupal will complain since the settings files are in that directory. If I move the extensions directory under the sites dir and then copy all existing extensions to that directory do the existing extensions continue to function? So at the moment I am not able to have a look at the Mosaico extension which is a pity since it would help my users significantly.

**Comment by deepak-srivastava** [comment]
Are you able to figure out whats the problem with files dir. And / or whats denying the permission there?
I remember doing one of the install myself in files dir and that required tweaking htaccess file.

@PalanteJon @mark-rodgers I'm assuming you guys also have extensions in files dir. Any suggestions for @mfuggle ?

**Comment by mfuggle** [comment]
I have a number of other extensions including veda consulting Mailchimp extension and have had no issue with any of them. It's only the Mosaico extension that seems to have a permissions problem when installed in the sites/default/files/etc  directory.

**Comment by PalanteJon** [comment]
@Martin 3 thoughts:
* most other extensions don't write to the extensions directory. Since you posted this, there's a new commit which greatly reduces, if not eliminates, what Mosaico is writing to the directory. Try installing from master?
* you can turn up Apache debugging to see the exact file/path being denied. 
* I submitted an issue on this extension which resulted in my doing a check for imageMagick. I did it as a hook, but it was suggested I inline the warning. Maybe add a file system permission check where it was suggested I put the other check?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by deepak-srivastava** [comment]
UPDATE:  [alpha3](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/releases/tag/1.0-alpha3) has been released.

**Comment by mfuggle** [comment]
alpha3 gets past the issues so that I am now able to see the templates. However I have a secoond issue insofar as Imagemagick is not found. I'll open another issue with the details.

**Comment by mark-rodgers** [comment]
@mfuggle read the install instructions. Imagemagick is required to be installed on your hosting environment

**Comment by deepak-srivastava** [comment]
Thanks @mfuggle and @PalanteJon for putting efforts in answering queries and submitting patches. Very much appreciated. :+1: 
Closing this ticket for now, as there is a new one filed - https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/14
