### ISSUE TITLE
Something Went Wrong While Saving Message Template

### ISSUE THREAD

**Issue by ae6** [veda-consulting/uk.co.vedaconsulting.mosaico#80]
Environment:  
- Drupal 7.53
- CiviCRM 4.6.24
- Extension Beta

When I attempt to save a Mosaico template (even if saving the initial template), I get the message:
"Something went wrong while saving message template"

The PHP log states:
Notice: Undefined variable: args in CRM_Core_IDS->kick() (line 257 of /var/www/wwwadmin/data/www/<site>/sites/all/modules/civicrm/CRM/Core/IDS.php).

Warning: implode(): Invalid arguments passed in CRM_Core_IDS->kick() (line 257 of /var/www/wwwadmin/data/www/<site>/sites/all/modules/civicrm/CRM/Core/IDS.php).

If I set the bypass skip for IDS in permissions, then it saves the template.

The CiviCRM Log for this portion is attached

[Mosaico_IDS_Error_On_Template_Save.txt](https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/files/655868/Mosaico_IDS_Error_On_Template_Save.txt)

Thank you for all your good work on this extension.

**Comment by deepak-srivastava** [comment]
Check suggestions / workaround in this ticket - https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/52#issuecomment-253535006

**Comment by mattwire** [comment]
Please update to 2.0  1.x is no longer supported
