### ISSUE TITLE
Message templates appear blank after printing

### ISSUE THREAD

**Issue by eugeneegbe** [veda-consulting/uk.co.vedaconsulting.mosaico#9]
Hello, 
          I am using wordpress andI have followed the installation procedure of the extension, but when i use the link of the message builder i get the mosaico template page but the templates appear blank 

a screenshot is shown below 
![issue](https://cloud.githubusercontent.com/assets/6907539/13742900/e17e3cae-e9de-11e5-86ce-78f7afb9d745.png)

**Comment by deepak-srivastava** [comment]
1. Are you using alpha2 version (or above)?

2. Do you have extension resource url configured as mentioned in installation instruction?

**Comment by eugeneegbe** [comment]
Hi @Deepak,
                           i am using alpha2 but i check under the resource
url i sae the string [civicrm.files]/ext/ i dont know what it means and I
dont know what it mens to configure the resource URL pls can you help me?

thanks


On Mon, Mar 14, 2016 at 1:07 PM, Deepak Srivastava <notifications@github.com

**Comment by deepak-srivastava** [comment]
@eugeneegbe so from the menu if you visit "Administer » System Settings » Resouce URLs, you should be able to set "Extension Resource URL" setting. Its mainly web url for your extension.

For e.g a drupal installation might have it something like:
http://example.org/sites/default/custom_civicrm/extensions/
[might differ for your installation]

for a wordpress installation:
http://example.org/wp-content/plugins/civicrm/custom_civicrm/extensions/
[again might differ for your installation]

**Comment by deepak-srivastava** [comment]
@eugeneegbe there's been a new alpha3 release you might want to try - https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/releases/tag/1.0-alpha3

**Comment by petednz** [comment]
in case it relates to this issue too, a solution at https://github.com/veda-consulting/uk.co.vedaconsulting.mosaico/issues/12#issuecomment-203647558

**Comment by deepak-srivastava** [comment]
Closing this ticket. Please re-open if different if still an issue or not same as #12. Thanks.
