### ISSUE TITLE
Template Builder not loading

### ISSUE THREAD

**Issue by simonneal72** [veda-consulting/uk.co.vedaconsulting.mosaico#92]
Running CiVi 4.7.14
Wordpress 4.7.2
Mosaico 1.0-beta1

New to extension was recommended to us by MillerTech

Installed and enabled extension but on clicking on Message Template builder it trys to load but ends up with a blank screen.

Not sure I have imageMagick installed so tried installing  imageMagick wordpress plugin to no avail.

**Comment by jakevv** [comment]
You need to have the imagemagick installed on your server environment (as a php module).

**Comment by simonneal72** [comment]
Thanks thats what I thought but Im not sure how to do that. Are there any instructions you can point me too? I'm hosted at Heartinternet so its shared hosting.

**Comment by jakevv** [comment]
These instructions may work if you have SSH access:
https://help.dreamhost.com/hc/en-us/articles/217253537-ImageMagick-and-imagick-PHP-module-on-Shared-hosting

Otherwise your best bet is to contact your host and ask them to install and
enable the module.

**Comment by tonyhrx** [comment]
Hi guys. I'm getting a WSOD when trying to launch Mosaico template builder. I'm getting these errors
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (mosaico-material.min.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (knockout.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (stylesheet.css, line 0)

And looking at the distribution the directory "packages" is not there at all on this path

/sites/default/files/civicrm/ext/uk.co.vedaconsulting.mosaico/packages/mosaico/dist/vendor/knockout.js

**Comment by petednz** [comment]
can you clarify how you dealt with the requirements for
org.civicrm.bootstrapcivihr
org.civicrm.flexmailer

**Comment by tonyhrx** [comment]
If that's directed at me Pete, I'll do another install on another site and post back

**Comment by petednz** [comment]
Thx Tony.

**Comment by veda-consulting** [comment]
We'll also be running some tests later this week so will feedback too.

Parvez Saleh

Managing Director

 vedaconsulting.co.uk

 +44 (0) 33 3011 8874 <#UNIQUE_ID_SafeHtmlFilter_>

 90 Mainyard, 90 Wallis Rd
London, E9 5LN

<https://twitter.com/vedaconsulting>
<https://www.facebook.com/vedaconsulting>
<https://uk.linkedin.com/in/vedaconsulting>

**Comment by mattwire** [comment]
Please update to 2.0  1.x is no longer supported
