### ISSUE TITLE
Loss of CiviMail content possible when making changes to Mosaico template

### ISSUE THREAD

**Issue by axon-obriend** [veda-consulting/uk.co.vedaconsulting.mosaico#93]
I'll say first how much I appreciate the work that's been done on this...

We've got a client that's been trying to use Mosaico and we've found a fairly serious "usability issue" with Beta 1 that's unfortunately caused the loss of several hours of work. Here's what happened:

- Client created a Mosaico template and saved it. So far, so good.
- Later, client returned to the email, this time clicking Edit on the "User-driven Messages" tab, and saved it.
- Finally, the client went back into Mosaico and added a section and saved it. At this point, the content on the CiviMail template was overwritten with the new Mosaico template with the dummy text and image placeholders.

I did some of my own testing and found that
- The template name and template subject that are displayed are the same on the User-driven Messages and Mosaico tab
- Changes made on the User-driven Messages tab persisted when saved and did not affect the content on the Mosaico side
- Saving changes to the Mosaco template overwrote the existing content on the User-driven Messages side
- Most importantly, there's no warning that you're going to clobber any content that's been altered on the CiviMail side
- Further, it's confusing to see the same Template Name/Template Subject on the User-driven Messages tab and the Mosaico tab, and in most cases, the same content when clicking Edit and have no indication that you're looking at two different things.

I understand that this is (probably) working exactly as designed. (And, yes, I do know what a "beta" is.) I've been following the developer chat and I know there's some major changes afoot, too. Mostly I'm creating the issue so I can tell the client I did something and hope that someone reads it and avoids this particular "oops."

**Comment by veda-consulting** [comment]
Thanks for the feedback. Deepak is back in 2 weeks and we'll be looking to
put a release together for the next version then. Normally clients use one
or other for emails and hence we haven't had any reports of this yet but I
understand the impact. Maybe a short term solution would be to ensure the
naming is designated for your client i.e. MOSAICO prefix on all templates
that are created in mosaico. The subject can always be amended during the
email sending stages.



Veda Consulting
t : +44 (0) 20 3239 1156
m : +44 (0) 77 4216 3491
e : parvez@vedaconsulting.co.uk
w : www.vedaconsulting.co.uk

**Comment by mattwire** [comment]
Please update to 2.0  1.x is no longer supported
