### ISSUE TITLE
Unexpected error when talking to server: Contact us

### ISSUE THREAD

**Issue by cmistry** [veda-consulting/uk.co.vedaconsulting.mosaico#94]
Hi
I've installed beta on drupal 7.53/ civicrm 4.7.15, following all the installation instructions.
It works really well, until I try to save my template, or send a test email.  Then I get 
"Unexpected error talking to server: Contact Us"
I can see in Chrome and Firefox console it tries to post to ...civicrm/mosaico/dl but I get fail returned from that with a 403 Forbidden.
I just wondered if anyone else has experienced that, and what they did to fix it
Thanks

**Comment by josh-ecocentre** [comment]
Also having this issue. Did you find a fix? @cmistry  @totten

**Comment by mattwire** [comment]
Please update to 2.0  1.x is no longer supported
